folio-org/stripes-testing

- cypress/e2e/fee-fine/cancel-fee-fine.cy.js
- cypress/e2e/fee-fine/fees-fines-list-loading.cy.js
- cypress/support/fragments/users/userAllFeesFines.js
- cypress/support/fragments/users/usersCard.js
[C368476](https://foliotest.testrail.io/index.php?/cases/view/368476)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6302/allure/)
> C368476 Check that Fees/fines list loading if user have any Fees/fines (vega) (TaaS)

- cypress/e2e/fee-fine/bill-actual-cost-for-item-with-declare-lost-status.cy.js
- cypress/e2e/fee-fine/declare-lost-do-not-bill.cy.js
- cypress/support/fragments/users/billActualCostModal.js
- cypress/support/fragments/users/lostItemsRequiringActualCostPage.js
[C374115](https://foliotest.testrail.io/index.php?/cases/view/374115)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6412/allure)
> C374115 Verify ability to bill actual cost for item with "Declared lost" status (vega) (TaaS)

- cypress/e2e/invoices/attach-file-to-approved-paid-invoice.cy.js
- cypress/e2e/invoices/upload-file-to-invoice.cy.js
- cypress/support/fragments/invoices/invoiceView.js
- cypress/support/fragments/invoices/invoices.js
[C360544](https://foliotest.testrail.io/index.php?/cases/view/360544)
[C360546](https://foliotest.testrail.io/index.php?/cases/view/360546)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6461/allure)
***
> [360544] Attaching file to approved invoice (thunderjet) (TaaS)

- cypress/e2e/settings/data-import/check-po-status-is-required.cy.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
[C380419](https://foliotest.testrail.io/index.php?/cases/view/380419)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6445/allure)
***
> [380419] Confirm that "Purchase order status" is a required field (folijet) (TaaS)

- cypress/e2e/settings/data-import/check-material-type-field-inactive-after-update-status-to-open.cy.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileView.js
[C380543](https://foliotest.testrail.io/index.php?/cases/view/380543)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6449/allure)
***
> [380543] Verify that Material type field is inactive (folijet) (TaaS)

- cypress/e2e/inventory/instance/instance-administrative-note.cy.js
- cypress/support/fragments/inventory/holdings/inventoryHoldings.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/inventory/inventoryInstances.js
[C359146](https://foliotest.testrail.io/index.php?/cases/view/359146)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6446/allure/)
> C359146 Search "Instance" with source = Folio/MARC by administrative note using query search (spitfire) (TaaS)

- cypress/e2e/checkin/check-in-show-in-house-use.cy.js
- cypress/support/fragments/check-in-actions/checkInPane.js
[C9182](https://foliotest.testrail.io/index.php?/cases/view/9182)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6459/allure)
> C9182 Check In: show in-house use (vega) (TaaS)

- cypress/e2e/consortia/facet-options-shown-by-performing-search-in-member.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
https://issues.folio.org/browse/FAT-10468
https://foliotest.testrail.io/index.php?/cases/view/414981
> FAT-10468/C414981-Consortia

- cypress/e2e/settings/data-import/check-electronic-resource-details-if-order-format-other.cy.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
- cypress/support/utils/interactorsTools.js
[C380524](https://foliotest.testrail.io/index.php?/cases/view/380524)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6485/allure)
***
> [380524] Electronic resource details are not active when Order format is other (folijet) (TaaS)

- cypress/e2e/data-import/importing-marc-bib-files/add-subfields-to-linked-fields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/can't-delete-protected-linked-fields-using-update-marcBib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/edit-protected-and-linked-fields-using-update-marcbib-profile.cy.js
- cypress/e2e/marc/marc-holdings/holding-quickmark.cy.js
https://issues.folio.org/browse/FAT-10195
> FAT-10195/Test fixes

- cypress/e2e/users/filter-users-by-tags.cy.js
- cypress/support/fragments/users/usersSearchPane.js
- cypress/support/fragments/users/usersSearchResultsPane.js
[C373214](https://foliotest.testrail.io/index.php?/cases/view/343214)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6470/allure/)
> C343214 Filter users by tags (volaris) (TaaS)

- cypress/e2e/settings/data-import/check-po-status-is-required.cy.js
- cypress/e2e/settings/data-import/check-stacking-of-bill-to-ship-to-addresses.cy.js
- cypress/e2e/settings/tenant/tenant-view-general.cy.js
- cypress/support/fragments/settings/configs.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
- cypress/support/fragments/settings/tenant/general/addresses.js
[C376000](https://foliotest.testrail.io/index.php?/cases/view/376000)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6532/allure)
***
> [376000] Check stacking of Bill to/Ship to addresses (folijet) (TaaS)

- cypress/e2e/inventory/item/check-new-formatting-statistical-codes-field-on-item-create-screen.cy.js
- cypress/support/fragments/inventory/item/itemRecordNew.js
- interactors/selection.js
https://foliotest.testrail.io/index.php?/cases/view/400654
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6462/allure/#behaviors/b1a8273437954620fa374b796ffaacdd/407091719cf0341a/
> C400654 Check the new formatting of Statistical codes field on Item create/edit screen (folijet)

- cypress/e2e/orders/populate-claiming-interval-from-organization.cy.js
- cypress/support/fragments/orders/orderLineDetails.js
- cypress/support/fragments/orders/orderLineEditForm.js
- cypress/support/fragments/organizations/newOrganization.js
[C423436](https://foliotest.testrail.io/index.php?/cases/view/423436)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6559/allure)
***
> [423436] Populate claiming interval from organization (thunderjet) (TaaS)

- cypress/support/fragments/finance/funds/funds.js
> [FIX] C374183, C375066, C375067, C375068

- cypress/e2e/loans/renewal-success-loan-details.cy.js
[C580](https://foliotest.testrail.io/index.php?/cases/view/580)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6499/allure)
> C580 Renewal: success, from loan details (vega) (TaaS)

- cypress/e2e/consortia/inventory/call-number-browse/facet-options-shown-by-performing-search-in-central.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/facet-options-shown-by-performing-search-in-member.cy.js
https://issues.folio.org/browse/FAT-10469
https://foliotest.testrail.io/index.php?/cases/view/414980
> FAT-10469/C414980-Consortia

- cypress/e2e/orders/item-status-changed-to-order-closed.cy.js
- cypress/e2e/orders/reopen-order-w-multiple-order-lines.cy.js
> [FIX] C366113, C366114, C367963

- cypress/e2e/invoices/initial-encumbrance-remain-the-same-after-cancelling-related-invoice.cy.js
> [FIX] C400612, C400614, C400615, C400618

- cypress/support/fragments/users/loans/userLoans.js
> [FIX] C10960

- cypress/e2e/invoices/attach-file-to-approved-paid-invoice.cy.js
> [FIX] C360544, C360546

- cypress/support/fragments/orders/orders.js
https://foliotest.testrail.io/index.php?/cases/view/353617
> fixed 353617 

- cypress/e2e/data-export/export-failed-using-non-existent-UUIDs.cy.js
> Fix for C353209

- cypress/e2e/orders/location-dd-in-order-line-allows-parentheses.cy.js
- cypress/support/fragments/orders/orderLineEditForm.js
> [FIX] C367957

- cypress/e2e/receiving/export/export-results-to-csv-from-receiving.cy.js
> [FIX] C353981

- cypress/e2e/eholdings/title+package/add-agreement-to-package.cy.js
- cypress/support/fragments/eholdings/eHoldingsResourceView.js
> [FIX] C752

- cypress/e2e/invoices/fiscal-year-specifies-expecse-class-selection.cy.js
- cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
> [FIX] C388520, C388545

- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-not-include-data-deleted-record.cy.js
> FIX C375230

- cypress/e2e/inventory/search/browse-subjects-pane-remains-same-results-when-switch-back.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
[FAT-11007](https://issues.folio.org/browse/FAT-11007)
Fix test cases C400617, C380405
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6607/allure/#behaviors/b1a8273437954620fa374b796ffaacdd/a1783722834d49c5/)
> Fix test cases

- cypress/e2e/loans/loan-dates.cy.js
- cypress/e2e/settings/circulation/patron-notices/create-patron-notice-template.cy.js
- cypress/e2e/title-level-request/check-cannot-change-tlr-modal.cy.js
- cypress/support/fragments/settings/circulation/patron-notices/newNoticePolicyTemplate.js
- interactors/rich-text-editor.js
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6605/allure/#suites
> Volaris autotest maintenance

- cypress/e2e/consortia/inventory/instance/Browse/subject-browse-member-no-shared.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
- cypress/support/fragments/inventory/search/browseSubjects.js
- package.json
FAT ticket - https://issues.folio.org/browse/FAT-11144
Test case - https://foliotest.testrail.io/index.php?/cases/view/422238
Results - 
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6615/allure
> FAT-11144-C422238-Consortia

- cypress/e2e/loans/loan-change-due-dates.cy.js
- cypress/support/fragments/requests/newRequest.js
> FIX-C581-C1284

- cypress/e2e/title-level-request/edit-recall-request.cy.js
> [FIX] 380500

- cypress/e2e/loans/loans-actions-while-claim-returned.cy.js
> [FIX] 10958

- cypress/e2e/data-import/importing-marc-bib-files/add-$9-to-linkable-fields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/add-subfields-to-linked-fields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/can't-delete-protected-linked-fields-using-update-marcBib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-$0-subfield-from-linked-not-repeatable-marc-bib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-$9-from-not-linkable-marc-bib-fields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-linked-field-which-controlled-by-marc-authority.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-repeatable-linked-field-controlled-by-marcAuth.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-uncontrolled-subfield-of-linked-marcBib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/edit-protected-and-linked-fields-using-update-marcbib-profile.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/marc-bib-import-delete-linked-field.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-$0-in-linked-repeatable-field.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controllable-and-not-controlable-subfields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controllable-letter-subfield-in-linked-repeatable-field.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controllable-subfield0.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controlled-and-not-controlled-subfields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-linked-marc-bib-record-with-multiple-$0.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-several-linked-controllable-subfield0.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-tag-value-of-linked-marcBib-controlled-by-marcAuth.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/verify-correct-number-of-linked-records.cy.js
- cypress/e2e/marc/marc-authority/delete-one-marc-bib-linked-marc-authority.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/user-without-permission-can't-see-link-headings-button.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/instance-quickmark.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/unlink-bib-record-with-save-and-keep-editing-in-editing-window.cy.js
- cypress/e2e/marc/marc-holdings/holdings-record-through-upload.cy.js
- cypress/e2e/marc/marc-holdings/holdings-records-Instancesource-folio.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
https://issues.folio.org/browse/FAT-11072
> FAT-11072/Tests fixes

- cypress.config.js
- cypress/e2e/consortia/inventory/instance/holding-actions-menu-on-central-tenant-for-member-librarys-holdings-record.cy.js
- cypress/e2e/consortia/inventory/instance/share-local-instance-button-for-folio-instance.cy.js
- cypress/support/api/consortium.js
- cypress/support/api/users.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/inventory/inventoryInstance.js
https://issues.folio.org/browse/FAT-10345
https://issues.folio.org/browse/FAT-10347
https://issues.folio.org/browse/FAT-10349
https://issues.folio.org/browse/FAT-10351
https://foliotest.testrail.io/index.php?/cases/view/411343
https://foliotest.testrail.io/index.php?/cases/view/411329
https://foliotest.testrail.io/index.php?/cases/view/411345
https://foliotest.testrail.io/index.php?/cases/view/411334
> Fat 10345 fat 10347 fat 10349 fat 10351

- cypress/e2e/consortia/orders/shared-instance-can-be-created-linked-instance-when-creating-package-pol.cy.js
- cypress/support/fragments/orders/orderLines.js
***
[FAT-10864](https://issues.folio.org/browse/FAT-10864)
***
[C411690](https://foliotest.testrail.io/index.php?/cases/view/411690)
***
***
> Implement of FAT-10864

- cypress/e2e/consortia/data-import/importing-marcBib-files/adding-deleting-fields-and-subfields-when-updating-shared-marcBib-in-central-via-DI-and-confirm-in-member.cy.js
- cypress/e2e/consortia/data-import/importing-marcBib-files/adding-deleting-fields-and-subfields-when-updating-shared-marcBib-in-member.cy.js
- cypress/e2e/consortia/data-import/importing-marcBib-files/update-shared-marcBib-in-central-via-DI-and-changes-flow-to-member.cy.js
- cypress/e2e/consortia/data-import/importing-marcBib-files/update-shared-marcBib-in-member-via-DI-and-confirm-in-central-and-member.cy.js
- cypress/e2e/consortia/inventory/instance/limited-edit-permissions-for-shared-marc-folio-instance-on-member.cy.js
- cypress/e2e/consortia/inventory/instance/shared-instance-is-updated-using-DI-from-member.cy.js
- cypress/e2e/consortia/inventory/instance/source-of-marc-folio-instance-on-central.cy.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/settings/consortium-manager/consortium-manager.js
***
https://issues.folio.org/browse/FAT-10281
***
https://foliotest.testrail.io/index.php?/cases/view/402763
***
***
> FAT-10281-C402763

- cypress/e2e/consortia/inventory/instance/limited-edit-permissions-for-shared-marc-folio-instance-on-member.cy.js
- cypress/e2e/consortia/inventory/instance/source-of-marc-folio-instance-on-central.cy.js
***
https://issues.folio.org/browse/FAT-10280
***
https://foliotest.testrail.io/index.php?/cases/view/402762
***
***
> FAT-10280-C402762

- cypress/e2e/consortia/inventory/instance/source-of-marc-folio-local-instance-on-member.cy.js
***
https://issues.folio.org/browse/FAT-10279
***
https://foliotest.testrail.io/index.php?/cases/view/402761
***
***
> FAT-10279-C402761

- cypress/e2e/consortia/inventory/instance/action-for-creating-new-shared-instances-for-central.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
***
https://issues.folio.org/browse/FAT-10282
***
https://foliotest.testrail.io/index.php?/cases/view/405564
***
***
> FAT-10282-C405564

- cypress/e2e/consortia/orders/receiving-for-shared-instance-in-member-tenant.cy.js
***
[FAT-10866](https://issues.folio.org/browse/FAT-10866)
***
[C411742](https://foliotest.testrail.io/index.php?/cases/view/411742)
***
***
> Implementing of FAT-10866

- cypress/e2e/invoices/accounting-number-is-not-specified-in-voucher-export-details.cy.js
- cypress/e2e/invoices/approve-invoice-is-disabled.cy.js
- cypress/e2e/invoices/attach-file-to-approved-paid-invoice.cy.js
- cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-cancelled.cy.js
- cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
- cypress/e2e/orders/edit-fund-when-invoice-paid-cancelled.cy.js
- cypress/e2e/orders/encumbered-amount-is-not-changed-after-deleting-received-piece-when-order-closed-C375986.cy.js
- cypress/support/fragments/invoices/voucherExportForm.js
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6715/allure)
***
> Test fixes

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-series-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField240-to-authority111-with-subfield-0.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField600-to-authority100-with-multiple-subfield-0.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField611-to-authority111.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField655-to-authority155.cy.js
https://issues.folio.org/browse/FAT-10406
> FAT-10406/Test fixes

- cypress/e2e/consortia/can-not-view-a-users-affiliations-accordion.cy.js
- cypress/support/fragments/users/usersCard.js
***
[FAT-10876](https://issues.folio.org/browse/FAT-10876)
***
[C380507](https://foliotest.testrail.io/index.php?/cases/view/380507)
***
***
> Implementing of FAT-10876

- cypress/e2e/consortia/marc/marc-bibliographic/derive-marcBib/derive-from-shared-marc-bib-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/manual-linking/marc-bib-shared-link-shared-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/manual-linking/marc-bib-shared-link-shared-member.cy.js
Functional changes:
- Update ECS tests according to MODELINKS-191: 2
Tuning tests: 
- Update test clean-up for ECS: 1
> Spitfire ECS fixes

- cypress/e2e/consortia/inventory/instance/edit-shared-instance-on-member-without-central-editing-permissions.cy.js
- cypress/e2e/consortia/inventory/instance/share-local-instance-functionality-for-folio-instance.cy.js
- cypress/e2e/consortia/inventory/instance/share-local-instance-functionality-for-marc-instance.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/inventory/inventoryInstance.js
https://folio-org.atlassian.net/browse/FAT-11369
https://folio-org.atlassian.net/browse/FAT-10213
https://folio-org.atlassian.net/browse/FAT-10283
https://foliotest.testrail.io/index.php?/cases/view/411289
https://foliotest.testrail.io/index.php?/cases/view/411292
https://foliotest.testrail.io/index.php?/cases/view/407750
> FAT-10283 FAT-11369 FAT-10213

- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/error-notification-confirmation-modal-when-saving-marc-bib-record-with-invalid-ldr.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/instance-quickmark.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
Stabilize test cases C353610, C353612: make tests independent of the changing LDR value of the loaded file.
> Stabilize test cases C353610, C353612 

- cypress/e2e/consortia/inventory/contributor-browse/contributor-browse-member-no-shared.cy.js
- cypress/support/fragments/inventory/search/browseContributors.js
- package.json
FAT ticket - https://folio-org.atlassian.net/browse/FAT-11956
Test case - https://foliotest.testrail.io/index.php?/cases/view/422237
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6806/allure
> FAT-11956-C422237

- cypress/e2e/consortia/users/add-service-point-when-editing-shadow-user.cy.js
- cypress/support/fragments/users/userEdit.js
https://folio-org.atlassian.net/browse/FAT-10315
https://foliotest.testrail.io/index.php?/cases/view/422215
> added test for FAT-11380

- cypress/e2e/consortia/inventory/instance/header-local-instance-edit-page-member-tenant.cy.js
- cypress/e2e/consortia/inventory/instance/header-shared-instance-edit-page-member-tenant.cy.js
- cypress/e2e/consortia/inventory/instance/header-shared-instance-member-tenant.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
https://folio-org.atlassian.net/browse/FAT-10317
https://folio-org.atlassian.net/browse/FAT-10315
https://foliotest.testrail.io/index.php?/cases/view/404357
https://foliotest.testrail.io/index.php?/cases/view/404354
> Fat 10317 fat 10315

- cypress/e2e/consortia/consortium-manager/user-is-not-able-to-edit-and-delete-from-member-tenant-circulation.cy.js
- cypress/support/fragments/settings/circulation/cancellationReason.js
- cypress/support/login.js
***
[FAT-10232](https://issues.folio.org/browse/FAT-10232)
***
[C400666](https://foliotest.testrail.io/index.php?/cases/view/400666)
***
***
> Implement FAT-10232

- cypress/e2e/consortia/inventory/instance/header-shared-instance-central-tenant.cy.js
- cypress/e2e/consortia/inventory/instance/header-shared-instance-edit-page-central-tenant.cy.js
https://folio-org.atlassian.net/browse/FAT-10319
https://folio-org.atlassian.net/browse/FAT-10316
https://foliotest.testrail.io/index.php?/cases/view/404385
https://foliotest.testrail.io/index.php?/cases/view/404355
> FAT-10316 FAT-10319

- cypress/e2e/consortia/data-import/importing-marcBib-files/adding-deleting-fields-and-subfields-when-updating-shadow-marcBib-in-member-via-DI.cy.js
- cypress/e2e/consortia/inventory/instance/link-in-data-export-app-after-exporting-shared-folio-source-instance-from-instance-search-results-pane-on-member.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10297
***
https://foliotest.testrail.io/index.php?/cases/view/422077
***
***
> FAT-10297-C422077

- cypress/e2e/eholdings/package/attach-package-to-existing-agreement.cy.js
- cypress/e2e/marc/marc-authority/advanced-search/advanced-search-exact-phrase.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-import.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-series-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/all-linkable-fields-not-linked-except-already-linked-ones.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/all-linkable-fields-linked-except-already-linked-ones.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-fields-using-link-headings-button.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/manual-and-auto-linking-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/unlink-auto-linked-fields-manual-link-edit-and-auto-link-again.cy.js
[FAT-12030](https://folio-org.atlassian.net/browse/FAT-12030)
Stabilize and fix falling test cases
> FAT-12030 Stabilize falling test cases

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/request-cancellation-reason-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/user-with-permission-is-able-add-delete-request-cancellation-reason.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/user-with-permission-is-able-add-edit-request-cancellation-reason.cy.js
- cypress/e2e/consortia/consortium-manager/user-is-not-able-to-edit-and-delete-from-member-tenant-circulation.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-alternative-title-types/view-affiliated-alternative-title-types-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-classification-identifier-types/view-affiliated-classification-identifier-types-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-departments/view-affiliated-departments-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-patron-groups/view-affiliated-patron-groups-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-request-cancellation-reasons/view-affiliated-request-cancellation-reasons-with-given-permissions.cy.js
- cypress/support/fragments/consortium-manager/circulation/requestCancellationReasonsConsortiumManager.js
- cypress/support/fragments/consortium-manager/consortiaControlledVocabularyPaneset.js
- cypress/support/fragments/consortium-manager/consortiumManagerApp.js
- cypress/support/fragments/consortium-manager/inventory/instances/alternativeTitleTypesConsortiumManager.js
- cypress/support/fragments/consortium-manager/inventory/instances/classificationIdentifierTypesConsortiumManager.js
- cypress/support/fragments/consortium-manager/modal/delete-cancel-reason.js
- cypress/support/fragments/consortium-manager/users/departmentsConsortiumManager.js
- cypress/support/fragments/consortium-manager/users/patronGroupsConsortiumManager.js
- cypress/support/fragments/settings/users/departments.js
- cypress/support/fragments/settingsMenu.js
[FAT-12126](https://folio-org.atlassian.net/browse/FAT-12126)
> Refactoring ECS autotests that interact with "consortia-controlled-vocabulary-paneset"

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/user-with-permission-is-able-add-delete-classification-identifier-type.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/user-with-permission-is-able-add-delete-request-cancellation-reason.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/user-with-permission-is-able-add-edit-request-cancellation-reason.cy.js
- cypress/support/fragments/consortium-manager/circulation/requestCancellationReasonsConsortiumManager.js
- cypress/support/fragments/consortium-manager/inventory/instances/classificationIdentifierTypesConsortiumManager.js
[FAT-11008](https://folio-org.atlassian.net/browse/FAT-11008)
***
[User with "Consortium manager: Can share settings to all members" permission is able to add/delete classification identifier type shared to all affiliated tenants in "Consortium manager" app](https://foliotest.testrail.io/index.php?/cases/view/410900)
> FAT-11008/C410900

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/classification-identifier-type-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-request-cancellation-reasons/request-cancellation-reason-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/support/fragments/consortium-manager/consortiaControlledVocabularyPaneset.js
[FAT-11011](https://folio-org.atlassian.net/browse/FAT-11011)
***
[Classification identifier type can be shared to all tenants in "Consortium manager" app regardless permission and affiliation](https://foliotest.testrail.io/index.php?/cases/view/410902)
> FAT-11011/C410902

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/classification-identifier-type-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/user-with-permission-is-able-add-delete-classification-identifier-type.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/user-with-permission-is-able-add-edit-classification-identifier-type.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-departments/department-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-departments/user-with-permission-is-able-add-delete-department.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-departments/user-with-permission-is-able-add-edit-department.cy.js
[FAT-10878](https://folio-org.atlassian.net/browse/FAT-10878)
***
[Department can be shared to all tenants in "Consortium manager" app regardless permission and affiliation](https://foliotest.testrail.io/index.php?/cases/view/407740)
***
> FAT-10878/C407740

- cypress/e2e/consortia/consortium-manager/user-is-not-able-to-edit-and-delete-from-member-tenant-inventory-holdings.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/consortium-manager/inventory/instances/holdingsNoteTypesConsortiumManager.js
- cypress/support/fragments/consortium-manager/inventory/instances/holdingsTypesConsortiumManager.js
- cypress/support/fragments/settings/inventory/holdings/holdingsNoteTypes.js
- cypress/support/fragments/settings/inventory/holdings/holdingsTypes.js
- cypress/support/fragments/settingsMenu.js
***
[FAT-10235](https://issues.folio.org/browse/FAT-10235)
***
[C401723](https://foliotest.testrail.io/index.php?/cases/view/401723)
***
***
> Implement FAT-10235

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-instance-note-types/user-with-permission-is-able-add-delete-instance-note-types.cy.js
- cypress/support/fragments/settings/inventory/instance-note-types/instanceNoteTypes.js
[FAT-11012](https://folio-org.atlassian.net/browse/FAT-11012)
***
[User with "Consortium manager: Can share settings to all members" permission is able to add/delete instance note type shared to all affiliated tenants in "Consortium manager" app
](https://foliotest.testrail.io/index.php?/cases/view/410931)
***
> FAT-11012/C410931

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-alternative-title-types/alternative-title-types-can-be-shared-regardless-permission-and-affiliation.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-alternative-title-types/user-with-permission-is-able-add-delete-alternative-title-types.cy.js
- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-alternative-title-types/user-with-permission-is-able-add-edit-alternative-title-types.cy.js
- cypress/support/fragments/consortium-manager/inventory/instances/alternativeTitleTypesConsortiumManager.js
[FAT-10885](https://folio-org.atlassian.net/browse/FAT-10885)
***
[User with "Consortium manager: Can share settings to all members" permission is able to add/delete alternative title type shared to all affiliated tenants in "Consortium manager" app
](https://foliotest.testrail.io/index.php?/cases/view/410875)
***
> FAT-10885/C410875

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-instance-note-types/instance-note-types-can-be-shared-regardless-permission-and-affiliation.cy.js
[FAT-11014](https://folio-org.atlassian.net/browse/FAT-11014)
***
[Instance note type can be shared to all tenants in "Consortium manager" app regardless permission and affiliation
](https://foliotest.testrail.io/index.php?/cases/view/410933)
***
> FAT-11014/C410933

- cypress.config.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-call-number-components-changed.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
Fix test case C388510
Revert changes in cypress.config
> FAT-12336 Stabilize/fix falling test cases 

- cypress/support/fragments/inventory/inventoryInstance.js
Update the InventoryInstance.waitLoading() method as the previous one stops working
> FAT-12336 Stabilize/fix falling test cases

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-add-notes-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-body-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-suppressed-holdings-false-items-not.cy.js
- cypress/e2e/marc/marc-holdings/moving-items.cy.js
- cypress/support/fragments/settings/inventory/items/itemNoteTypes.js
- cypress/support/fragments/users/userEdit.js
https://folio-org.atlassian.net/browse/FAT-12310
> FAT-12310_1

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-modes-of-issuance/modes-of-issuance-can-be-shared-regardless-permission-and-affiliation.cy.js
[FAT-11017](https://folio-org.atlassian.net/browse/FAT-11017)
***
[Mode of issuance can be shared to all tenants in "Consortium manager" app regardless permission and affiliation
](https://foliotest.testrail.io/index.php?/cases/view/410955)
***
> FAT-11017/C410955

- cypress/e2e/marc/marc-authority/create-marc-authority/verify-options-in-authority-file-look-up-modal-one-local-active.cy.js
[FAT-12380](https://folio-org.atlassian.net/browse/FAT-12380)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/422243)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6889/allure/#behaviors/b1a8273437954620fa374b796ffaacdd/141c80f650a568b7/)
> FAT-12380/C422243

- cypress/e2e/organizations/making-organization-donor-and-vice-versa.cy.js
- cypress/support/fragments/organizations/organizations.js
***
[FAT-12405](https://issues.folio.org/browse/FAT-12405)
***
[C421981](https://foliotest.testrail.io/index.php?/cases/view/421981)
***
***
> Implement FAT-12405

- cypress.config.js
- cypress/e2e/agreements/agreement-internal-contacts/assign-library-staff-member-to-agreement.cy.js
- cypress/e2e/agreements/agreement-internal-contacts/filter-agreements-by-library-staff-member-assigned.cy.js
- cypress/e2e/circulation-log/circulation-log-barcodes.cy.js
- cypress/e2e/circulation-log/filtering-circulation-log-by-fee-fine-actions.cy.js
- cypress/e2e/circulation-log/user-without-barcode.cy.js
- cypress/e2e/eureka/user-permissions-not-shown.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit.cy.js
- cypress/e2e/users/search-by-middle-name.cy.js
- cypress/e2e/users/usertype-fields-displays-on-create-user-page.cy.js
- cypress/e2e/users/verify-that-proxies-and-sponsors-are-sorted.cy.js
- cypress/support/api/permissions.js
- cypress/support/api/users.js
- cypress/support/fragments/users/userEdit.js
- cypress/support/fragments/users/users.js
- moved system admin role name to config file (to be available from all files)
- updated method for adding permissions to use admin role
- updated one test (fixed wrong argument sequence in method)
- updated usernames in several tests to lowercase
-- Keyloak on Eureka converts all usernames to lowercase internally but does not change Folio username
-- Then usernames in KC and Folio might differ which may cause issues
> Eureka fixes

- cypress/e2e/settings/data-import/placing-of-action-profiles-in-edited-job-profile.cy.js
- cypress/support/fragments/data_import/job_profiles/jobProfileEdit.js
***
https://folio-org.atlassian.net/browse/FAT-12221
***
https://foliotest.testrail.io/index.php?/cases/view/423385
***
***
> FAT-12221-C423385

- cypress/e2e/eureka/authorization-roles/create-role-no-capabilities-or-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-only-sets.cy.js
- cypress/e2e/eureka/user-permissions-not-shown.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12472
Test case - https://foliotest.testrail.io/index.php?/cases/view/430264
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6899/allure/
> FAT-12472-C430264-Eureka

- cypress/e2e/eureka/authorization-roles/selecting-capabilities-and-sets.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12503
Test case - https://foliotest.testrail.io/index.php?/cases/view/434129
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6902/allure
> FAT-12503-C434129

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/ldr-length-tag-validation-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/ldr-validation-rules-with-valid-data-when-deriving.cy.js
Update test cases C380398, C422118
> FAT-12403 Update automated E2E tests because of UI updates in "LDR" field

- cypress/e2e/data-import/importing-marc-bib-files/action-profile-is-only-unlinked-once-when-used-in-multiple-times-in-job-profile.cy.js
- cypress/e2e/settings/data-import/remove-default-action-profile.cy.js
- cypress/support/fragments/data_import/job_profiles/jobProfileView.js
***
https://folio-org.atlassian.net/browse/FAT-12223
***
https://foliotest.testrail.io/index.php?/cases/view/423473
***
***
> FAT-12223-C423473

- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12509
Test case - https://foliotest.testrail.io/index.php?/cases/view/430260
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6908/allure
> FAT-12509-C430260

- cypress/e2e/data-import/importing-marc-authority-files/marc-authority-update.cy.js
> FAT-12346 Fix test cases

- cypress/e2e/consortia/consortium-manager/view-settings/view-alternative-title-types/view-affiliated-alternative-title-types-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-classification-identifier-types/view-affiliated-classification-identifier-types-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-departments/view-affiliated-departments-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-instance-note-types/view-affiliated-instance-note-types-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-patron-groups/view-affiliated-patron-groups-with-given-permissions.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-request-cancellation-reasons/view-affiliated-request-cancellation-reasons-with-given-permissions.cy.js
https://folio-org.atlassian.net/browse/FAT-12580
> q-ecs-thunderjet-fixes

- cypress/e2e/eureka/authorization-roles/assign-capabilities-to-renamed-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-empty-role.cy.js
- cypress/support/api/permissions.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12630
Test case - https://foliotest.testrail.io/index.php?/cases/view/423999
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12631
Test case - https://foliotest.testrail.io/index.php?/cases/view/431152
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6933/allure/
> FAT-12630-C423999

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-error-after-typing-non-existing-item-location.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-body-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-permanent-temporary-location-at-once.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-errors-accordion-correct-identifier.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-holdings-records-contains-select-option-placeholder.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-narrow-down-options.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-no-error-after-select-location.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-user-unable-to-edit-instances.cy.js
- cypress/e2e/data-export/data-export-errors-accordion.cy.js
- cypress/e2e/settings/users/fee&Fine/schedule-time.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/data-export/dataExportViewAllLogs.js
https://folio-org.atlassian.net/browse/FAT-12608
> FAT-12608-1

- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority.cy.js
- cypress/support/fragments/eholdings/eHoldingsProviderEdit.js
- cypress/support/fragments/quickMarcEditor.js
https://folio-org.atlassian.net/browse/FAT-12551
> FAT-12551/Test fixes

- cypress/e2e/data-import/importing-marc-holdings-files/source-value-of-imported-marc-holdings-record.cy.js
- cypress/e2e/marc/marc-authority/mark-auth-delete-auth-ref-record-with-linked-field-in-marc-bib.cy.js
https://folio-org.atlassian.net/browse/FAT-12523
> FAT-12523/Daily run test fixes

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-fields-with-$9.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-pre-defined-linkable-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/all-linkable-fields-not-linked-except-already-linked-ones.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/add-$9-before-click-link-headings-when-edit-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-fields-using-link-headings-button.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/pre-defined-fields-linked-after-click-link-headings.cy.js
> FAT-12583 Fix/update test cases in bugfest

- cypress/e2e/organizations/viewing-and-editing-banking-information-record-with-organizations.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/organizations/organizations.js
***
[FAT-12535](https://issues.folio.org/browse/FAT-12535)
***
[C423504](https://foliotest.testrail.io/index.php?/cases/view/423504)
***
***
> Implement FAT-12535

- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12629
Test case - https://foliotest.testrail.io/index.php?/cases/view/430265
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6943/allure/#
> FAT-12629-C430265

- cypress/e2e/eureka/authorization-roles/assign-capabilities-to-renamed-role.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps-sets.cy.js
- cypress/e2e/eureka/users/user-permissions-not-shown.cy.js
- cypress/support/api/permissions.js
- cypress/support/api/users.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12558
Test case - https://foliotest.testrail.io/index.php?/cases/view/430262
- - -
Also, updated/fixed following existing tests:
- C431152
- C442842
- - -
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6952/allure
> FAT-12558-C430262 (new test, updates)

- cypress/e2e/data-import/importing-marc-bib-files/add-subfields-to-linked-fields.cy.js
- cypress/e2e/marc/marc-authority/open-marc-bib-130-field-using-number-of-title-link.cy.js
- cypress/e2e/marc/marc-authority/open-marc-bib-610-field-using-number-of-title-link.cy.js
- cypress/e2e/marc/marc-authority/open-marc-bib-650-field-using-number-of-title-link.cy.js
- cypress/e2e/marc/marc-authority/open-marc-bib-711-field-using-number-of-title-link.cy.js
> FAT-12745 Fix test cases for poppy

- cypress/e2e/inventory/search/browse-subjects-pane-remains-same-results-when-switch-back.cy.js
- cypress/e2e/inventory/search/change-selected-search-option-when-facet-is-applied.cy.js
- cypress/e2e/inventory/search/search-for-instance-by-title-field-without-spec-chars.cy.js
- cypress/e2e/inventory/search/subject-browse.cy.js
Updated authorization for API calls in several tests (removed UI authorization and replaced with `cy.getAdminToken()`
> Spitfire LoC pre-val auth fixes

- cypress/e2e/inventory/search/search-for-instance-by-contributor-name-field-with-spec-chars.cy.js
Remove authorization in data import app
> Remove authorization in data import app

- cypress/e2e/eureka/authorization-roles/create-new-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12819
Test case - https://foliotest.testrail.io/index.php?/cases/view/423998
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6971/allure/
> FAT-12819-C423998

- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-auth-file-with-default-prefix.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-record-with-different-prefix-in-010-field.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-delete-10-field-of-record-when-010-a-0.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-with-multiple-001-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/add-multiple-001-when-deriving.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bib-add-multiple-001s.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bib-edit.cy.js
- cypress/e2e/marc/marc-holdings/add-multiple-001s-edit-marc-holdings.cy.js
- cypress/support/fragments/quickMarcEditor.js
Add steps to the test case C374161 according to the ticket:
[FAT-12800](https://folio-org.atlassian.net/browse/FAT-12800)
[Test rail](https://foliotest.testrail.io//index.php?/cases/view/374161)
Improve and rename the method QuickMarcEditor.checkFourthBoxDisabled()
Remove obsolete methods
> FAT-12800/Update the test case C374161

- cypress/e2e/finance/fiscalYears/displaying-settings-for-test-rollover.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/consecutive-rollovers-within-three-fiscal-years.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollover-is-blocked.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollover-when-pol-has-2-funds.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollovers-within-3-fy-when-polcontains-2-funds.cy.js
- cypress/e2e/finance/funds/add-allocation-to-budget.cy.js
- cypress/e2e/finance/funds/add-transfer-to-budget.cy.js
- cypress/e2e/finance/funds/create-encumbrance-from-order.cy.js
- cypress/e2e/finance/transactions/unrelease-encumbrance.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-dollar.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-percent.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-with-added-adjustment-amount-to-invoice-line-not-prorated.cy.js
- cypress/e2e/invoices/approve-and-pay-more-than-one-invoice.cy.js
- cypress/e2e/invoices/approve-invoice-with-payment-credit.cy.js
- cypress/e2e/invoices/approve-invoice.cy.js
- cypress/e2e/invoices/change-fund-before-approve-invoice.cy.js
- cypress/e2e/invoices/edit-subscription-info-and-dates-after-approve.cy.js
- cypress/e2e/invoices/error-message-appears-when-approve-invoice-from-previous-budget.cy.js
- cypress/e2e/invoices/invoices.createCreditInvoice.cy.js
- cypress/e2e/invoices/invoices.manuallyCreateLineFromPol.cy.js
- cypress/e2e/invoices/invoices.testPolSearchPlugin.cy.js
- cypress/e2e/invoices/pay-invoice-with-multiple-xpense-classes.cy.js
- cypress/e2e/invoices/pay-invoice.cy.js
- cypress/e2e/invoices/search-invoices.cy.js
- cypress/e2e/invoices/update-accordion-labels-and-logic-on-invoice.cy.js
- cypress/e2e/settings/finance/user-finance-view-setting-only-view-appropriate-settings.cy.js
- authorization fixes
- added required arguments to one method
- removed eurekaPhase1 label from one test
> Eureka Thunderjet fixes

- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic.cy.js
- cypress/e2e/marc/marc-hodings/holdings-record-through-upload.cy.js
- cypress/support/fragments/marcAuthority/marcAuthorities.js
- cypress/support/fragments/quickMarcEditor.js
https://folio-org.atlassian.net/browse/FAT-12782
> Poppy tests' fixes

- cypress/e2e/inventory/search/search-in-inventory-linked-authID.cy.js
- cypress/e2e/marc/marc-authority/marc-authority-sort.cy.js
- cypress/e2e/marc/marc-authority/open-marc-bib-110-field-using-number-of-title-link.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/pre-defined-fields-linked-after-click-link-headings.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bib-save-and-close.cy.js
- cypress/e2e/marc/marc-hodings/edit-marc-holdings.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/plug-in-marc-authority-search-by-childrens-subject-heading.cy.js
- cypress/e2e/permissions/marc-authority-view.cy.js
- cypress/support/api/requests.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/marcAuthority/marcAuthorities.js
- cypress/support/fragments/settings/circulation/titleLevelRequests.js
> FAT-12859 Fix test cases for poppy

- cypress/e2e/inventory/instance/eureka-experim.cy.js
- cypress/e2e/invoices/filter-invoices.cy.js
- cypress/e2e/orders/create-order-withPol-different-formats.cy.js
- cypress/e2e/orders/po-filters-with-cLose-order.cy.js
- cypress/e2e/orders/po-filters.cy.js
- cypress/e2e/orders/pol-filters.cy.js
Auth fixes for more Thunderjet tests
> Eureka Thunderjet fixes 2

- cypress/e2e/export-manager/check-view-jobs.cy.js
- cypress/e2e/export-manager/export-orders-in-edifact-format/sorting-by-export-method-does-not-reset-search-results.cy.js
- cypress/e2e/export-manager/job-for-order-with-acquisition-unit.cy.js
- cypress/e2e/export-manager/orders-export-to-a-vendor/days-for-weekly-scheduling-are-not-displaying-in-new-scheduling-settings.cy.js
- cypress/e2e/export-manager/orders-export-to-a-vendor/trying-to-open-an-order-with-2-pol.cy.js
- cypress/e2e/finance/check-available-balance.cy.js
- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/expense-classes-none.cy.js
- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/export-settings-active-status.cy.js
- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/export-settings-all-statuses-with-ex-classes.cy.js
- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/export-settings-inactive-status-with-rollover-and-2-exp-classes.cy.js
- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/export-settings-inactive-status-without-rollover-with-2-exp-classes.cy.js
- cypress/e2e/finance/ledgers/ledger-summary-calculation-after-allocation-movement.cy.js
- cypress/e2e/orders/edifact-export-to-a-vendor.cy.js
- cypress/e2e/orders/edifact-exports/delete-order-by-user.cy.js
- cypress/support/fragments/organizations/organizations.js
Auth fixes for Thunderjet tests for Eureka
> Eureka thunderjet fixes 3

- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-subfield-0-controlled-field.cy.js
- cypress/e2e/marc/marc-authority/mark-auth-delete-auth-ref-record-with-linked-field-in-marc-bib.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-edit-ldr.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/manual-linking/cancel-unlinking-marc-bib-field-from-marc-authority-record.cy.js
- cypress/support/fragments/quickMarcEditor.js
https://folio-org.atlassian.net/browse/FAT-12894
> Fixed Q bugfest non ECS tests

- cypress/e2e/eureka/authorization-roles/delete-empty-role.cy.js
- cypress/e2e/eureka/authorization-roles/delete-role.cy.js
- cypress/support/api/permissions.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
- interactors/accordion.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12945
Test case - https://foliotest.testrail.io/index.php?/cases/view/446119
Result - 
- - - -
FAT ticket - https://folio-org.atlassian.net/browse/FAT-12946
Test case - https://foliotest.testrail.io/index.php?/cases/view/446120
- - - -
Result:
> FAT-12945-FAT-12945

- cypress/e2e/consortia/inventory/search-in-inventory/use-shared-facet-when-search-executed-in-member.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/use-shared-facet-when-search-not-executed-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/browse/apply-shared-facet-to-browse-result-list-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/marc-authority-local-edit-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-shared-linked-marc-auth-record-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/automated-linking/auto-linking-shared-marcBib-with-shared-marcAuth-on-central.cy.js
- cypress/e2e/consortia/marc/plug-in-marc-authority/searching-browsing-authority-in-central.cy.js
- cypress/e2e/inventory/search/search-by-alternative-title-of-linked-record.cy.js
- cypress/support/fragments/quickMarcEditor.js
https://folio-org.atlassian.net/browse/FAT-13149
> Fixed daily run and ECS tests

- cypress.config.js
- cypress/e2e/consortia/inventory/search-in-inventory/use-shared-facet-when-search-executed-in-member.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/use-shared-facet-when-search-not-executed-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/browse/apply-shared-facet-to-browse-result-list-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/marc-authority-local-edit-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-shared-linked-marc-auth-record-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/automated-linking/auto-linking-shared-marcBib-with-shared-marcAuth-on-central.cy.js
- cypress/e2e/consortia/marc/plug-in-marc-authority/searching-browsing-authority-in-central.cy.js
https://folio-org.atlassian.net/browse/FAT-13140
> Fixed Q ECS bugfest tests

- cypress/e2e/eureka/authorization-roles/assigning-users/assigned-users-in-role-view.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-in-role-view.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket 1 - https://folio-org.atlassian.net/browse/FAT-13137
Test case 1 - https://foliotest.testrail.io/index.php?/cases/view/442816
- - - - 
FAT ticket 2 - https://folio-org.atlassian.net/browse/FAT-13138
Test case 2 - https://foliotest.testrail.io/index.php?/cases/view/442836
- - - - 
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7010/allure
> FAT-13137-FAT-13138

- cypress/e2e/marc/marc-authority/marc-authority-print-option.cy.js
- cypress/e2e/marc/marc-holdings/add-multiple-001s-when-creating-marc-holdings-record.cy.js
- cypress/e2e/marc/marc-holdings/error-notif-shown-before-modals-when-saving-marcHold-record-while-editing-record.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-call-number-components-changed.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-fields-not-related-to-item-are-changed.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/search-using-advanced-search-option.cy.js
- cypress/support/fragments/marcAuthority/marcAuthority.js
Fix/update test cases in extended path
> FAT-13139 Fix/update test cases in extended path

- cypress/e2e/data-import/importing-marc-authority-files/import-marcAuth-without-010-job-profile-matching-010-update-and-create-action.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/import-derive-marc-bib-record-which-has-subfields.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-delete.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-import.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit-008-field.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/verify-source-value-displays-only-last-name.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic-edit.cy.js
- cypress/e2e/marc/marc-holdings/error-notif-shown-before-modals-when-saving-marcHold-record-while-editing-record.cy.js
- cypress/e2e/marc/marc-holdings/holding-quickmark.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-call-number-components-changed.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-fields-not-related-to-item-are-changed.cy.js
- cypress/e2e/marc/marc-holdings/marc-holdings-call-number-types.cy.js
- cypress/e2e/marc/marc-holdings/modify-marc-holdings-of-deleted-user.cy.js
> FAT-13225 Support automated tests for eureka

- cypress/e2e/eureka/authorization-roles/edit-role-only-name-description.cy.js
- cypress/e2e/eureka/users/password-reset-link-generated.cy.js
- cypress/support/fragments/users/userEdit.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13247
Test case - https://foliotest.testrail.io/index.php?/cases/view/434077
- - - - 
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13250
Test case - https://foliotest.testrail.io/index.php?/cases/view/424003
- - - - 
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7019/allure
> FAT-13247-FAT-13250

- cypress/e2e/eureka/authorization-roles/edit-role-only-capabilities.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13249
Test case - https://foliotest.testrail.io/index.php?/cases/view/436929
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7021/allure/
> FAT-13249-C436929

- cypress/e2e/data-import/importing-marc-bib-files/delete-$0-subfield-from-linked-not-repeatable-marc-bib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controllable-subfield0.cy.js
- cypress/e2e/eholdings/tags-from-other-application-not-shown-in-search-filter.cy.js
- cypress/e2e/inventory/search/advanced-or-not-search-in-inventory.cy.js
- cypress/e2e/inventory/search/advanced-search-in-inventory.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit-008-field.cy.js
- cypress/e2e/marc/marc-holdings/add-multiple-001s-when-creating-marc-holdings-record.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-call-number-components-changed.cy.js
- cypress/e2e/marc/marc-holdings/item-metadata-updates-when-holdings-fields-not-related-to-item-are-changed.cy.js
- cypress/e2e/marc/marc-holdings/marc-holdings-call-number-types.cy.js
Fix, stabilize test cases for Q BugFest
> FAT-13034 Fix, stabilize test cases for Q BugFest

- cypress/e2e/eureka/authorization-roles/assign-capabilities-to-renamed-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-new-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-only-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-capabilities.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-name-description.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps-sets.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
1) Updated the following tests according to UIROLES-41:
- C423998
- C430262
2) Updated method names
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7023/allure
> FAT-13359-updates

- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/support/login.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13248
Test case - https://foliotest.testrail.io/index.php?/cases/view/424001
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7042/allure
> FAT-13248-C424001

- cypress/e2e/eureka/users/assigning-roles-user-edit.cy.js
- cypress/support/fragments/users/userEdit.js
- cypress/support/fragments/users/usersCard.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13793
Test case - https://foliotest.testrail.io/index.php?/cases/view/466113
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7045/allure
> FAT-13793-C466113

- cypress/e2e/settings/marc-authority/edit-all-editable-fields-of-folio-authority-file-with-assigned-record.cy.js
- cypress/support/api/authority.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
[FAT-13622](https://folio-org.atlassian.net/browse/FAT-13622)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/436863)
> FAT-13622/C436863

- cypress/e2e/eureka/users/unassigning-roles-user-edit.cy.js
- cypress/support/fragments/users/userEdit.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13892
Test case - https://foliotest.testrail.io/index.php?/cases/view/466114
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7050/allure
> FAT-13892: test added

- cypress/e2e/settings/marc-authority/hrid-starts-with-field-length-validation-during-editing-local-authority-file.cy.js
[FAT-13828](https://folio-org.atlassian.net/browse/FAT-13828)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/436953)
> FAT-13828/ C436953

- cypress/e2e/data-import/importing-marc-bib-files/delete-uncontrolled-subfield-of-linked-marcBib.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/edit-protected-and-linked-fields-using-update-marcbib-profile.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-$0-in-linked-repeatable-field.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-controllable-subfield0.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/update-several-linked-controllable-subfield0.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-api.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-export-manager.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/user-can't-link-bibField100-with-wrong-record.cy.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
> FAT-13819 Support automated tests for eureka

- cypress/e2e/settings/marc-authority/create-new-authority-file-hrid-starts-with-field-special-characters-validation.cy.js
[FAT-13827](https://folio-org.atlassian.net/browse/FAT-13827)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/436951)
> FAT-13827/C436951

- cypress/e2e/data-import/importing-marc-authority-files/importing-marc-authority-files.cy.js
- cypress/e2e/eholdings/title+package/eholdings-titles-packages-export-selected.cy.js
- cypress/e2e/inventory/search/display-records-with-same-values-in-subject-field-and-linked-to-record.cy.js
- cypress/e2e/inventory/search/search-by-alternative-title-of-linked-record.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-delete.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-update-header.cy.js
- cypress/e2e/marc/marc-holdings/modify-marc-holdings-of-deleted-user.cy.js
- cypress/support/fragments/notes/notesEholdings.js
https://folio-org.atlassian.net/browse/FAT-13507
> Fixed eureks tests

- cypress/e2e/consortia/edit-tenant-name-in-consortium-manager-settings.cy.js
- cypress/e2e/consortia/users/add-service-point-when-editing-shadow-user.cy.js
- cypress/e2e/consortia/view-user-affiliations-accordion.cy.js
- cypress/support/api/users.js
- cypress/support/dictionary/affiliations.js
- cypress/support/fragments/settings/consortium-manager/consortium-manager.js
- cypress/support/fragments/users/userEdit.js
Updated several methods, configs, tests to work better with ECS on Eureka
> Eureka ECS updates

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-non-existent-relationship.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-uri.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- interactors/select.js
https://folio-org.atlassian.net/browse/FAT-13823
https://foliotest.testrail.io/index.php?/cases/view/423494
> FAT--13823

- cypress/e2e/settings/marc-authority/create-new-authority-file-base-url-field-uniqueness-validation.cy.js
[FAT-13829](https://folio-org.atlassian.net/browse/FAT-13829)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/440086)
> FAT-13829/C440086

- cypress/e2e/inventory/search/search-in-inventory-symbols.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-pre-defined-linkable-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/all-linkable-fields-not-linked-except-already-linked-ones.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/add-$9-before-click-link-headings-when-edit-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-fields-using-link-headings-button.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/pre-defined-fields-linked-after-click-link-headings.cy.js
Return the indices of the fields that should not have been changed to their initial values
> FAT-13918 Support automated test cases for quesnelia

- cypress/e2e/consortia/data-import/importing-marcAuthority-files/imported-marcAuthority-record-from-central-discoverable-in-central-member.cy.js
- cypress/e2e/consortia/data-import/importing-marcAuthority-files/imported-marcAuthority-record-from-member-not-discoverable-in-central.cy.js
- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic-edit.cy.js
- cypress/e2e/marc/marc-holdings/holding-quickmark.cy.js
- cypress/e2e/marc/marc-holdings/modify-marc-holdings-of-deleted-user.cy.js
- cypress/support/fragments/data_import/logs/logs.js
Replace the string type argument with a regular expression to adapt the method to an environment with the "split" functionality in Data import app.
> FAT-13818 Support automated tests in daily run

- cypress/e2e/settings/marc-authority/base-url-field-uniqueness-validation-during-editing-folio-authority-file.cy.js
- cypress/e2e/settings/marc-authority/edit-all-editable-fields-of-folio-authority-file-with-assigned-record.cy.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
[FAT-13832](https://folio-org.atlassian.net/browse/FAT-13832)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/440091)
> FAT-13832/C440091

- cypress/e2e/eureka/authorization-roles/assign-capabilities-to-renamed-role.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigned-users-in-role-view.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-in-role-view.cy.js
- cypress/e2e/eureka/authorization-roles/create-empty-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-new-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-no-capabilities-or-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-only-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/delete-empty-role.cy.js
- cypress/e2e/eureka/authorization-roles/delete-role.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-capabilities.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-name-description.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps-sets.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/role-with-only-sets-api.cy.js
- cypress/e2e/eureka/authorization-roles/selecting-capabilities-and-sets.cy.js
- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/e2e/eureka/users/assigned-roles-in-user-view.cy.js
- cypress/e2e/eureka/users/assigning-roles-user-edit.cy.js
- cypress/e2e/eureka/users/password-reset-link-generated.cy.js
- cypress/e2e/eureka/users/unassigning-roles-user-edit.cy.js
- cypress/e2e/eureka/users/user-permissions-not-shown.cy.js
- cypress/e2e/inventory/instance/eureka-experim.cy.js
- cypress/support/api/permissions.js
- cypress/support/api/users.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-13968
Updated Eureka auto-tests with required minimal capabilities for test users.
Tests handled in scope of this update:
C423998
C436928
C430260
C430264
C430262
C430265
C424001
C436929
C424003
C423999
C431152
C434129
C446119
C446120
C464313
C442816
C442836
C434077
C466113
C466114
C464314
> FAT-13968-updates

- cypress.config.js
- cypress/e2e/eureka/authorization-roles/assign-capabilities-to-renamed-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-new-role.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-no-capabilities-or-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-capabilities.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-name-description.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps-sets.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/e2e/eureka/users/unassigning-roles-user-edit.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
Updates adapting Eureka auto-tests to FSE Dry run 1 module versions (mainly reverting recent updates for evrk2)
> dry-run: updated Eureka tests

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-unassigning-users-in-role-view.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14149
Test case - https://foliotest.testrail.io/index.php?/cases/view/442837
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7103/allure
> Fat 14149 c442837

- cypress/e2e/inventory/search/browse-contributors.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
Adjust the test case C358148 according to the Test rail, 
Fix the locator
> FAT-14128 Support/review automated tests for eureka

- cypress/e2e/data-import/importing-marc-bib-files/update-controlled-and-not-controlled-subfields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-fields-using-link-headings-button.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
- cypress/support/fragments/marcAuthority/marcAuthorities.js
Add deleteMarcAuthorityByTitleViaAPI() method
> FAT-14127 Support automated tests in daily run

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-user-name-changed.cy.js
- cypress/e2e/eureka/settings/settings-permission-sets-absent.cy.js
- cypress/support/fragments/users/userEdit.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14273
Test case - https://foliotest.testrail.io/index.php?/cases/view/451613
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7105/allure
> FAT-14273-C451613

- cypress/e2e/consortia/inventory/instance/edit-instance-button-on-central-instance-page.cy.js
- cypress/e2e/inventory/instance/in-accordion-admin-data-instance-status-term-validate-matching-settings.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
***
https://folio-org.atlassian.net/browse/FAT-10323
***
https://foliotest.testrail.io/index.php?/cases/view/409460
***
***
> FAT-10323-C409460

- cypress/e2e/consortia/inventory/instance/view-source-button-on-central-instance-page.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10324
***
https://foliotest.testrail.io/index.php?/cases/view/409461
***
***
> FAT-10324-C409461

- cypress/e2e/consortia/inventory/instance/add-marc-holdings-button-on-central-instance-page.cy.js
- cypress/support/fragments/inventory/instanceRecordView.js
***
https://folio-org.atlassian.net/browse/FAT-10333
***
https://foliotest.testrail.io/index.php?/cases/view/409473
***
***
> FAT-10333-C409473

- cypress/e2e/consortia/inventory/instance/edit-marc-bibliographic-record-button-on-central-instance-page.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10334
***
https://foliotest.testrail.io/index.php?/cases/view/409474
***
***
> FAT-10334-C409474

- cypress/e2e/settings/data-export/field-mapping-profile-with-suppression.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
https://folio-org.atlassian.net/browse/FAT-14152
> FAT-14152-2

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-error-handling.cy.js
- cypress/support/utils/interactorsTools.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14295
Test case - https://foliotest.testrail.io/index.php?/cases/view/491278
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7106/allure/#
> FAT-14295: test added

- cypress/e2e/inventory/search/advanced-search-in-inventory.cy.js
- cypress/support/fragments/data_import/dataImport.js
- cypress/support/fragments/inventory/inventoryInstances.js
Fix uploadFileWithSplitFilesViaApi() method, 
Update the test case id according to the Test rail, add search option
> FAT-14127 Support automated tests in daily run 

- cypress/e2e/permissions/view-reading-room-access-permission.cy.js
- cypress/support/dictionary/permissions.js
https://folio-org.atlassian.net/browse/FAT-14266
https://foliotest.testrail.io/index.php?/cases/view/466237
> FAT-14266/C466237 User can view reading room access permission

- cypress/e2e/data-import/importing-marc-bib-files/delete-repeatable-linked-field-controlled-by-marcAuth.cy.js
- cypress/e2e/inventory/search/browse-and-search-capabilities-are-separated.cy.js
- cypress/e2e/inventory/search/browse-call-numbers-only-correct-types.cy.js
- cypress/e2e/inventory/search/browse-contributors.cy.js
- cypress/e2e/marc/marc-authority/marc-authority-sort.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/$9-validation-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-series-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/manual-and-auto-linking-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/ldr-validation-rules-with-valid-data.cy.js
- cypress/e2e/marc/marc-hodings/create-new-marc-holdings-edit-ldr.cy.js
- cypress/e2e/marc/marc-hodings/create-new-marc-holdings.cy.js
- cypress/e2e/marc/marc-hodings/marc-holdings-edit-ldr.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
Update the IDs of the test cases, fix tests
> FAT-14479 Support/review automated tests for poppy

- package.json
> RANCHER-1529. The package.json file now includes a new version of the agent-js-cypress package.

- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-import.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-api.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-linked-marc-bib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/marc-bibliographic-unlink-fields.cy.js
- cypress/support/fragments/quickMarcEditor.js
Stabilize test cases C360521, C360522,
Update the test data according to the Test rail in the test case C380529,
Add methods for interaction with fields by tag value
> FAT-14422 Support automated tests in daily run 

- cypress/e2e/eureka/authorization-roles/role-general-info.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14514
Test case - https://foliotest.testrail.io/index.php?/cases/view/464307
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7143/allure
> FAT-14514-C464307

- cypress/e2e/inventory/call-number/call-number-not-valid-format-with-dewey-can-be-found-in-browse.cy.js
- cypress/e2e/inventory/call-number/call-number-not-valid-format-with-lc-can-be-found-in-browse.cy.js
- cypress/e2e/inventory/call-number/call-number-not-valid-format-with-nlm-can-be-found-in-browse.cy.js
- cypress/e2e/inventory/call-number/call-number-not-valid-format-with-sudoc-can-be-found-in-browse.cy.js
- cypress/e2e/inventory/search/plug-in-search-marBib-by-lccn-normolized-option-using-query-with-asteriks.cy.js
- cypress/e2e/marc/marc-authority/search-marcAuth-by-lccn-using-query-without-prefix-when-lccn-has-spaces.cy.js
- cypress/e2e/marc/marc-authority/search-marcAuth-by-lccn-using-query-without-spaces.cy.js
https://folio-org.atlassian.net/browse/FAT-14065
https://foliotest.testrail.io/index.php?/cases/view/451470
> FAT-14065/C451470

- cypress/e2e/eureka/authorization-policies/policy-general-info.cy.js
- cypress/e2e/eureka/authorization-roles/role-general-info.cy.js
- cypress/support/api/auth-policies.js
- cypress/support/api/index.js
- cypress/support/api/permissions.js
- cypress/support/api/tenant.js
- cypress/support/constants.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
- cypress/support/fragments/topMenu.js
- cypress/support/utils/dateTools.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14527
Test case - https://foliotest.testrail.io//index.php?/cases/view/464308
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7150/allure
---
Also updated C464307 to set default locale before run
> FAT-14527-C464308

- cypress/e2e/inventory/instance/duplicating-instance-on-non-consortia-tenant-with-source-folio.cy.js
***
https://folio-org.atlassian.net/browse/FAT-14440
***
https://foliotest.testrail.io/index.php?/cases/view/410929
***
https://folio-org.atlassian.net/browse/FAT-14442
***
https://foliotest.testrail.io/index.php?/cases/view/410930
***
***
> FAT-14440-FAT-14442

- cypress/e2e/inventory/instance/share-local-instance-button-does-not-appear-on-non-consortia-tenant.cy.js
***
https://folio-org.atlassian.net/browse/FAT-14444
***
https://foliotest.testrail.io/index.php?/cases/view/411383
***
***
> FAT-14444-C411383

- cypress/e2e/eureka/authorization-roles/role-capabilities-loading-animation.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
- interactors/checkbox.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-14572
Test rail - https://foliotest.testrail.io/index.php?/cases/view/434130
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7153/allure
> FAT-14572-C43413

- cypress/e2e/inventory/instance/closing-after-add-item-action-on-non-consortia-tenant.cy.js
***
https://folio-org.atlassian.net/browse/FAT-14656
***
https://foliotest.testrail.io/index.php?/cases/view/411681
***
***
> FAT-14656-C411681

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-staff-only-for-added-notes.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-instances-hrids.cy.js
https://folio-org.atlassian.net/browse/FAT-14778
> FAT-14778-2

- cypress/support/fragments/data-export/exportMappingProfile/exportFieldMappingProfiles.js
https://folio-org.atlassian.net/browse/FAT-14778
> FAT-14778-3

- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/support/fragments/eholdings/eHoldingsPackage.js
https://folio-org.atlassian.net/browse/FAT-14909
> FAT-14909/Fixed tests

- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
After changes in https://folio-org.atlassian.net/browse/UIBULKED-440 it's required to update selector, because Select was replaced with Selection component.
> FAT-14900 Change selector for bulk-edit In app approach

- cypress/e2e/fse/ui/erm-comparison-ui.cy.js
- cypress/e2e/fse/ui/erm-usage-ui.cy.js
- cypress/e2e/fse/ui/local-kb-admin-ui.cy.js
ERM tests removed from default sanity check suite.
> Erm related tests removed from default sanity check

- cypress/e2e/eholdings/package/eholdings-custom-packages.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/created-marcAuth-could-be-found-using-search-and-browse.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
Stabilize the tests in daily run
> FAT-14822 Support/review automated test case in daily/weekly runs

- cypress/e2e/eureka/users/promoting-user-to-authUser.cy.js
- cypress/support/api/users.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-14967
- https://folio-org.atlassian.net/browse/FAT-14968
Test cases: 
- https://foliotest.testrail.io/index.php?/cases/view/451631
- https://foliotest.testrail.io//index.php?/cases/view/451632
Allure report:
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7195/allure
> FAT-14967-14968

- cypress/e2e/settings/circulation/create-edit-delete-request-policies.cy.js
- cypress/support/fragments/circulation/request-policy.js
https://folio-org.atlassian.net/browse/FAT-14433
> C1218: Settings (Circ): Can create, edit and remove request policies

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-body-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-source-null.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-add-admin-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-find-remove-admin-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-find-replace-admin-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-admin-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-status-unchanged.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-are-you-sure-form.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-cancel.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-duplicate-checkout-note-checkin.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-form.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-location-contains-char.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-narrow-down-options.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-suppress-from-discovery-option.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-suppressed-holdings-true.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-view-holdings-items.cy.js
- cypress/e2e/inventory/moving-item-between-holdings.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-logs.js
- cypress/support/fragments/data-export/dataExportViewAllLogs.js
- cypress/support/fragments/users/userEdit.js
https://folio-org.atlassian.net/browse/FAT-14958
> FAT-14958-2

- cypress/e2e/inventory/search/search-by-electronic-access-field-of-item-in-case-insensitive.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
[FAT-14838](https://folio-org.atlassian.net/browse/FAT-14838)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/466084)
> FAT-14838/C466084

- cypress/e2e/eureka/authorization-roles/selecting-capabilities-and-sets-edit.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-15097
Test case - https://foliotest.testrail.io/index.php?/cases/view/503019
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7203/allure
- - - 
_Note:_ `TO DO`s will be implemented when current issues on the environment are resolved
> FAT-15097-C503019

- cypress/e2e/inventory/search/search-by-call-number-field-of-item-record-is-case-insensitive.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/manual-linking/derive-restore-deleted-and-saved-linked-field-of-marcBib-record-in-deriving-window.cy.js
https://folio-org.atlassian.net/browse/FAT-14817
https://foliotest.testrail.io/index.php?/cases/view/466082
> FAT-14817/C466082

- cypress/e2e/eureka/users/roles-sorting-in-user-view-edit.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-15260
Test case - https://foliotest.testrail.io/index.php?/cases/view/476793
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7220/allure
> FAT-15260-C476793

- cypress/e2e/inventory/settings/view-mode-of-isri-profiles.cy.js
- cypress/e2e/permissions/inventory/browse-call-numbers-and-subjects.cy.js
- cypress/e2e/permissions/inventory/new-button-active-on-z3950-profiles-with-settings-inventory-configure-single-record-import-permission.cy.js
- cypress/support/fragments/settings/inventory/integrations/z39.50TargetProfiles.js
***
https://folio-org.atlassian.net/browse/FAT-15149
***
https://foliotest.testrail.io/index.php?/cases/view/494346
***
***
> FAT-15149-C494346

- cypress/e2e/permissions/inventory/edit-button-active-on-z3950-profiles-with-settings-inventory-configure-single-record-import-permission.cy.js
- cypress/support/fragments/settings/inventory/integrations/z39.50TargetProfiles.js
***
https://folio-org.atlassian.net/browse/FAT-15150
***
https://foliotest.testrail.io/index.php?/cases/view/494347
***
***
> Fat 15150 c494347

- cypress/e2e/eureka/authorization-roles/create-role-add-app.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-15379
Test case - https://foliotest.testrail.io//index.php?/cases/view/496123
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7256/allure
> FAT-15379-C496123

- cypress/e2e/inventory/instance/instance-notes.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
***
https://folio-org.atlassian.net/browse/FAT-15152
***
https://foliotest.testrail.io/index.php?/cases/view/615
***
***
> FAT-15152-C615

- cypress/e2e/consortia/inventory/instance/edit-instance-button-on-central-instance-page.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/item-update-via-match-by-status.cy.js
- cypress/e2e/inventory/instance/green-success-toast-appears-when-instance-is-saved.cy.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/statisticalCodes.js
***
https://folio-org.atlassian.net/browse/FAT-15215
***
https://foliotest.testrail.io/index.php?/cases/view/345346
***
> FAT-15215-C345346

- cypress/e2e/inventory/instance/subjects.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
- cypress/support/fragments/inventory/instanceRecordView.js
***
https://folio-org.atlassian.net/browse/FAT-15214
***
https://foliotest.testrail.io/index.php?/cases/view/617
***
***
> FAT-15214-C617

- cypress/e2e/bulk-edit/logs/bulk-edit-logs-generation-files-for-users-query.cy.js
- cypress/e2e/circulation-log/filter-closed-loan.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-files.js
- cypress/support/fragments/bulk-edit/bulk-edit-logs.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-15412](https://folio-org.atlassian.net/browse/FAT-15412)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/436916)
> FAT-15412/C436916

- cypress/e2e/data-import/importing-marc-bib-files/update-controlled-and-not-controlled-subfields.cy.js
- cypress/e2e/inventory/advanced-search/search-by-place-of-publication-using-advanced-search.cy.js
- cypress/e2e/inventory/search-in-select-instance-plugin/search-instance-which-has-each-classification-type-using-classification-normalized-option.cy.js
- cypress/support/constants.js
https://folio-org.atlassian.net/browse/FAT-15205
https://foliotest.testrail.io/index.php?/cases/view/466166
> FAT-15205/C466166

- cypress/e2e/eureka/users/get-user-via-bl-users-by-usename.cy.js
- cypress/e2e/eureka/users/promoting-user-to-authUser.cy.js
- cypress/support/api/users.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-15453
Test case - https://foliotest.testrail.io/index.php?/cases/view/451589
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7264/allure
> FAT-15453-C451589

- cypress/e2e/inventory/search-in-select-instance-plugin/no-result-found-when-search-with-classification-normalized-option.cy.js
- cypress/e2e/inventory/search/plug-in-search-instance-by-issn-with-x-at-the-end-in-holdings-tab.cy.js
- cypress/e2e/inventory/search/plug-in-search-instance-by-issn-with-x-at-the-end-in-instance-tab.cy.js
- cypress/e2e/inventory/search/plug-in-search-instance-by-issn-with-x-at-the-end-in-item-tab.cy.js
- cypress/support/fragments/orders/modals/selectInstanceModal.js
https://folio-org.atlassian.net/browse/FAT-15207
https://foliotest.testrail.io/index.php?/cases/view/466163
> FAT-15207/C466163

- cypress/e2e/inventory/instance/set-record-for-deletion-option-in-actions-menu.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/inventory/modals/setRecordForDeletionModal.js
***
https://folio-org.atlassian.net/browse/FAT-15227
***
https://foliotest.testrail.io/index.php?/cases/view/436834
***
***
> FAT-15227-C436834

- cypress/e2e/aaa.cy.js
- cypress/support/api/index.js
- cypress/support/api/specifications.js
https://folio-org.atlassian.net/browse/FAT-15564
> Marc Bib and Marc Auth specifications sync request

- cypress/e2e/inventory/contributors-browse/browse-contributors-linked.cy.js
- cypress/e2e/inventory/contributors-browse/browse-in-inventory.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects-linked.cy.js
- cypress/e2e/marc/marc-authority/delete-two-marc-bib-linked-marc-authority.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/edit-an-authority-record.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked-modals.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-api.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-export-manager.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting.cy.js
- cypress/e2e/marc/marc-authority/retrieve-deleted-authority-api.cy.js
- cypress/e2e/marc/marc-authority/retrieve-deleted-authority-filter-api.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/add-controllable-subfield-to-linked-field.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-headings-enabled-disabled-when-editing-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/protocol-displayed-in-$0-of-auto-linked-field-without-base-url-before-linking.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bibl-record-which-has-$-sign.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField100-to-authority100-with-subfield-0.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField240-to-authority100-with-subfield-t.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/marc-bibliographic-unlink-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/protocol-displayed-in-$0-of-manual-linked-field-with-base-url-with-protocol-before-linking.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/protocol-displayed-in-$0-of-manual-linked-field-with-base-url-without-protocol-before-linking.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/protocol-displayed-in-$0-of-manual-linked-field-without-$0-subfield-before-linking.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/protocol-displayed-in-$0-of-manual-linked-field-without-base-url-before-linking.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bib-edit.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic.cy.js
- cypress/e2e/marc/marc-bibliographic/modify-marc-bib-record-of-deleted-user.cy.js
- cypress/support/fragments/marcAuthority/marcAuthority.js
https://folio-org.atlassian.net/browse/FAT-15564
> Update tests related to UIQM-631 changes

- cypress/e2e/fse/ui/consortia-ui.cy.js
- cypress/e2e/inventory/instance/inventory-enable-staff-suppress-facet-permission-in-inventory-app.cy.js
Switch affiliation test added for the env-verification suite
> FSE AQA suite - switch affiliation test added

- cypress/e2e/inventory/search-in-inventory/search-instances-which-has-different-classification-types-using-classif-normalized-optoin.cy.js
https://folio-org.atlassian.net/browse/FAT-15182
https://foliotest.testrail.io/index.php?/cases/view/466148
> FAT-15182/C466148

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-remove-all.cy.js
- cypress/support/api/inventory.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
[FAT-15451](https://folio-org.atlassian.net/browse/FAT-15451)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/422044)
> FAT-15451/C422044

- cypress/e2e/fee-fine/manual-patron-block-for-requests.cy.js
- cypress/support/fragments/requests/newRequest.js
- cypress/support/fragments/users/usersCard.js
https://folio-org.atlassian.net/browse/FAT-15231
https://foliotest.testrail.io/index.php?/cases/view/481
> new test FAT-15231 C481

- cypress/e2e/settings/data-export/default-field-mapping-profiles.cy.js
- cypress/e2e/settings/data-export/default-job-profile.cy.js
- cypress/e2e/settings/data-export/edit-duplicate-field-mapping-profile.cy.js
- cypress/e2e/settings/data-export/new-field-mapping-profile.cy.js
- cypress/e2e/settings/data-export/new-job-profile.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/data-export/exportJobProfile/exportJobProfiles.js
Add new permissions for settings in data-export, and update the test cases in Quality Gates.
[FAT-15703](https://folio-org.atlassian.net/browse/FAT-15703)
> FAT-15703 Update test cases related Data-export settings

- cypress/e2e/settings/circulation/patron-notices/metadata-info-patron-notice-templates.cy.js
- cypress/support/fragments/settings/circulation/patron-notices/newNoticePolicyTemplate.js
> Add edit steps

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-custom-fields-semicolon.cy.js
- cypress/e2e/circulation-log/loan-date-and-time.cy.js
- cypress/e2e/settings/tenant/settings-remain-for-campus.cy.js
- cypress/e2e/settings/tenant/settings-remain-for-location.cy.js
- cypress/e2e/settings/tenant/tenant-general-html-title.cy.js
Tune the test cases in the weekly run
> FAT-15436 Support automated test case in the weekly run

- cypress/e2e/eureka/authorization-roles/assigning-capabilities-role-user-api.cy.js
- cypress/support/api/permissions.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-15757
- https://folio-org.atlassian.net/browse/FAT-15758
Test cases:
- https://foliotest.testrail.io//index.php?/cases/view/523660
- https://foliotest.testrail.io//index.php?/cases/view/523661
Allure report:
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7310/allure/
> FAT-15757-FAT-15758

- cypress/e2e/eureka/authorization-policies/system-policy-created-for-user.cy.js
- cypress/support/constants.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-15765
Test case - https://foliotest.testrail.io/index.php?/cases/view/514999
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7315/allure
> FAT-15765-C514999

- cypress/e2e/fee-fine/multi-options-lost-item-fee.cy.js
- cypress/support/fragments/settings/circulation/patron-notices/newNoticePolicy.js
> Lost item fees option

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-barcodes-preview.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-with-deleting.cy.js
- cypress/e2e/settings/data-export/edit-duplicate-field-mapping-profile.cy.js
- cypress/e2e/settings/data-export/field-mapping-profile-with-suppression.cy.js
- cypress/e2e/settings/data-export/new-field-mapping-profile.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-tenant.cy.js
Tune the tests in daily run
Temporarily remove the 'shiftLeft' tag due to upcoming changes in functionality.
> FAT-15790 Support automated test case in the daily run

- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-auth-file-with-default-prefix.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/edit-marc-auth-which-has-$-sign.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic.cy.js
- cypress/e2e/orders/unopen-order-with-changed-fund-distribution.cy.js
Reverts folio-org/stripes-testing#4098
> Revert "removed broken tests from Quality gates"

- cypress/e2e/settings/data-export/delete-the-existing-mapping-profile.cy.js
- cypress/e2e/settings/data-export/edit-duplicate-field-mapping-profile.cy.js
- cypress/e2e/settings/data-export/field-mapping-profile-with-suppression.cy.js
- cypress/e2e/settings/data-export/new-field-mapping-profile.cy.js
- cypress/support/fragments/data-export/exportMappingProfile/modalSelectTransformations.js
Update autotests regarding changes in Transformation form in Data export Settings
[FAT-15906](https://folio-org.atlassian.net/browse/FAT-15906)
> FAT-15906 Update autotests regarding changes in Transformation form in Data export Settings

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-users-ids-error.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-in-different-columns-add-notes.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-user-permissions.cy.js
- cypress/e2e/settings/data-export/edit-duplicate-field-mapping-profile.cy.js
- cypress/e2e/settings/data-export/mapping-profiles-transformations-placeholder-attribute.cy.js
- cypress/e2e/settings/data-export/new-field-mapping-profile.cy.js
- cypress/support/fragments/data-export/exportMappingProfile/exportFieldMappingProfiles.js
- cypress/support/fragments/data-export/exportMappingProfile/exportNewFieldMappingProfile.js
- cypress/support/fragments/data-export/exportMappingProfile/modalSelectTransformations.js
- interactors/multi-column-list.js
Update the test case C345342
Stabilize the test case C422220
Add the tag 'shiftLeft'
> FAT-15906 Update autotests regarding changes in Transformation form in Data export Settings 

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-without-keycloak-api.cy.js
- cypress/e2e/eureka/users/assigning-capabilities-for-users-without-keycloak-api.cy.js
- cypress/support/api/permissions.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-15787
- https://folio-org.atlassian.net/browse/FAT-15788
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/451622
- https://foliotest.testrail.io//index.php?/cases/view/451628
Allure report:
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7348/allure
> FAT-15787, FAT-15788: tests added

- cypress/e2e/eureka/consortia/login/entitled-apps-retrieved-on-login.cy.js
- cypress/support/api/tenant.js
- cypress/support/fragments/settings/consortium-manager/consortium-manager.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16042
Test case - https://foliotest.testrail.io/index.php?/cases/view/449377
Test results -
> FAT-16042-C449377 ECS

- cypress/e2e/consortia/inventory/search-in-inventory/title-look-up-plugin-in-requests-app-use-shared-facet-in-member.cy.js
- cypress/e2e/requests/cancel-item-level-request.cy.js
- cypress/e2e/requests/create-recall-item-level-request.cy.js
- cypress/e2e/requests/edit-item-level-request.cy.js
- cypress/e2e/requests/edit-title-level-request.cy.js
- cypress/e2e/requests/find-requester-via-user-barcode.cy.js
- cypress/e2e/requests/new-request-user-without-barcode.cy.js
- cypress/e2e/settings/circulation/cannot-duplicate-cancellation-reason.cy.js
- cypress/e2e/title-level-request/place-title-level-request-from-title-look-up.cy.js
- cypress/e2e/title-level-request/recall-request-for-item-with-status-in-process.cy.js
- cypress/e2e/title-level-request/search-requests-by-instance-ISBN.cy.js
- cypress/e2e/title-level-request/tlr-Item-renewable.cy.js
- cypress/e2e/title-level-request/user-can-create-item-level-request-from-instance-page.cy.js
- cypress/e2e/title-level-request/user-can-see-request-detail-for-title-request-hold-or-recall.cy.js
- cypress/support/api/users.js
- cypress/support/fragments/requests/newRequest.js
- cypress/support/fragments/requests/selectInstanceModal.js
> added a new test on title level request (FAT-15867)

- cypress/e2e/eureka/consortia/login/entitled-apps-retrieved-on-login.cy.js
- cypress/e2e/eureka/tenant/interfaces-retrieved-from-proxy-call-api.cy.js
- cypress/support/api/tenant.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16257
Test case - https://foliotest.testrail.io/index.php?/cases/view/546774
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7385/allure
> FAT-16257-C546774

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-incorrectly-formatted-identifiers.cy.js
[FAT-15799](https://folio-org.atlassian.net/browse/FAT-15799)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/440082)
> FAT-15799/C440082

- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps.cy.js
- cypress/e2e/eureka/tenant/interfaces-retrieved-from-proxy-call-api.cy.js
- cypress/e2e/eureka/tenant/modules-retrieved-from-proxy-call-api.cy.js
- cypress/support/api/tenant.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16434
Test case - https://foliotest.testrail.io/index.php?/cases/view/553008
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7427/allure
> FAT-16434-C553008

- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/e2e/eholdings/package/eholdins-packages-addtitles-to-holdings.cy.js
- cypress/support/fragments/eholdings/eHoldingsPackages.js
[FAT-16491](https://folio-org.atlassian.net/browse/FAT-16491)
***
[C688](https://foliotest.testrail.io/index.php?/tests/view/3751901)
***
> Fixed C688

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-locations-clear.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-updated-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items.cy.js
- cypress/e2e/settings/tenant/service-points-view.cy.js
Fix the test cases in daily run
> FAT-16080 Support automated test case in daily run

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-verify-preview-of-record-matched-valid-instance-identifier.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-16509](https://folio-org.atlassian.net/browse/FAT-16509)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/476785)
> FAT-16509/C476785

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-in-different-columns-add-notes.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-admin-note.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-user-unable-to-edit-instances.cy.js
- cypress/e2e/export-manager/search-filter-verify.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
Update e-2-e automated tests because of implementation UIBULKED-535
[FAT-16374](https://folio-org.atlassian.net/browse/FAT-16374)
> FAT-16374 Update e-2-e automated tests because of implementation UIBULKED-535

- cypress/support/fragments/bulk-edit/query-modal.js
Add the click on the Select field button
> FAT-16466 Support the test cases in the daily/weekly runs

- cypress/e2e/data-import/importing-marc-authority-files/import-marc-authority-records-with-999-ff-field-and-without.cy.js
- cypress/e2e/users/profile-pictures/enable-profile-pictures-functionality-on-env.cy.js
- cypress/support/fragments/users/usersCard.js
***
https://folio-org.atlassian.net/browse/FAT-16516
***
https://foliotest.testrail.io/index.php?/cases/view/514930
***
***
> FAT-16516-C514930

- cypress/e2e/users/profile-pictures/enable-profile-pictures-functionality-on-env.cy.js
- cypress/e2e/users/profile-pictures/no-changes-upon-canceling-an-edit-with-pp-deletion.cy.js
- cypress/support/fragments/users/userEdit.js
- cypress/support/fragments/users/usersCard.js
***
https://folio-org.atlassian.net/browse/FAT-16584
***
https://foliotest.testrail.io/index.php?/cases/view/446009
***
***
> FAT-16584-C446009

- cypress/e2e/users/profile-pictures/pp-displays-on-user-record-for-users-with-users-can-view-pp.cy.js
- cypress/support/fragments/users/usersCard.js
***
https://folio-org.atlassian.net/browse/FAT-16586
***
https://foliotest.testrail.io/index.php?/cases/view/442805
***
***
> FAT-16586-C442805

- cypress/support/fragments/data_import/dataImport.js
[FAT-16629](https://folio-org.atlassian.net/browse/FAT-16629)
> add handling of empty parent job id

- cypress/e2e/inventory/settings/instance-date-types/update-instance-date-type-name.cy.js
- cypress/support/api/inventory.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16626
Test case - https://foliotest.testrail.io/index.php?/cases/view/506694
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7471/allure
> FAT-16626-C506694

- cypress/e2e/data-import/importing-marc-holdings-files/source-value-of-imported-marc-holdings-record.cy.js
- cypress/e2e/inventory/search/browse-contributors.cy.js
- cypress/support/constants.js
Update the test cases regarding Test rail.
Remove call numbers options because of updates in the story [UIIN-3015](https://folio-org.atlassian.net/browse/UIIN-3015)
> FAT-16628 Support Q CSP#4 (spitfire)

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-add-note.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-enum.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-in-not-in-operators.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-items-edit-render-preview.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-items-view-render-preview.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-date-time-string.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-string-stores-uuid-boolean.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-string-stores-uuid-but-million.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-users-edit-render-preview.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-zero-holdings.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-zero-instances.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-zero-items.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-zero-users.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/bulk-edit/query-modal.js
Remove the clickSelectFieldButton from the method and add to the tests if necessary,
Fix the test case C350943
> FAT-16466 Support the test cases in daily run

- cypress/e2e/inventory/call-number-browse/browse-call-number-with-space.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
[FAT-16659](https://folio-org.atlassian.net/browse/FAT-16659)
***
> Updated C347918

- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic-edit.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bilbliografic-link-icon.cy.js
[FAT-16673](https://folio-org.atlassian.net/browse/FAT-16673)
***
[C360541](https://foliotest.testrail.io/index.php?/cases/view/360541)
***
> splited marc edit into two files. removed dependenceies between tests

- cypress.config.js
- package.json
Reverts folio-org/stripes-testing#4243
> Revert "hot fix with dependencies"

- cypress/e2e/marc/marc-holdings/holdings-records-Instancesource-folio.cy.js
> fix C345406

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holding-more-than-10-note-types-are-displayed.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
[FAT-16740](https://folio-org.atlassian.net/browse/FAT-16740)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/440089)
> FAT-16740/C440089

- cypress/e2e/consortia/inventory/search-in-inventory/sort-changed-on-central.cy.js
- cypress/support/api/auth.js
- cypress/support/api/inventory.js
- cypress/support/constants.js
- cypress/support/dictionary/permissions.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16754
Test case - https://foliotest.testrail.io/index.php?/cases/view/543872
Test results -
> FAT-16754-C543872

- cypress/e2e/consortia/consortium-manager/user-is-not-able-to-edit-and-delete-from-member-tenant-patron-group-and-departments.cy.js
- cypress/e2e/reading-room-access/user-can-view-reading-room-access.cy.js
- cypress/e2e/settings/users/edit-patron-group.cy.js
- cypress/e2e/settings/users/patron-group-can-be-deleted-only-if-it-has-no-users-assigned.cy.js
- cypress/e2e/settings/users/view-patron-groups.cy.js
- cypress/support/fragments/settings/users/patronGroups.js
- cypress/support/fragments/settings/users/settingsUsers.js
***
https://folio-org.atlassian.net/browse/FAT-16614
***
https://foliotest.testrail.io/index.php?/cases/view/514946
***
***
> FAT-16614-C514946

- cypress/e2e/bulk-edit/in-app/bulk-adit-in-app-separating-notes-in-different-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-non-existent-relationship.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-user.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-add-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-staff-suppress-true.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes-error.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-custom-fields-recent.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-csv-in-app-export-manager-permissions.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-in-app-export-manager-permissions.cy.js
- cypress/e2e/circulation-log/search.cy.js
- cypress/e2e/remote-storag/item-locations.cy.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/urlRelationship.js
- cypress/support/fragments/settings/users/customFields.js
> FAT-16466 Support the tests in daily run

- cypress/e2e/lists/create-list/lists-view-permissions.cy.js
- cypress/e2e/lists/permissions/lists-all-permissions.cy.js
- cypress/e2e/lists/permissions/lists-refresh-permissions.cy.js
- cypress/e2e/lists/permissions/lists-view-permissions.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/lists/lists.js
https://foliotest.testrail.io/index.php?/cases/view/418651
https://foliotest.testrail.io/index.php?/cases/view/411821
> Fat 16533 fat 16534

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-items-verify-options.cy.js
[FAT-16784](https://folio-org.atlassian.net/browse/FAT-16784)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/553004)
> FAT-16784/C553004

- cypress/e2e/lists/permissions/lists-edit-permissions.cy.js
- cypress/e2e/lists/permissions/lists-refresh-permissions.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/lists/lists.js
https://foliotest.testrail.io/index.php?/cases/view/418650
> implemented a new test on Lists permissions FAT-16536

- cypress/e2e/data-import/importing-marc-authority-files/import-marcAuth-without-010-job-profile-matching-010-update-and-create-action.cy.js
- cypress/e2e/marc/marc-authority/modify-marc-auth-record-of-deleted-user.cy.js
- cypress/e2e/marc/marc-bibliographic/modify-marc-bib-record-edited-by-deleted-user.cy.js
- cypress/e2e/marc/marc-bibliographic/modify-marc-bib-record-of-deleted-user.cy.js
- cypress/e2e/marc/marc-holdings/modify-marc-holdings-of-deleted-user.cy.js
[FAT-16814](https://folio-org.atlassian.net/browse/FAT-16814)
***
> Fixes for broken tests

- cypress/e2e/lists/Export-list/export-all-columns.cy.js
- cypress/e2e/lists/Export-list/export-visible-columns.cy.js
- cypress/e2e/lists/permissions/lists-all-permissions.cy.js
- cypress/e2e/lists/permissions/lists-edit-permissions.cy.js
- cypress/e2e/lists/permissions/lists-refresh-permissions.cy.js
- cypress/e2e/lists/permissions/lists-view-permissions.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/lists/lists.js
https://foliotest.testrail.io/index.php?/cases/view/552377
https://foliotest.testrail.io/index.php?/cases/view/552378
> Fat 16531 fat 16532

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-ids-uploading.cy.js
- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-created-updated-dates.cy.js
- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-records-confirmation-page.cy.js
- cypress/e2e/bulk-edit/csv/bulk-edit-csv-usernames.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-adit-in-app-holdings-separating-notes-in-different-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-permanent-location.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-identifiers-different.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-add-and-remove-mark-as-staff-only.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-location-contains-char.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-location-filter.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-navigation.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-several-holdings.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes-error.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users-changed-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users-updated-columns.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-users-uuids.cy.js
- cypress/e2e/bulk-edit/logs/in-app/verify-that-actions-menu-is-hidden-on-the-logs-tab-with-in-app-permissions.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-date-time-string.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-logs.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
Support the test cases in daily/weekly runs
> FAT-16781 Support the test cases in daily/weekly runs

- cypress/e2e/eureka/authorization-roles/cannot-duplicate-role-insufficient-capabilities.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16775
Test case - https://foliotest.testrail.io/index.php?/cases/view/554635
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7510/allure
> FAT-16775-C554635

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-without-keycloak.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-only-sets.cy.js
- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/e2e/eureka/users/assigned-roles-in-user-view.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16853
Test case - https://foliotest.testrail.io/index.php?/cases/view/499896
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7534/allure
> FAT-16853-C499896

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-verify-instance-data-in-forms-and-files.cy.js
- cypress/support/fragments/settings/inventory/instances/formats.js
[FAT-16779](https://folio-org.atlassian.net/browse/FAT-16779)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/423676)
> FAT-16779/C423676

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-without-username.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16878
Test case - https://foliotest.testrail.io/index.php?/cases/view/584420
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7541/allure
> FAT-16878: test added

- cypress/e2e/eureka/login/app-details-shown-in-settings.cy.js
- cypress/support/fragments/settings/softwareVersions/software-versions.js
- interactors/messagebanner.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16893
Test case - https://foliotest.testrail.io/index.php?/cases/view/431150
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7552/allure
> FAT-16893: test added

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-identifiers-different.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-add-and-remove-mark-as-staff-only.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-verify-changed-properties-columns.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/inventory/inventoryInstances.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
[FAT-16913](https://folio-org.atlassian.net/browse/FAT-16913)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/431145)
> FAT-16913/C431145

- cypress/support/fragments/eholdings/eHoldingsPackages.js
[FAT-17022](https://folio-org.atlassian.net/browse/FAT-17022)
***
> refactored package validation methods

- cypress/e2e/lists/Export-list/export-list.cy.js
- cypress/e2e/lists/create-list/add-new-list.cy.js
- cypress/e2e/lists/create-list/cancel-list-creation.cy.js
- cypress/e2e/lists/create-list/create-new-list.cy.js
- cypress/e2e/lists/create-list/private-list.cy.js
- cypress/e2e/lists/delete-list/canned-lists.cy.js
- cypress/e2e/lists/delete-list/inprogress-refresh-export.cy.js
- cypress/e2e/lists/delete-list/not-canned-Lists.cy.js
- cypress/e2e/lists/edit-list/edit-list-not-canned-records.cy.js
- cypress/e2e/lists/edit-list/editlist-canned.cy.js
- cypress/e2e/lists/edit-list/editlists-not-canned.cy.js
- cypress/e2e/lists/edit-list/make-list-private-shared.cy.js
- cypress/support/fragments/lists/lists.js
https://foliotest.testrail.io/index.php?/cases/view/411732
> new test on editing not canned list FAT-16535

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-button-disabled.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-alternative-title-when-creating-new-marcBib.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-contributor-when-creating-new-marcBib.cy.js
- cypress/support/fragments/data_import/dataImport.js
This reverts commit 7033a5dbff489c67ec2cb12548260acddb9964a1.
> Revert "added force requests repeating during file import (#4343)"

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-ids-uploading.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-note-types-in-bulk-edit-form.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-forms.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users-pagination-no-more-than-100-records.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users-search-column-name.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
[FAT-17019](https://foliotest.testrail.io/index.php?/cases/view/468187)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/468187)
> FAT-17019/C468187

- cypress/e2e/bulk-edit/permissions/bulk-edit-csv-export-manager-permissions.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-landing.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-date-time-string.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-users-edit-render-preview.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/query-modal.js
Update/stabilize the test cases
> FAT-17040 Support the test cases in daily/weekly run

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-suppress-from-discovery-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-16512](https://folio-org.atlassian.net/browse/FAT-16512)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496118)
> FAT-16512/C496118

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-created-updated-dates.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-change-note-type.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-change-note-type-within.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-for-added-notes.cy.js
> FAT-17040 Support the test cases in daily/weekly run 

- cypress/e2e/inventory/classification-browse/browse-classification-has-same-value-different-classification-types-using-dewey-decimal-classification-option.cy.js
- cypress/e2e/inventory/search-in-inventory/browse-and-search-capabilities-are-separated.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-export-manager.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/add-non-controllable-subfield-to-linked-field-when-creating-marcBib.cy.js
https://folio-org.atlassian.net/browse/FAT-17034
https://foliotest.testrail.io/index.php?/cases/view/468159
> FAT-17034/C468159

- cypress/e2e/inventory/classification-browse/browse-classification-has-same-value-different-classification-types-using-lib-of-congress-classification-option.cy.js
https://folio-org.atlassian.net/browse/FAT-17035
https://foliotest.testrail.io/index.php?/cases/view/468160
> FAT-17035/C468160

- cypress/e2e/eureka/users/assigning-roles-user-edit-with-without-keycloak.cy.js
- cypress/support/fragments/users/userEdit.js
- cypress/support/fragments/users/usersCard.js
- cypress/support/fragments/users/usersSearchPane.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17147
Test case - https://foliotest.testrail.io/index.php?/cases/view/584520
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7620/allure
> FAT-17147-C584520

- cypress/e2e/inventory/call-number-browse/browse-call-number-with-space.cy.js
- cypress/e2e/inventory/subject-browse/subject-browse.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-marcBib-with-created-on-ui-marcAuth.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/all-linkable-fields-not-linked-except-already-linked-ones.cy.js
https://folio-org.atlassian.net/browse/FAT-17244
> Update testcases regarding functional changes in MODQM-447

- cypress/support/fragments/data_import/dataImport.js
Added attempts to operations related to file upload
> fileUpload stabilization

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-change-note-type.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-users-uuids.cy.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/inventory/item/itemRecordView.js
- interactors/option.js
[FAT-17103](https://folio-org.atlassian.net/browse/FAT-17103)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/411509)
> FAT-17103/C411509

- cypress/e2e/eureka/consortia/login/logout-switching-affiliation.cy.js
- cypress/e2e/eureka/users/authn-update-user-with-without-keycloak-api.cy.js
- cypress/support/api/auth.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-17240
- https://folio-org.atlassian.net/browse/FAT-17238
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/423958
- https://foliotest.testrail.io/index.php?/cases/view/594518
Allure reports:
- https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7652/allure
- https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7653/allure
> FAT-17240-FAT-17238

- interactors/multi-column-list.js
Reverts folio-org/stripes-testing#4427
> Revert "removed selector to avoid multiple interactors detection"

- cypress/e2e/marc/marc-authority/browse-authority-records/marc-authority-import_6.cy.js
- cypress/support/fragments/settings/inventory/instances/classificationBrowse.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
> MultiColumnListRow detection updates

- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
> fix for C436844

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-cancel.cy.js
Replace the top menu navigation method
>  FAT-17272 Support the test cases in daily/weekly runs

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-staff-suppress-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/bulk-edit/query-modal.js
[FAT-16510](https://folio-org.atlassian.net/browse/FAT-16510)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/477642)
> FAT-16510/C477642

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-users-preview.cy.js
- cypress/e2e/bulk-edit/logs/bulk-edit-logs-search-and-filters-pane.cy.js
- cypress/e2e/bulk-edit/logs/bulk-edit-logs-verify-reset-all.cy.js
- cypress/support/fragments/settings/tenant/location-setup/campuses.js
- cypress/support/fragments/settings/tenant/location-setup/institutions.js
Move the test case to separate file;
Adjust the selectors;
> FAT-17272 Support the test cases in daily/weekly runs

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-suppress-from-discovery-in-central-tenant.cy.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/query-modal.js
[FAT-16511](https://folio-org.atlassian.net/browse/FAT-16511)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496127)
> FAT-16511/C496127

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-barcodes.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-date-time-string.cy.js
Update/stabilize the test cases
> FAT-17442 Update/stabilize the test cases

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-fields-actions.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-in-different-columns-add-notes.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-only-updated-properties-columns-in-are-you-sure-form.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-add-admin-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-verify-changed-properties-columns.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
Replace the verifyPossibleActionsForSpecificSelect() with the stable one;
Remove unused method verifyPossibleActionsForSpecificSelect();
Stabilize the test cases;
> FAT-17442 Support the test cases in daily/weekly runs 

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-deleted-user.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-fields-actions.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-incorrectly-formatted-identifiers.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-columns-titles.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
> FAT-17442 Stabilize the test cases

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-deleted-user.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-fields-actions.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-incorrectly-formatted-identifiers.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-columns-titles.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
> FAT 17442 Stabilize the test cases

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-deleted-user.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-incorrectly-formatted-identifiers.cy.js
Stabilize the test case C440082
> FAT-17442 Support the test cases in daily/weekly runs

- cypress/e2e/circulation-log/filter-circulation-log-by-renewed.cy.js
- cypress/e2e/circulation-log/filter-claimed-returned.cy.js
- cypress/e2e/circulation-log/filter-closed-loan.cy.js
- cypress/e2e/circulation-log/filter-declared-lost.cy.js
- cypress/e2e/circulation-log/filter-marked-as-missing.cy.js
- cypress/e2e/circulation-log/filter-notice-send.cy.js
- cypress/e2e/circulation-log/filter-renewed-through-override.cy.js
- cypress/e2e/circulation-log/filter-staff-information-only-added.cy.js
- cypress/e2e/circulation-log/loan-date-and-time.cy.js
- cypress/e2e/circulation-log/search.cy.js
- cypress/e2e/remote-storag/item-locations.cy.js
- cypress/e2e/remote-storag/moving-items-non-remote.cy.js
- cypress/e2e/remote-storag/moving-items-remote.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-accession-tables-final-location.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-accession-tables.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-callout.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-configurations.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-delete.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-provider-name.cy.js
- cypress/e2e/settings/remote-storage/remote-storage-tenant.cy.js
- cypress/e2e/settings/remote-storage/remote-storage.cy.js
Change the tag to 'volaris' according to the test rail
> FAT-17442 Change the tag to 'volaris' according to the test rail

- cypress/e2e/consortia/settings/marc-authority/view-authority-files-central-member.cy.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
> updated cases C430207, C430209

- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-users-uuids.cy.js
Update the test case C375245 because the story  MODBULKOPS-412
> FAT-17554 Support the test cases in daily/weekly runs

- cypress/e2e/consortia/data-import/importing-marcAuthority-files/imported-marcAuthority-record-from-member-not-discoverable-in-central.cy.js
- cypress/e2e/consortia/data-import/importing-marcAuthority-files/imported-marcAuthority-record-from-member1-not-discoverable-in-member2.cy.js
- cypress/e2e/consortia/data-import/importing-marcAuthority-files/updated-imported-marcAuth-record-from-central-updated-in-member.cy.js
- cypress/e2e/consortia/data-import/importing-marcBib-files/update-$0-in-linked-fileds-of-shared-marcBib-in-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-shared-central.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-shared-local-member.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/search-shared-local-records-by-contributor-from-member.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/search-shared-local-records-by-title-all-from-central.cy.js
- cypress/e2e/consortia/marc/marc-authority/marc-authority-local-edit-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/marc-authority-shared-edit-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-local-linked-marc-auth-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-shared-linked-marc-auth-record-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/derive-marcBib/derive-new-local-marcBib-from-shadow-instance-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-local-marcBib-with-local-marcAuth-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-local-marcBib-with-shared-marcAuth-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-shared-marcBib-with-shared-marcAuth-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-shared-marcBib-with-shared-marcAuth-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/marc-bib-edit-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/user-can-edit-local-marc-bib-in-member.cy.js
- cypress/support/fragments/settings/consortium-manager/consortium-manager.js
> FAT-17554 Fix, adjust Spitfire ecs test cases

- cypress/e2e/eureka/consortia/users/unassigned-roles-user-view-central-member.cy.js
- cypress/support/fragments/users/usersCard.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17597
Test case - https://foliotest.testrail.io/index.php?/cases/view/514899
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7781/allure
> FAT-17597-C514899-ECS

- cypress/e2e/eureka/consortia/users/assigned-roles-user-view-central-member.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17598
Test case - https://foliotest.testrail.io/index.php?/cases/view/514892
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7790/allure
> FAT-17598-C514892

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-staff-suppress-in-central-tenant.cy.js
- cypress/e2e/consortia/data-import/importing-marcAuthority-files/imported-marcAuthority-record-from-member-not-discoverable-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-shared-marcBib-with-shared-marcAuth-in-central.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/add-$9-to-linkable-fields.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-linked-field-which-controlled-by-marc-authority.cy.js
- cypress/e2e/data-import/importing-marc-bib-files/delete-uncontrolled-subfield-of-linked-marcBib.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-linked.cy.js
- cypress/e2e/marc/marc-authority/marc-authority-print-option.cy.js
- cypress/e2e/marc/marc-authority/reporting-marc-authority/marc-authority-reporting-api.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/all-linkable-fields-linked-after-click-link-headings.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bib-add-multiple-001s.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/user-can't-link-bibField100-with-wrong-record.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-browse/include-exclude-reference-in-marc-auth-plugin-browse.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/collapse-pane-when-searching.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/include-exclude-reference-in-marc-authority-plugin-results-list.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/search-using-advanced-search-option.cy.js
- cypress/e2e/marc/plug-in-marc-authority/switching-between-browse-and-search-views-when-linking.cy.js
- cypress/e2e/settings/notes/view-note-type.cy.js
- cypress/support/fragments/marcAuthority/marcAuthorities.js
- cypress/support/fragments/quickMarcEditor.js
- cypress/support/fragments/settings/notes/noteTypes.js
> FAT-17554 Support automated tests

- cypress/e2e/eureka/authorization-roles/roles-view-capability-set.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17637
Test case - https://foliotest.testrail.io/index.php?/cases/view/605890
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7793/allure/
> FAT-17637-C605890

- cypress/e2e/fse/ui/settings-ui.cy.js
Tag added as per discussion with Vasyl Avramenko. We need to temporarily exclude that test from eureka sanity check.
> Tag added for software version test

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-fields-with-0-subfield.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/manual-and-auto-linking-when-creating-new-marcBib.cy.js
- cypress/e2e/settings/tenant/create-custom-package-with-not-english-session-locale.cy.js
- cypress/support/fragments/marcAuthority/marcAuthorities.js
> updates for extended path tests

- cypress/e2e/consortia/data-import/importing-marcBib-files/update-$0-in-linked-fileds-of-shared-marcBib-in-central.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/title-look-up-plugin-in-requests-app-use-shared-facet-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-shared-linked-marc-auth-record-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/derive-marcBib/derive-new-local-marcBib-from-shadow-instance-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/edit-subfields-shared-marc-bib-in-member.cy.js
- cypress/support/fragments/requests/selectInstanceModal.js
> FAT-17554 Support automated test cases

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-barcodes-preview.cy.js
- cypress/e2e/bulk-edit/csv/bulk-edit-csv-users-ids-error.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-uuids.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-users-barcodes.cy.js
- cypress/support/login.js
> FAT-17554 Support of automated tests

- cypress/e2e/inventory/instance/create-instance-date-fields-digits.cy.js
- cypress/support/constants.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
- cypress/support/fragments/inventory/instanceRecordView.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17691
Test case - https://foliotest.testrail.io/index.php?/cases/view/552504
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7825/allure/
> FAT-17691-C552504

- cypress/e2e/inventory/instance/create-instance-date-fields-digits.cy.js
- cypress/e2e/inventory/instance/create-instance-date-fields-length-validation.cy.js
- cypress/e2e/inventory/instance/create-instance-no-date2.cy.js
- cypress/e2e/inventory/instance/edit-instance-date-fields-digits.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/inventory/inventoryNewInstance.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-17692
- https://folio-org.atlassian.net/browse/FAT-17693
- https://folio-org.atlassian.net/browse/FAT-17696
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/552514
- https://foliotest.testrail.io/index.php?/cases/view/552527
- https://foliotest.testrail.io/index.php?/cases/view/552518
Allure report:
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7838/allure
> FAT-17692-FAT-17693-FAT-17696

- cypress/e2e/inventory/instance/edit-instance-date-fields-length-validation.cy.js
- cypress/e2e/inventory/instance/edit-instance-no-date2.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-17697
- https://folio-org.atlassian.net/browse/FAT-17698
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/552528
- https://foliotest.testrail.io/index.php?/cases/view/552531
Allure report:
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7839/allure
> FAT-17697-FAT-17698

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-replace-with-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-add-note-in-central.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/consortium-manager/inventory/instances-holdings-items/urlRelationshipConsortiumManager.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/urlRelationship.js
[FAT-16785](https://folio-org.atlassian.net/browse/FAT-16785)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494359)
> FAT-16785/C494359

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-staff-only-notes-in-central-tenant.cy.js
[FAT-17736](https://folio-org.atlassian.net/browse/FAT-17736)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494091)
> FAT-17736/C494091

- cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-barcodes.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-enum.cy.js
- cypress/e2e/settings/tenant/service-points.cy.js
- cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js
> FAT-17417 Support automated test cases

- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/marc-bib-edit-in-central.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
Adjust the test case C405520 according to the Test rail
> FAT-17417 Support automated tests

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-clear-field.cy.js
- cypress/support/fragments/inventory/holdingsRecordView.js
[FAT-17763](https://folio-org.atlassian.net/browse/FAT-17763)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494101)
> FAT-17763/C494101

- cypress/e2e/bulk-edit/permissions/bulk-edit-with-logs-permissions.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-logs.js
Stabilize the test case C368013
> FAT-17417 Support the automated tests

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-notes-in-central.cy.js
- cypress/support/fragments/inventory/item/itemRecordView.js
[FAT-17761](https://folio-org.atlassian.net/browse/FAT-17761)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494095)
> FAT-17761/C494095

- cypress/e2e/linked-data/check-view-and-search.cy.js
- cypress/e2e/linked-data/create-work.cy.js
- cypress/e2e/linked-data/duplicate-instance.cy.js
- cypress/e2e/linked-data/duplicate-work.cy.js
- cypress/e2e/linked-data/edit-resource-marc-record.cy.js
- cypress/e2e/linked-data/search.cy.js
- cypress/support/fragments/linked-data/linkedDataEditor.js
Citations tests updated and 'shiftLeft' tag added.
> Citation shift left

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-duplicate-notes-in-central-tenant.cy.js
[FAT-17762](https://folio-org.atlassian.net/browse/FAT-17762)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494096)
> FAT-17762/C494096

- cypress/e2e/inventory/classification-browse/browse-classification-using-classification-all-option-is-case-insensitive.cy.js
- cypress/e2e/inventory/classification-browse/browse-classification-using-dewey-decimal-classification-option-is-case-insensitive.cy.js
- cypress/e2e/inventory/classification-browse/browse-classification-using-lib-of-congress-classification-option-is-case-insensitive.cy.js
- cypress/e2e/inventory/classification-browse/browse-classification-which-has-each-classification-type-using-classification-all-option.cy.js
https://folio-org.atlassian.net/browse/FAT-17319
> Update tests with classification identifier types

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-clear-field.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-replace-with-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-staff-only-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-add-note-in-central.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-duplicate-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-notes-in-central.cy.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/query-modal.js
- cypress/support/fragments/consortium-manager/inventory/instances-holdings-items/urlRelationshipConsortiumManager.js
- cypress/support/fragments/inventory/holdingsRecordView.js
- cypress/support/fragments/inventory/item/itemRecordView.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/urlRelationship.js
Add the test cases automated in the Sunflower release (master branch) to the Ramsons release branch in order to decrease manual effort during the [Eureka] Bugfest: Ramsons R2 Revalidation Phase.
> FAT-17417 Add the test cases from master branch

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-loan-type-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-17837](https://folio-org.atlassian.net/browse/FAT-17837)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496151)
> FAT-17837/C496151

- cypress/e2e/consortia/settings/marc-authority/view-authority-files-central-member.cy.js
- cypress/support/api/inventory.js
- cypress/support/fragments/settings/marc-authority/manageAuthorityFiles.js
Fixes from Bugfest applicable in master
> Spitfire minor fixes

- cypress/e2e/eureka/authorization-roles/assigning-users/assigned-users-in-role-view-with-manage.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigned-users-in-role-view-with-view.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-unassigning-users-in-role-view.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-user-created-in-ui.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-user-name-changed.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-in-role-view.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-with-or-without-keycloak.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-without-keycloak.cy.js
- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-without-username.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17731
Test case - https://foliotest.testrail.io/index.php?/cases/view/627247
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7924/allure
- - -
Also, updated test names according to FAT-17730
> FAT-17731-C627247

- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-heldby-facet-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-heldby-shared-facets-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-same-call-number-shared-facet.cy.js
- cypress/e2e/consortia/inventory/search-in-inventory/search-shared-local-instances-by-title-all-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/browse/apply-shared-facet-to-browse-result-list-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/search/apply-shared-facet-when-search-executed-in-member.cy.js
- cypress/e2e/consortia/marc/marc-authority/update-shared-linked-marc-auth-record-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/derive-marcBib/derive-from-local-marc-bib-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/derive-marcBib/derive-from-shared-marc-bib-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/automated-linking/auto-linking-shared-marcBib-with-shared-marcAuth-on-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/manual-linking/link-shared-marcBib-with-shared-marcAuth-in-central.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/edit-marc-bib/user-can-edit-shared-marc-bib-in-member.cy.js
> Eureka critical tests updates pt.1

- cypress/e2e/inventory/contributors-browse/browse-contributors-exact.cy.js
- cypress/support/fragments/inventory/search/browseContributors.js
> Stabilize C353639 for smoke tests

- cypress/e2e/eureka/login/logout-default-params.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18002
Test case - https://foliotest.testrail.io/index.php?/cases/view/630447
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7927/allure
> FAT-18002-C630447

- cypress/e2e/inventory/search-in-inventory/facet-search-after-contributors-sort.cy.js
- cypress/e2e/inventory/search-in-inventory/facet-search-after-relevance-sort.cy.js
- cypress/e2e/inventory/search-in-inventory/facet-search-after-title-sort.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-folio-authority-file.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-auth-file-with-default-prefix.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-authority-file.cy.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
Fixes from Eureka Snapshot applicable in master
> spitfire fixes 1-9

- cypress/e2e/eureka/authorization-roles/create-role-add-app.cy.js
- cypress/e2e/eureka/authorization-roles/duplicate-role.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-add-app.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-unassign-button-select-apps.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-unassign-button.cy.js
- cypress/e2e/eureka/authorization-roles/role-with-only-sets-api.cy.js
- cypress/e2e/eureka/authorization-roles/selecting-capabilities-and-sets-edit.cy.js
- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
Fixes for Eureka tests in R Bugfest
> Eureka bf fixes

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-replace-item-notes-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-17838](https://folio-org.atlassian.net/browse/FAT-17838)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/605955)
> FAT-17838/C605955

- cypress/e2e/eureka/authorization-roles/selecting-capabilities-columns-create.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18023
Test case - https://foliotest.testrail.io//index.php?/cases/view/624253
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7947/allure
> FAT-18023: test added

- cypress/e2e/inventory/contributors-browse/browse-contributors-non-exact.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/marc-bibliographic.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
> Updates for failed quality gate tests

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-notes-remove-all-add-same-type.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-for-added-notes.cy.js
- cypress/support/constants.js
> FAT-17417 Stabilize test cases

- cypress/e2e/eureka/authorization-roles/selecting-capabilities-columns-create.cy.js
- cypress/e2e/eureka/authorization-roles/selecting-capabilities-columns-edit.cy.js
- cypress/e2e/eureka/login/access-token-not-shown-on-login.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18024
Test case - https://foliotest.testrail.io//index.php?/cases/view/624254
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7948/allure
> FAT-18024-C624254

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-find-replace-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-find-replace-notes-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-replace-item-notes-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/inventory/holdingsRecordView.js
[FAT-17839](https://folio-org.atlassian.net/browse/FAT-17839)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/478258)
> FAT-17839/C478258

- cypress/e2e/data-import/importing-marc-authority-files/update-created-from-ui-marc-authority-record.cy.js
https://foliotest.testrail.io/index.php?/cases/view/423563
---
https://folio-org.atlassian.net/browse/FAT-18052
---
> Implementation of C423563 Export of created MARC authority record

- cypress/e2e/inventory/single-record-import/import-by-loc.cy.js
- cypress/support/api/inventory.js
- cypress/support/fragments/inventory/inventoryActions.js
- cypress/support/fragments/inventory/inventoryInstance.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18034
Test case - https://foliotest.testrail.io/index.php?/cases/view/490900
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7956/allure
> FAT-18034-C490900

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-created-updated-dates.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-add-note-action-in-member-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/bulk-edit/query-modal.js
[FAT-18026](https://folio-org.atlassian.net/browse/FAT-18026)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566125)
> FAT-18026/C566125

- cypress/e2e/consortia/inventory/settings/update-date-type-from-member-api.cy.js
- cypress/e2e/inventory/settings/get-date-types-api.cy.js
- cypress/support/api/inventory.js
FAT tickets: 
- https://folio-org.atlassian.net/browse/FAT-18036
- https://folio-org.atlassian.net/browse/FAT-18071
Test cases: 
- https://foliotest.testrail.io/index.php?/cases/view/506693
- https://foliotest.testrail.io/index.php?/cases/view/506702
Allure report: https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7961/allure
> FAT-18036, FAT-18071: tests added

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-suppress-from-discovery-in-member-tenant.cy.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/inventory/item/itemRecordView.js
[FAT-18027](https://folio-org.atlassian.net/browse/FAT-18027)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566119)
> FAT-18027/C566119

- cypress/e2e/inventory/settings/change-default-sort.cy.js
- cypress/e2e/inventory/settings/instance-date-types/get-date-types-api.cy.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/displaySettings.js
- cypress/support/fragments/settings/inventory/settingsInventory.js
FAT ticket: https://folio-org.atlassian.net/browse/FAT-18073
Test case: https://foliotest.testrail.io/index.php?/cases/view/543867
Allure report: https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7969/allure
> FAT-18073: test added

- cypress/e2e/eureka/users/cannot-assign-roles-with-view-capability.cy.js
- cypress/support/fragments/users/userEdit.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18020
Test case - https://foliotest.testrail.io/index.php?/cases/view/627241
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7981/allure
> FAT-18020-C627241

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-clear-location-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/query-modal.js
[FAT-18076](https://folio-org.atlassian.net/browse/FAT-18076)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496114)
> FAT-18076/C496114

- cypress/e2e/eholdings/tags-from-other-application-not-shown-in-search-filter.cy.js
- cypress/e2e/inventory/contributors-browse/browse-contributors-back.cy.js
- cypress/e2e/inventory/contributors-browse/browse-contributors.cy.js
- cypress/e2e/inventory/contributors-browse/browse-deleted-contributors.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects-diacritics.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-folio-authority-file.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-auth-file-with-default-prefix.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-authority-file.cy.js
- cypress/e2e/settings/tenant/create-custom-package-with-not-english-session-locale.cy.js
- cypress/support/api/eholdings.js
- cypress/support/fragments/eholdings/eHoldingsPackages.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/inventory/search/browseContributors.js
- cypress/support/fragments/inventory/search/browseSubjects.js
Spitfire fixes in master from R BF
> spitfire-fixes-master-1-29

- cypress/e2e/inventory/contributors-browse/browse-contributors-diacritics.cy.js
- cypress/support/fragments/inventory/search/browseContributors.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18183
Test case - https://foliotest.testrail.io/index.php?/cases/view/466294
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8007/allure
> FAT-18183-C466294

- cypress/e2e/inventory/search-in-inventory/facet-search-after-date-sort.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18184
Test case - https://foliotest.testrail.io/index.php?/cases/view/553010
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8021/allure
> FAT-18184-C553010

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-created-updated-dates.cy.js
- cypress/e2e/bulk-edit/csv/bulk-edit-csv-users-ids-error.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-change-note-type.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-identifiers-different.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-change-note-type-within.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-intellectual-item.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-for-added-notes.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-holdings.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-items-hrids.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-suppressed-items.cy.js
- cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-users-uuids.cy.js
- cypress/e2e/marc/marc-authority/edit-linked-authority-record/marc-authority-edit-1XX-field-value-without-010-field.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-files.js
- cypress/support/fragments/bulk-edit/bulk-edit-logs.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
> FAT-18203 Support automated test cases

- cypress/e2e/inventory/classification-browse/browse-classification-deleted-number.cy.js
- cypress/e2e/inventory/classification-browse/browse-classification-deleted-value.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/inventory/search/browseClassifications.js
- interactors/repeatablefield.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18182
Test case - https://foliotest.testrail.io/index.php?/cases/view/471477
Result -
> FAT-18182: test added

- cypress/support/fragments/data-export/exportJobProfile/exportJobProfiles.js
- cypress/support/fragments/data-export/exportMappingProfile/exportFieldMappingProfiles.js
- cypress/support/fragments/data-export/exportMappingProfile/singleFieldMappingProfilePane.js
Adjust the logic of page scrolling to stabilize test suite
> FAT-18203 Support automated tests

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-locations-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-files.js
[FAT-18078](https://folio-org.atlassian.net/browse/FAT-18078)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496117)
> FAT-18078/C496117

- cypress/e2e/eureka/consortia/consortium-manager/view-roles-from-different-tenants.cy.js
- cypress/support/api/permissions.js
- cypress/support/constants.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18421
Test case - https://foliotest.testrail.io/index.php?/cases/view/422010
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8043/allure
> FAT-18421: test added

- cypress/e2e/eureka/consortia/consortium-manager/filter-roles-from-different-tenants.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18424
Test case - https://foliotest.testrail.io/index.php?/cases/view/503005
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8057/allure
> FAT-18424-C503005

- cypress/e2e/consortia/data-export/simplified-export-of-deleted-authority-record-with-deleted-profile-in-central-tenant.cy.js
- cypress/e2e/data-export/holdings-records-export/instance-hrid-004-field.cy.js
- cypress/support/api/data-export.js
- cypress/support/fragments/data-export/dataExportResults.js
- cypress/support/utils/parseMrcFileContent.js
- package.json
[FAT-18450](https://folio-org.atlassian.net/browse/FAT-18450)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566114)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8056/allure/#)
> FAT-18450/C566114

- cypress/e2e/eureka/consortia/consortium-manager/filter-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/filter-roles-from-different-tenants.cy.js
- cypress/support/constants.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18426
Test case - https://foliotest.testrail.io/index.php?/cases/view/514962
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8058/allure
> FAT-18426: test added

- cypress/e2e/eureka/consortia/consortium-manager/filter-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/filter-roles-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-roles-from-different-tenants.cy.js
- cypress/support/api/auth-policies.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18427
Test case - https://foliotest.testrail.io/index.php?/cases/view/514964
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8059/allure
> FAT-18427: test added

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-identifiers-different.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-marc-fields-actions-in-central-tenant.cy.js
- cypress/e2e/consortia/data-export/simplified-export-of-deleted-authority-record-with-deleted-profile-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-files.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/inventory/instanceRecordView.js
- interactors/select.js
- interactors/textarea.js
[FAT-18453](https://folio-org.atlassian.net/browse/FAT-18453)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/543818)
> FAT-18453/C543818

- cypress/e2e/eureka/authorization-roles/roles-view-capability-set.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-add-role-without-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-details-for-policies-from-different-tenants.cy.js
- cypress/support/api/permissions.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18431
Test case - https://foliotest.testrail.io/index.php?/cases/view/523582
Results -
> FAT-18431-C523582

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-identifiers-different.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-marc-fields-actions-in-central-tenant.cy.js
- cypress/e2e/consortia/data-export/simplified-export-of-deleted-authority-record-with-deleted-profile-in-central-tenant.cy.js
- cypress/e2e/eureka/authorization-roles/roles-view-capability-set.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-add-role-without-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/filter-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/filter-roles-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-details-for-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-policies-from-different-tenants.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/view-roles-from-different-tenants.cy.js
- cypress/support/api/auth-policies.js
- cypress/support/api/permissions.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/bulk-edit-files.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/inventory/instanceRecordView.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
- interactors/select.js
- interactors/textarea.js
Merging old `eureka` branch into `master`
> Eureka to master

- cypress/e2e/eureka/consortia/consortium-manager/cannot-view-policies-without-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-view-roles-without-capabilities-via-cm.cy.js
- cypress/support/fragments/settings/authorization-policies/authorizationPolicies.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-18432
- https://folio-org.atlassian.net/browse/FAT-18759
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/552519
- https://foliotest.testrail.io/index.php?/cases/view/503093
Results:
> FAT-18432-FAT-18759

- cypress/e2e/eureka/authorization-roles/assigning-users/assigning-users-in-role-view.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
https://folio-org.atlassian.net/browse/FAT-18777
C627249 test updated
> FAT-18777: test updated

- cypress/support/fragments/inventory/inventorySearchAndFilter.js
Update effective location  filter
> FAT-18449 Support automated tests

- cypress/e2e/eureka/consortia/consortium-manager/cannot-view-roles-without-capabilities-member-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/create-role-member-via-cm.cy.js
- cypress/support/fragments/consortium-manager/consortiumManagerApp.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-18760
- https://folio-org.atlassian.net/browse/FAT-18761
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/503095
- https://foliotest.testrail.io/index.php?/cases/view/523593
Results:
- https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8068/allure
> FAT-18760, FAT-18761: tests added

- cypress/e2e/eureka/consortia/consortium-manager/cannot-share-role-without-capabilities.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18762
Test case - https://foliotest.testrail.io/index.php?/cases/view/523603
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8073/allure
> FAT-18762: test added

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-permanent-location.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-search-column-name.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-with-source-marc.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-holdings-location-call-number-column.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-clear-location-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-clear-field.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-remove-all-notes-in-Central-tenant.cy.js
Update, stabilize the test cases
> FAT-18447 Support automated tests

- cypress/e2e/consortia/settings/inventory/call-number-browse.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/settings/inventory/instances/callNumberBrowse.js
- cypress/support/fragments/settings/inventory/instances/callNumberTypes.js
https://folio-org.atlassian.net/browse/FAT-18412
---
https://foliotest.testrail.io/index.php?/cases/view/627461
---
> Implementation of C627461 Edit "Call number browse" option from Central/Member tenants

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-notes-sraff-only-action-in-central-tenant.cy.js
- cypress/support/dictionary/affiliations.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-18889](https://folio-org.atlassian.net/browse/FAT-18889)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/494089)
> FAT-18889/C494089

- cypress/e2e/eureka/consortia/consortium-manager/create-role-central-via-cm.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18842
Test case - https://foliotest.testrail.io/index.php?/cases/view/523671
Results -
> FAT-181842: test added

- cypress.config.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-change-note-type-action-in-central-tenant.cy.js
- cypress/support/dictionary/affiliations.js
[FAT-18885](https://folio-org.atlassian.net/browse/FAT-18885)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/477649)
> FAT-18885/C477649

- cypress.config.js
- cypress/support/dictionary/affiliations.js
Add the logic to get tenant names dependent on the environment.
> FAT -18878 Add the logic to get tenant names dependent on the environment.

- cypress/e2e/eureka/consortia/consortium-manager/delete-role-member-via-cm.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18843
Test case - https://foliotest.testrail.io/index.php?/cases/view/543745
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8092/allure
> FAT-18843-C543745

- cypress/e2e/eureka/consortia/consortium-manager/logs-and-reports-shown-in-cm.cy.js
- cypress/support/fragments/consortium-manager/consortiumManagerApp.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18845
Test case - https://foliotest.testrail.io/index.php?/cases/view/552368
Results -
> FAT-18845-C543745

- cypress/e2e/eureka/consortia/consortium-manager/compare-roles-three-tenants.cy.js
- cypress/support/fragments/consortium-manager/authorization-roles/compareRoles.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18846
Test case - https://foliotest.testrail.io/index.php?/cases/view/552363
Results - 
*Note:* results are from R Bugfest due to issue blocking execution on Snapshot - https://folio-org.atlassian.net/browse/EUREKA-698. Test methods are operational on Snapshot.
> FAT-18843-C55236

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-users-verify-errors-for-invalid-identifiers-in-central-tenant.cy.js
[FAT-18883](https://folio-org.atlassian.net/browse/FAT-18883)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/477641)
> FAT-18883/C477641

- cypress.config.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-csv-export-manager-permissions.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-notes-action-in-member-tenant.cy.js
[FAT-19068](https://folio-org.atlassian.net/browse/FAT-19068)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566138)
> FAT-19068/C566138

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-add-note-action-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-users-verify-actions-in-central-tenant.cy.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
[FAT-19098](https://folio-org.atlassian.net/browse/FAT-19098)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/496156)
> FAT-19098/C496156

- cypress/e2e/eureka/consortia/consortium-manager/share-role-edit-central.cy.js
- cypress/support/constants.js
- cypress/support/fragments/consortium-manager/consortiumManagerApp.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
- cypress/support/fragments/topMenuNavigation.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-18840
Test case - https://foliotest.testrail.io/index.php?/cases/view/523609
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8114/allure
> FAT-18840-C523609

- cypress/support/api/users.js
Uppercase letters in username cause issues on ECS due to Keycloak limitations
> Default username changed to lowercase

- cypress/e2e/inventory/call-number-browse/call-number-not-valid-format-with-dewey-can-be-found-in-browse.cy.js
https://folio-org.atlassian.net/browse/FAT-19161
---
https://foliotest.testrail.io/index.php?/cases/view/451466
---
> adjusted C451466 test case

- cypress/e2e/inventory/subject-browse/filtering-by-local-subject-type-in-folio-records.cy.js
- cypress/support/fragments/settings/inventory/instances/subjectTypes.js
***
https://folio-org.atlassian.net/browse/FAT-17430
***
https://foliotest.testrail.io/index.php?/cases/view/584511
***
***
> FAT-17430-C584511

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-incorrectly-formatted-identifiers.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-find-remove.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-change-note-type-outside.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-find-remove-find-replace.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-incorrect-format.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-remove-all-add-note.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-find-remove.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users-incorrect-format.cy.js
- cypress/e2e/bulk-edit/permissions/bulk-edit-user-permissions.cy.js
- cypress/e2e/bulk-edit/query/bulk-edit-query-search-date-time-string.cy.js
- cypress/support/constants.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
> FAT-19179 Support automated test cases

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-remove-all-notes-in-member-tenant.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/share-role-only-central-affiliation.cy.js
- cypress/e2e/users/browse-permissions.cy.js
[FAT-19139](https://folio-org.atlassian.net/browse/FAT-19139)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566152)
> FAT-19139/C566152

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-find-remove-notes-in-central-tenant.cy.js
[FAT-19344](https://folio-org.atlassian.net/browse/FAT-19344)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/552505)
> FAT-19344/C552505

- cypress.config.js
- cypress/support/dictionary/affiliations.js
Add environment-dependent switch affiliation logic
> Add environment-dependent switch affiliation logic

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes-10.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-temporary-location.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-find-replace-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-replace-with-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-find-replace-notes-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-staff-only-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-suppress-from-discovery-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-add-note-in-central.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-change-note-type-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-change-note-type-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-verify-remove-all-notes-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-add-note-action-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-instances-add-note-action-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-replace-item-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-with-action.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-notes-in-central.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-add-note-action-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-change-note-type-action-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-remove-all-notes-action-in-central-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
> FAT-19178 Support automated test cases

- cypress/e2e/eureka/consortia/users/add-update-user-roles-member.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19347
Test case - https://foliotest.testrail.io/index.php?/cases/view/514904
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/8150/allure
> FAT-19347-C514904

- cypress/e2e/eureka/consortia/users/add-update-user-roles-central.cy.js
- cypress/e2e/eureka/consortia/users/add-update-user-roles-member.cy.js
- cypress/e2e/eureka/consortia/users/unassign-user-roles-central.cy.js
- cypress/support/api/permissions.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19348
Test case - https://foliotest.testrail.io/index.php?/cases/view/514916
Results -
> FAT-19348-C514916

- cypress/e2e/inventory/advanced-search/advanced-or-not-search-in-instances.cy.js
- cypress/e2e/inventory/advanced-search/advanced-search-in-inventory.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
- cypress/support/fragments/orders/modals/selectInstanceModal.js
https://folio-org.atlassian.net/browse/FAT-19430
> FAT-19430: tests updated

- cypress/e2e/eureka/consortia/users/add-update-user-roles-central.cy.js
- cypress/e2e/eureka/consortia/users/add-update-user-roles-member.cy.js
- cypress/e2e/eureka/consortia/users/unassign-user-roles-member.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19349
Test case - https://foliotest.testrail.io/index.php?/cases/view/514917
Results -
> FAT-19349: test added

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-clear-locations-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-duplicate-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-replace-item-notes-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-loan-type-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-location-in-central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-replace-with-action.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-staff-only-notes-in-central.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-add-note-action-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-change-note-type-action-in-Central-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-remove-all-notes-action-in-central-tenant.cy.js
- cypress/e2e/fees-&-fines/newFeeFines.cy.js
> FAT-19535 Support automated test

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-instances-change-note-type-within.cy.js
> FAT-19535 Support automated tests

- cypress/e2e/consortia/inventory/browse/call-number-browse-shared-local-on-member.cy.js
- cypress/e2e/consortia/settings/inventory/call-number-browse.cy.js
- cypress/support/api/consortium.js
- cypress/support/constants.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/consortium-manager/inventory/holdings-items/callNumberTypesConsortiumManager.js
- cypress/support/fragments/inventory/inventoryInstances.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
- cypress/support/fragments/settings/inventory/instances/callNumberBrowse.js
- cypress/support/fragments/settings/inventory/instances/callNumberTypes.js
- cypress/support/fragments/settings/tenant/locations/newLocation.js
- cypress/support/tenant.js
> Fat 18413  cherry pick to eureka rbugfest

- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/support/fragments/eholdings/eHoldingsPackage.js
https://folio-org.atlassian.net/browse/FAT-19603
> FAT-19588: test updated

- cypress/support/fragments/settings/tenant/general/index.js
Remove unused export for SSOSettings in tenant general settings
> FAT-19600 Support automated tests

- cypress/e2e/consortia/inventory/browse/call-number-browse-shared-local-on-member.cy.js
> fix for C651515

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-add-note-action-in-member-tenant.cy.js
[FAT-19136](https://folio-org.atlassian.net/browse/FAT-19136)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566143)
> FAT-19136/C566143

- cypress/e2e/inventory/advanced-search/advanced-and-search-in-items.cy.js
- cypress/e2e/inventory/advanced-search/advanced-search-by-title-diacritics.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-marc-bib-without-245-field.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-19734
- https://folio-org.atlassian.net/browse/FAT-19732
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/503055
- https://foliotest.testrail.io/index.php?/cases/view/471499
Allure report:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8257/allure
> FAT-19734, FAT-19732: tests added

- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit_4.cy.js
- cypress/support/fragments/quickMarcEditor.js
> ensure save aurhority record success

- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/e2e/inventory/advanced-search/advanced-search-in-inventory-not-splitting.cy.js
- cypress/e2e/inventory/single-record-import/overlay-by-loc.cy.js
- cypress/support/constants.js
- cypress/support/fragments/inventory/inventoryActions.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-19728
- https://folio-org.atlassian.net/browse/FAT-19731
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/490903
- https://foliotest.testrail.io/index.php?/cases/view/466212
Allure report:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8268/allure
> FAT-19728-FAT-19731

- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-marc-bib-date2-special-chars.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-marc-bib-no-245.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bib-add-multiple-001s.cy.js
- cypress/support/fragments/quickMarcEditor.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-19933
- https://folio-org.atlassian.net/browse/FAT-19934
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/554634
- https://foliotest.testrail.io/index.php?/cases/view/503056
Allure report:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8280/allure/
> FAT-19933, FAT-19934: tests added

- cypress/e2e/acquisition-units/acquisition-unit-restrictions-for-FY-when-user-assigned-to-AU.cy.js
- cypress/e2e/finance/fiscalYears/calulate-available-balance-for-negative-amount.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/budget-summary-and-encumbrances-updated.cy.js
- cypress/e2e/finance/fiscalYears/rollover-fiscal-year.cy.js
- cypress/e2e/finance/funds/filter-transer-from-in-fund.cy.js
- cypress/e2e/finance/funds/test-acquisition-unit-restrictions-for-funds.cy.js
- cypress/e2e/finance/groups/add-funds-to-group.cy.js
- cypress/e2e/finance/groups/add-multiple-funds-to-group.cy.js
- cypress/e2e/finance/transactions/unrelease-encumbrance.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-dollar.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-percent.cy.js
- cypress/e2e/orders/delete-fund-in-pol-w-reviewed-invoice.cy.js
- cypress/e2e/orders/edit-fund-when-invoice-are-cancelled.cy.js
- cypress/e2e/orders/editing-fund-and-increasing-cost-in-pol.cy.js
- cypress/e2e/orders/encumbrance-transaction-updates-when-fund-name-is-changed.cy.js
- cypress/e2e/orders/items-for-receiving-includes-order-closed-statuses.cy.js
- cypress/e2e/orders/receiving-and-check-in/item-statuses-are-set-to-status-other.cy.js
- cypress/support/fragments/finance/funds/funds.js
- cypress/support/fragments/finance/groups/groups.js
- cypress/support/fragments/invoices/invoices.js
- cypress/support/fragments/orders/modals/exportSettingsModal.js
- cypress/support/fragments/orders/orderLineEditForm.js
- cypress/support/fragments/settings/acquisitionUnits/acquisitionUnits.js
- cypress/support/fragments/settings/tenant/general/addresses.js
> FAT-19939 Adjust Thunderjet tests

- cypress/e2e/acquisition-units/acquisition-unit-restrictions-for-FY-when-user-assigned-to-AU.cy.js
- cypress/e2e/finance/fiscalYears/calulate-available-balance-for-negative-amount.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/budget-summary-and-encumbrances-updated.cy.js
- cypress/e2e/finance/funds/filter-transer-from-in-fund.cy.js
- cypress/e2e/finance/groups/add-funds-to-group.cy.js
- cypress/e2e/finance/groups/add-multiple-funds-to-group.cy.js
- cypress/e2e/finance/transactions/unrelease-encumbrance.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-dollar.cy.js
- cypress/e2e/invoices/adjustment-amount-to-invoice-line-in-percent.cy.js
- cypress/e2e/orders/edit-fund-when-invoice-are-cancelled.cy.js
- cypress/e2e/orders/editing-fund-and-increasing-cost-in-pol.cy.js
- cypress/e2e/orders/encumbrance-transaction-updates-when-fund-name-is-changed.cy.js
- cypress/e2e/orders/receiving-and-check-in/item-statuses-are-set-to-status-other.cy.js
- cypress/support/fragments/finance/funds/funds.js
- cypress/support/fragments/finance/groups/groups.js
- cypress/support/fragments/orders/orderLineEditForm.js
- cypress/support/fragments/settings/tenant/general/addresses.js
> FAT-19938 Adjust Thunderjet tests

- cypress/e2e/orders/po-filters.cy.js
- cypress/e2e/organizations/search-organization.cy.js
- cypress/support/fragments/orders/orders.js
- cypress/support/fragments/settings/orders/settingsOrders.js
> FAT-19968 Support automated tests

- cypress/e2e/inventory/search-in-inventory/search-by-barcode-field-of-item-record-is-case-insensitive.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
https://folio-org.atlassian.net/browse/FAT-19963
> FAT-19963: test updated

- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-700-710-marc-fields.cy.js
[FAT-19819](https://folio-org.atlassian.net/browse/FAT-19819)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/648518)
> FAT-19819/C648518

- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bib-no-date2.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19932
Test case - https://foliotest.testrail.io/index.php?/cases/view/554632
Allure report - https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8294/allure
> FAT-19932-C554632

- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-marc-bib-invalid-008.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19924
Test case - https://foliotest.testrail.io/index.php?/cases/view/503015
Allure report - https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8298/allure
> FAT-19924-C503015

- cypress/e2e/finance/fiscalYears/displaying-settings-for-common-rollover.cy.js
- cypress/e2e/finance/fiscalYears/displaying-settings-for-test-rollover.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/budget-summary-and-encumbrances-updated.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/consecutive-rollovers-within-three-fiscal-years.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/encumbrances-are-rolled-over.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/execute-rollover-not-active-allocation.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/make-more-than-one-preview-for-one-ledger.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/planned-budget-status-is-updating-to-active-during-rollover.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-cash-balance-as-transfer-active-allocation.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-cash-balance-as-transfer-not-active-allocation.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollover-is-blocked.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollover-when-pol-has-2-funds.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/test-rollovers-within-3-fy-when-polcontains-2-funds.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/transactions-displaying-correctly-after-fund-name-was-changed.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/verify-rollover-adjustment-and-estimated-price-displayed-correctly-for-foreign-currency-orders-exchange-rate-is-set-manually.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/verify-rollover-adjustment-and-estimated-price-displayed-correctly-for-foreign-currency-orders.cy.js
- cypress/e2e/finance/fiscalYears/rollover-cash-balance-as-allocation-not-active-option.cy.js
- cypress/e2e/finance/fiscalYears/rollover-cash-balance-as-allocation.cy.js
- cypress/e2e/finance/fiscalYears/rollover-cash-balance-as-none-allocation.cy.js
- cypress/e2e/finance/fiscalYears/rollover-fiscal-year.cy.js
- cypress/e2e/finance/fiscalYears/test-and-common-rollover-are-executed-successfully.cy.js
Replace the creation of locations and material types with the use of already existing entities
> FAT-20136 Improve Thunderjet automated tests

- cypress/e2e/inventory/search-in-inventory/date-range-filter-one-box.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-19928
Test case - https://foliotest.testrail.io/index.php?/cases/view/553018
Results -
> FAT-19928: test added

- cypress/e2e/settings/data-export/edit-job-profile.cy.js
- cypress/e2e/settings/data-export/field-mapping-profile-with-suppression.cy.js
- cypress/support/fragments/bulk-edit/query-modal.js
- cypress/support/fragments/data-export/exportJobProfile/exportJobProfiles.js
> FAT-20072 Adjust test cases

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-users-preview.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-columns-titles.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-body-special-chars.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-add-583-marc-field.cy.js
- cypress/e2e/invoices/invoices-create-credit-invoice.cy.js
- cypress/e2e/orders/select-acquisition-method-from-POL.cy.js
- cypress/e2e/settings/orders/increase-pol-limit.cy.js
- cypress/support/fragments/inventory/item/itemRecordEdit.js
> FAT-20072 Support automated tests in daily run

- cypress/e2e/acquisition-units/acquisition-unit-restrictions-for-FY-when-user-is-NOT-assigned-to-AU-only-edit-and-view.cy.js
- cypress/e2e/finance/fiscalYears/fiscalYearRollover/budget-summary-and-encumbrances-updated.cy.js
- cypress/e2e/invoices/invoice-with-fund-different-from-related-pol-can-be-approved.cy.js
- cypress/e2e/invoices/update-exchange-rates-on-invoice-lines-with-multiple-funds.cy.js
- cypress/e2e/orders/deleting-manually-assigned-donor-from-pol.cy.js
- cypress/e2e/orders/select-random-currancy-in-order.cy.js
- cypress/support/dictionary/permissions.js
- cypress/support/fragments/finance/funds/funds.js
- cypress/support/fragments/invoices/invoices.js
- cypress/support/fragments/orders/orderLines.js
- cypress/support/fragments/receiving/modals/editPieceModal.js
- cypress/support/fragments/settings/acquisitionUnits/acquisitionUnits.js
> FAT-20180 Support automated tests in eureka-rbugfest

- cypress/support/fragments/receiving/receiving.js
> fixed C9177 Change location during receiving (thunderjet)

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-240-field-when-marcAuth-111-has-all-subfields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField240-to-authority100-with-all-subfields.cy.js
https://folio-org.atlassian.net/browse/FAT-19969
Update Ids of tests for Sunflower release
> FAT-19969 Update Ids for Sunflower

- cypress/e2e/inventory/classification-browse/classification-browse-suite2.cy.js
- cypress/e2e/inventory/settings/call-number-browse/call-number-browse-settings.cy.js
- cypress/support/fragments/settings/inventory/instances/callNumberBrowse.js
- cypress/support/fragments/settings/inventory/instances/callNumberTypes.js
FAT tickets: 
- https://folio-org.atlassian.net/browse/FAT-19727
- https://folio-org.atlassian.net/browse/FAT-19729
- https://folio-org.atlassian.net/browse/FAT-19730
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/627456
- https://foliotest.testrail.io/index.php?/cases/view/468181
- https://foliotest.testrail.io/index.php?/cases/view/468182
Allure report:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8357/allure
> FAT-19727, FAT-19729, FAT-19730: tests added

- cypress/support/fragments/users/usersCard.js
This is a subsequent PR.
Fix https://jenkins.ci.folio.org/job/folioScheduledTesting/job/folioQualityGates/1688/allure/#suites/cd1af563c364c83f0cb7307ff326d221/8debdd90c2b3c1af/
> UITEST-136: Update the 'patronHasBlocksInPlace' message (follow-up PR).

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-240-field-when-marcAuth-111-has-all-subfields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-all-linkable-fields-automatically-when-marcAuth-have-all-subfields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField240-to-authority100-with-all-subfields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField6XX-to-authority1XX.cy.js
Just updating of Ids for tests from Sunflower branch
> FAT-19969 Update Ids for Sunflower test (2nd part)

- cypress/e2e/settings/users/edit-patron-group.cy.js
- cypress/support/fragments/settings/users/patronGroups.js
> fix for C514937

- cypress/support/fragments/users/userEdit.js
- cypress/support/fragments/users/usersCard.js
> fix for C432_C720

- cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-created-updated-dates.cy.js
Adjust retry logic in test case
> FAT-20178 Support automated tests

- cypress/e2e/inventory/search-in-inventory/filter-instances-by-mode-of-issuance.cy.js
- cypress/e2e/inventory/search-in-inventory/filter-instances-by-nature-of-content.cy.js
- cypress/support/api/inventory.js
- cypress/support/fragments/settings/inventory/instances/natureOfContent.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-20285
- https://folio-org.atlassian.net/browse/FAT-20286
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/476725
- https://foliotest.testrail.io/index.php?/cases/view/476726
Allure report:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8412/allure
> FAT-20285, FAT-20286: tests added

- cypress/e2e/circulation-log/search.cy.js
- cypress/support/fragments/users/usersSearchPane.js
> FAT-20298 fix for C16979_C17010_C421

- cypress/e2e/eureka/authorization-roles/cannot-create-update-delete-default-roles.cy.js
- cypress/support/api/permissions.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-20302
Test case - https://foliotest.testrail.io/index.php?/cases/view/794509
Results -
> FAT-20302-C794509

- cypress.config.js
- cypress/e2e/data-import/importing-marc-authority-files/marc-authority-update-1XX-tag-value-which-controls-2-marc-bib-records.cy.js
- cypress/e2e/inventory/call-number-browse/browse-call-numbers-all.cy.js
- cypress/e2e/inventory/single-record-import/import-by-loc.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit_4.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/automated-linking/auto-linking-pre-defined-linkable-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-valid-ldr.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/link-fields-using-link-headings-button.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-search/plug-in-marc-authority-search.cy.js
> FAT-20271-Fixes: C374167 C387477 C490900 C353533 C422111 C389489

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-users-verify-actions-in-central-tenant-identifiers.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
[FAT-20248](https://folio-org.atlassian.net/browse/FAT-20248)
[Test rail](https://foliotest.testrail.io/index.php?/cases/view/566178)
> FAT-20248/C566178

- cypress/e2e/marc/marc-bibliographic/validation-rules/standard-fields-cannot-be-deleted.cy.js
https://folio-org.atlassian.net/browse/FAT-20316
---
https://foliotest.testrail.io/index.php?/cases/view/499836
---
> Implemented C499836

- cypress/e2e/inventory/call-number-browse/browse-call-numbers-only-correct-types.cy.js
> Fix C405530

- cypress/e2e/orders/pol-search-am-filter.cy.js
- cypress/e2e/orders/pol-with-linked-holdings-could-be-found-by-location-filteringon-order-lines-pane.cy.js
- cypress/support/fragments/orders/orderLines.js
- cypress/support/fragments/orders/orders.js
- cypress/support/fragments/settings/orders/settingsOrders.js
> fixed C668, C350603, C451533 (thunderjet)

- cypress/e2e/settings/remote-storage/remote-storage-delete.cy.js
- cypress/e2e/users/add-and-remove-tags-from-user.cy.js
- cypress/support/fragments/circulation/editStaffClips.js
- cypress/support/fragments/settings/remote-storage/configurations.js
- cypress/support/fragments/users/usersCard.js
> FAT-20382 fix for C9318_C343214_C515006_C163921

- cypress/e2e/inventory/call-number-browse/browse-call-numbers-only-correct-types.cy.js
- cypress/e2e/inventory/single-record-import/import-by-loc.cy.js
- cypress/e2e/inventory/single-record-import/overlay-by-loc.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-marc-bib-edit-ldr.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/automated-linking/pre-defined-fields-linked-after-click-link-headings.cy.js
- cypress/e2e/marc/marc-holdings/marc-holdings-call-number-types.cy.js
> Fixes: C405530 C490900 C490902 C490903 C357566 C389486 C389500

- cypress/e2e/consortia/consortium-manager/view-settings/view-subject-type/user-is-able-view-list-of-subject-types-of-affiliated-tenants.cy.js
- cypress/support/fragments/consortium-manager/inventory/instances/subjectTypesConsortiumManager.js
***
https://folio-org.atlassian.net/browse/FAT-17796
***
https://foliotest.testrail.io/index.php?/cases/view/594398
***
***
> FAT-17796-C594398

- cypress/e2e/inventory/call-number-browse/browse-same-call-number-different-copy-diff-instances.cy.js
- cypress/e2e/inventory/call-number-browse/browse-same-call-number-different-copy.cy.js
- cypress/e2e/inventory/call-number-browse/browse-same-call-number-different-holdings.cy.js
- cypress/e2e/inventory/call-number-browse/full-call-number-generation-holdings-item.cy.js
- cypress/e2e/inventory/call-number-browse/item-call-number-create-update-delete.cy.js
- cypress/support/fragments/inventory/holdingsRecordEdit.js
- cypress/support/fragments/inventory/inventoryInstances.js
- cypress/support/fragments/inventory/search/browseCallNumber.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-20335
- https://folio-org.atlassian.net/browse/FAT-20336
- https://folio-org.atlassian.net/browse/FAT-20384
- https://folio-org.atlassian.net/browse/FAT-20338
- https://folio-org.atlassian.net/browse/FAT-20337
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/478256
- https://foliotest.testrail.io/index.php?/cases/view/651491
- https://foliotest.testrail.io/index.php?/cases/view/651492
- https://foliotest.testrail.io/index.php?/cases/view/692245
- https://foliotest.testrail.io/index.php?/cases/view/651502
<details>
</details>
> FAT-20335-20336-20384-20338-20337

- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/derive-marc-bib-edit-ldr.cy.js
- cypress/support/fragments/quickMarcEditor.js
> Fixes: C695 C357566

- cypress/e2e/consortia/consortium-manager/view-settings/view-subject-sources/user-with-share-permission-sees-subject-sources-of-affiliated-tenants.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-subject-sources/user-with-view-permission-sees-subject-sources-of-affiliated-tenants.cy.js
***
https://folio-org.atlassian.net/browse/FAT-17798
***
https://foliotest.testrail.io/index.php?/cases/view/594420
***
***
> FAT-17798-C594420

- cypress/e2e/consortia/consortium-manager/view-settings/view-subject-sources/user-with-manage-permission-sees-subject-sources-of-affiliated-tenants.cy.js
***
https://folio-org.atlassian.net/browse/FAT-17799
***
https://foliotest.testrail.io/index.php?/cases/view/594421
***
***
> FAT-17799-C594421

- cypress/e2e/bulk-edit/in-app/bulk-adit-in-app-holdings-separating-notes-in-different-columns.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-find-remove.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-notes-find-remove-add-same-type.cy.js
- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-remove-notes.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-administrative-data-for-part-of-the-records.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-append-subfield-to-533-933-999-fields-with-errors.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-find-and-remove-533-933-999-fields-with-errors.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-in-app-remove-584-field-mapped-to-inventory-instance.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-remove-subfield-from-525-925-533-999-fields-with-errors.cy.js
- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-replace-data-in-subfield-of-533-933-999-fields-with-errors.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/inventory/instanceRecordView.js
[FAT-20361](https://folio-org.atlassian.net/browse/FAT-20361)
[https://foliotest.testrail.io/index.php?/cases/view/543785](https://foliotest.testrail.io/index.php?/cases/view/543785)
[https://foliotest.testrail.io/index.php?/cases/view/543809](https://foliotest.testrail.io/index.php?/cases/view/543809)
[https://foliotest.testrail.io/index.php?/cases/view/543812](https://foliotest.testrail.io/index.php?/cases/view/543812)
[https://foliotest.testrail.io/index.php?/cases/view/543814](https://foliotest.testrail.io/index.php?/cases/view/543814)
[https://foliotest.testrail.io/index.php?/cases/view/656340](https://foliotest.testrail.io/index.php?/cases/view/656340)
<details>
<summary>Test result sceeenshots</summary>
<p>
</p>
</details>
> FAT-20361-C543785-C543809-C543812-C543814-C656340

- cypress/e2e/data-import/importing-marc-authority-files/marc-authority-update-1XX-tag-value-which-controls-2-marc-bib-records.cy.js
- cypress/e2e/eholdings/package/eholdings-packages.cy.js
- cypress/e2e/inventory/contributors-browse/browse-contributors-linked.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/edit-marc-auth-which-has-S-sign.cy.js
> Fixes: C451558 C395596 C695 C374167

- cypress/e2e/consortia/inventory/instance/link-in-data-export-app-after-exporting-local-folio-source-instance-from-instance-details-pane-on-member.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10398
***
https://foliotest.testrail.io/index.php?/cases/view/422079
***
***
> FAT-10398-C422079

- cypress/e2e/consortia/inventory/instance/link-in-data-export-app-after-exporting-local-marc-source-instance-from-instance-details-pane-on-member.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10399
***
https://foliotest.testrail.io/index.php?/cases/view/422080
***
***
> FAT-10399-C422080

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-clear-location-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-find-remove-action-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-electronic-access-replace-with-action-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-replace-location-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-suppress-from-discovery-in-member-tenant.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/bulk-edit/query-modal.js
- cypress/support/fragments/bulk-edit/select-permanent-location-modal.js
[FAT-20361](https://folio-org.atlassian.net/browse/FAT-20361)
[C566159](https://foliotest.testrail.io/index.php?/cases/view/566159)
[C566160](https://foliotest.testrail.io/index.php?/cases/view/566160)
[C566161](https://foliotest.testrail.io/index.php?/cases/view/566161)
[C566162](https://foliotest.testrail.io/index.php?/cases/view/566162)
[C566163](https://foliotest.testrail.io/index.php?/cases/view/566163)
<details><summary>Test result screenshots</summary>
<p>
</p>
</details>
> FAT-20361-C566159-566160-C566161-C566162-C566163

- cypress/e2e/consortia/inventory/instance/link-in-data-export-app-after-exporting-shared-folio-source-instance-from-details-pane-on-member.cy.js
***
https://folio-org.atlassian.net/browse/FAT-10400
***
https://foliotest.testrail.io/index.php?/cases/view/422081
***
***
> FAT-10400-C422081

- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-holdings-suppress-from-discovery-with-warnings-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-remove-item-notes-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-find-replace-item-notes-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-add-note-action-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/in-app/bulk-edit-in-app-items-verify-change-note-type-action-in-member-tenant.cy.js
[FAT-20361](https://folio-org.atlassian.net/browse/FAT-20361)
[C566164](https://foliotest.testrail.io/index.php?/cases/view/566164)
[C566165](https://foliotest.testrail.io/index.php?/cases/view/566165)
[C566166](https://foliotest.testrail.io/index.php?/cases/view/566166)
[C566167](https://foliotest.testrail.io/index.php?/cases/view/566167)
[C566168](https://foliotest.testrail.io/index.php?/cases/view/566168)
<details><summary>Test result screenshots</summary>
<p>
</p>
</details>
> FAT-20361-C566164-C566165-C566166-C566167-C566168

- cypress/e2e/requests/assign-tags-to-request.cy.js
- cypress/e2e/requests/edit-request.cy.js
- cypress/e2e/requests/request-types-filter.cy.js
- cypress/e2e/requests/requests-sort.cy.js
- cypress/e2e/settings/circulation/fixed-due-date-schedules/schedule-does-not-cover-the-test-date.cy.js
- cypress/e2e/users/from-user-to-create-view-requests.cy.js
- cypress/e2e/users/proxy-user-can-checkout-on-the-behalf-of-the-user.cy.js
- cypress/support/fragments/users/userEdit.js
> FAT-20489 fix C540 C541 C2379 C556 C747 C641 C433 C720

- cypress/e2e/finance/ledgers/ledger-export-settings-pairwise-variants/expense-classes-none.cy.js
- cypress/e2e/orders/holdings-records creation-for-order-with-pe-mix-format-eresource-none.cy.js
- cypress/support/fragments/orders/modals/unopenConfirmationModal.js
> fixed C377037, С377040, С402351, С350976

- cypress/e2e/eureka/consortia/consortium-manager/cannot-add-role-without-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-create-role-without-tenant-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-duplicate-role-insufficient-capabilities-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/cannot-share-role-without-capabilities.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/create-role-central-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/create-role-member-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/create-roles-same-name-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/delete-duplicate-of-shared-role.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/delete-role-member-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/delete-shared-role.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/duplicate-non-shared-role-central-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/duplicate-non-shared-role-member-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/duplicate-shared-role-central-via-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/member-role-cannot-be-shared.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/role-detail-view-in-cm.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/share-role-assign-users-member.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/share-role-capability-sets-missing-in-members.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/share-role-edit-central.cy.js
- cypress/e2e/eureka/consortia/consortium-manager/share-role-only-central-affiliation.cy.js
https://folio-org.atlassian.net/browse/FAT-20535
Tests updated due to changes introduced in https://folio-org.atlassian.net/browse/UICONSET-226:
- https://foliotest.testrail.io/index.php?/cases/view/502981
- https://foliotest.testrail.io/index.php?/cases/view/523582
- https://foliotest.testrail.io/index.php?/cases/view/523593
- https://foliotest.testrail.io/index.php?/cases/view/523596
- https://foliotest.testrail.io/index.php?/cases/view/523603
- https://foliotest.testrail.io/index.php?/cases/view/523604
- https://foliotest.testrail.io/index.php?/cases/view/523606
- https://foliotest.testrail.io/index.php?/cases/view/523609
- https://foliotest.testrail.io/index.php?/cases/view/523612
- https://foliotest.testrail.io/index.php?/cases/view/523665
- …
> FAT-20535: tests updated

- cypress/e2e/fees-&-fines/cancel-fee-fine.cy.js
- cypress/e2e/title-level-request/user-directed-to-request-queue-with-correct-number-of-requests-displayed.cy.js
- cypress/support/fragments/requests/requests.js
> FAT-20489 fix C356793_C350557

- cypress/e2e/orders/inventory-interaction/permission-does-not-grant-delete-polpermission.cy.js
> fixed C367948

- cypress/support/fragments/bulk-edit/query-modal.js
Failed tests 
https://jenkins.ci.folio.org/job/folioScheduledTesting/job/folioQualityGates/1879/allure/#suites/2e666168d4e1bfbd22ce1fc4db449ade/af2f35909e2d81e7/
https://jenkins.ci.folio.org/job/folioScheduledTesting/job/folioQualityGates/1879/allure/#suites/2e666168d4e1bfbd22ce1fc4db449ade/d6db5edf00c389a4/
[FAT-20567](https://folio-org.atlassian.net/browse/FAT-20567)
> FAT-20567 Fix bulk-edit query tests after changes in FQM manager

- cypress/e2e/inventory/tags/assign-tags-preceding-succeeding-titles-present.cy.js
- cypress/e2e/title-level-request/user-directed-to-request-queue-with-correct-number-of-requests-displayed.cy.js
- cypress/support/fragments/finance/funds/funds.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
- cypress/support/fragments/quickMarcEditor.js
- cypress/support/fragments/requests/requests.js
> FAT-20489 fix C350557_C358961

- cypress/e2e/bulk-edit/in-app/instances-with-source-marc/bulk-edit-append-subfield-to-505-905-fields.cy.js
- cypress/e2e/data-export/holdings-records-export/instance-hrid-004-field.cy.js
- cypress/e2e/data-export/holdings-records-export/verify-852-field-for-folio-holdings-in-exported-marc-record.cy.js
> FAT-20487 Support automated test

- cypress/e2e/marc/marc-bibliographic/validation-rules/specification-storage-fields-api/local-fields-indicators-duplicate-order-validation-api.cy.js
https://folio-org.atlassian.net/browse/FAT-20492
---
https://foliotest.testrail.io/index.php?/cases/view/499657
---
> implemented C499657

- cypress/e2e/inventory/call-number-browse/create-holdings-with-typed-call-number-trailing-spaces.cy.js
- cypress/e2e/inventory/tags/quick-add-remove-multiple-tags-instance-marc.cy.js
- cypress/e2e/inventory/tags/quick-add-remove-multiple-tags-instance.cy.js
- cypress/e2e/inventory/tags/quick-add-remove-multiple-tags-item.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
- cypress/support/fragments/inventory/item/itemRecordView.js
- cypress/support/utils/interactorsTools.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-20556 (part 3)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/490906
- https://foliotest.testrail.io/index.php?/cases/view/490907
- https://foliotest.testrail.io/index.php?/cases/view/490909 (currently failing due to [UIIN-3459](https://folio-org.atlassian.net/browse/UIIN-3459))
- https://foliotest.testrail.io/index.php?/cases/view/543802
<details>
</details>
> FAT-20556, pt3: C490906, C490907, C490909, C543802 added

- cypress/e2e/users/validate-metadata-accordion-after-updating-user.cy.js
- cypress/support/fragments/users/usersCard.js
> FAT-20589 add C428

- cypress/e2e/inventory/classification-browse/browse-using-classification-all-option-and-select-exact-match-result.cy.js
- cypress/e2e/inventory/classification-browse/browse-using-classification-all-option-and-select-non-exact-match-result.cy.js
- cypress/e2e/inventory/classification-browse/browse-using-dewey-decimal-classification-option-and-select-exact-match-result.cy.js
- cypress/e2e/inventory/classification-browse/browse-using-dewey-decimal-classification-option-and-select-non-exact-match-result.cy.js
- cypress/e2e/inventory/classification-browse/browse-using-lib-of-congress-classification-option-and-select-exact-match-result.cy.js
- cypress/e2e/inventory/classification-browse/browse-using-lib-of-congress-classification-option-and-select-non-exact-match-result.cy.js
https://folio-org.atlassian.net/browse/FAT-20373
Ids update for updated in Trillium test cases
> FAT-20373-sunflower Ids update

- cypress/support/fragments/inventory/search/browseClassifications.js
https://folio-org.atlassian.net/browse/FAT-20373 - new columns have been added to Classification browse result pane ("Title" and "Contributors")
Allure: https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8527/allure/#suites/550efd884ce8d8fd5dfe89b7507c15b4/8474b398dd2cc4d0/
> FAT-20373-trillium New columns check

- cypress/e2e/consortia/consortium-manager/view-settings/view-contributor-types/user-with-edit-permission-view-contributor-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-contributor-types/user-with-share-permission-view-contributor-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-contributor-types/user-without-contributor-type-permission-view-contributor-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-holdings-types/user-with-view-permission-view-holdings-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-instance-status-types/user-with-share-permission-view-instance-status-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-instance-status-types/user-without-instance-status-type-permission-view-instance-status-types.cy.js
- cypress/support/fragments/consortium-manager/inventory/holdings/holdingsTypesConsortiumManager.js
- cypress/support/fragments/consortium-manager/inventory/instances/contributorTypesConsortiumManager.js
- cypress/support/fragments/settings/inventory/holdings/holdingsTypes.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-20625 (part 3)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/411537
- https://foliotest.testrail.io/index.php?/cases/view/411536
- https://foliotest.testrail.io/index.php?/cases/view/411514
- https://foliotest.testrail.io/index.php?/cases/view/411516
- https://foliotest.testrail.io/index.php?/cases/view/411515
- https://foliotest.testrail.io/index.php?/cases/view/411479
<details>
</details>
> FAT-20625-pt3: C411537,C411536,C411514,C411516,C411515,C411479 added

- cypress/e2e/finance/transactions/order-with-three-po-lines-can-not-be-opened-when-encumbered-available-balance-is-less-that-order-total.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-created-in-current-FY-for-previous-FYwhen-POL-created-in-previous-FY.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-in-current-FY-for-previous-FY.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-with-more-than-50-invoice-lines.cy.js
- cypress/e2e/invoices/pay-invoice-with-multiple-expense-classes.cy.js
- cypress/e2e/invoices/save-invoise-fiscal-year-after-adding-adjustment.cy.js
- cypress/e2e/orders/items-for-receiving-includes-order-closed-statuses.cy.js
- cypress/e2e/orders/manage-user-assignments-in-routing-list-from-orders.cy.js
- cypress/e2e/orders/one-tiem-pol-can-not-be-saved-without-expense-class.cy.js
- cypress/e2e/orders/ongoing-pol-can-not-be-saved-without-expense-class.cy.js
- cypress/e2e/receiving/making-display-to-public-checkbox-visible-on-holdings-for-already-received-piece-with-display-on-holdings-false.cy.js
- cypress/support/fragments/finance/funds/funds.js
- cypress/support/fragments/invoices/invoices.js
https://foliotest.testrail.io/index.php?/cases/view/446075
> implement C446075

- cypress/e2e/consortia/consortium-manager/view-settings/view-item-note-types/user-with-edit-permission-view-item-note-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-item-note-types/user-with-share-permission-view-item-note-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-item-note-types/user-without-permission-view-item-note-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-material-types/user-with-edit-permission-view-material-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-material-types/user-with-view-permission-view-material-types.cy.js
- cypress/e2e/consortia/consortium-manager/view-settings/view-material-types/user-without-permission-view-material-types.cy.js
- cypress/support/fragments/consortium-manager/inventory/items/materialTypesConsortiumManager.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-20625 (part 5)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/411437
- https://foliotest.testrail.io/index.php?/cases/view/411438
- https://foliotest.testrail.io/index.php?/cases/view/411439
- https://foliotest.testrail.io/index.php?/cases/view/411415
- https://foliotest.testrail.io/index.php?/cases/view/411416
- https://foliotest.testrail.io/index.php?/cases/view/411417
<details>
</details>
> FAT-20625-pt5

- cypress/e2e/inventory/contributors-browse/browse-in-inventory.cy.js
- cypress/e2e/inventory/search-in-inventory/search-instance-by-issn-with-x-at-the-end-in-item-tab.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
> Fix: C388531 C451459 C388641

- cypress/e2e/circulation-log/filtering-circulation-log-by-loan-actions.cy.js
- cypress/e2e/circulation-log/search.cy.js
- cypress/e2e/patron-notices/item-aged-to-lost-triggers.cy.js
- cypress/e2e/patron-notices/manual-fee-fine-notices-by-fee-fine-type-charge-and-action.cy.js
- cypress/e2e/settings/circulation/fee-fine/overdue-fine-policies.cy.js
- cypress/e2e/settings/users/fees&fines/owners.cy.js
- cypress/support/fragments/settings/users/usersOwners.js
- cypress/support/fragments/users/payFeeFine.js
- cypress/support/fragments/users/refundFeeFine.js
- cypress/support/fragments/users/transferFeeFine.js
- cypress/support/fragments/users/waiveFeeFineModal.js
> Fat 20589 fix for sunflower critical smoke

- cypress/e2e/fse/api/oa-api.cy.js
- cypress/e2e/fse/ui/oa-ui.cy.js
- cypress/support/api/index.js
- cypress/support/api/oa.js
- cypress/support/fragments/oa/oaNewPublicationRequest.js
- cypress/support/fragments/oa/oaSearchAndFilter.js
- cypress/support/fragments/topMenu.js
> FSE mod-oa tests added

- cypress/e2e/checkout/checkout.multipiece.items.cy.js
- cypress/e2e/fees-&-fines/patron-block/patron-block-maximum-fee-fine-balance-and-lost-items-removed-after-lost-item-returned-renewed.cy.js
- cypress/e2e/fees-&-fines/the-page-is-displayed-when-there-is-no-product.cy.js
- cypress/e2e/loans/loan-change-due-dates.cy.js
- cypress/e2e/loans/loan-dates.cy.js
- cypress/e2e/patron-notices/item-aged-to-lost-triggers.cy.js
- cypress/e2e/requests/filter-requests-by-service-point.cy.js
- cypress/e2e/requests/new-request-with-patron-comment.cy.js
- cypress/e2e/settings/circulation/create-edit-delete-cancellation-reasons.cy.js
- cypress/e2e/settings/users/fees&fines/owners.cy.js
- cypress/e2e/settings/users/fees&fines/verify-that-you-can-create-edit-delete-shared-manual-charges-for-institution.cy.js
- cypress/e2e/title-level-request/edit-recall-request.cy.js
> Fat 20589 ramsons fixes

- cypress/e2e/inventory/instance/duplicate-instance-empty-dates.cy.js
- cypress/e2e/inventory/instance/edit-instance-date-type-empty-dates.cy.js
- cypress/e2e/inventory/instance/edit-instance-empty-dates.cy.js
- cypress/e2e/inventory/instance/edit-instance-no-date1.cy.js
- cypress/e2e/inventory/instance/edit-instance-reset-date-type.cy.js
- cypress/e2e/inventory/instance/edit-instance-special-char-dates.cy.js
- cypress/support/fragments/inventory/instanceRecordEdit.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-21559 (part 3)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/566517
- https://foliotest.testrail.io/index.php?/cases/view/552529
- https://foliotest.testrail.io/index.php?/cases/view/552530
- https://foliotest.testrail.io/index.php?/cases/view/566514
- https://foliotest.testrail.io/index.php?/cases/view/566516
- https://foliotest.testrail.io/index.php?/cases/view/552532
<details>
</details>
> FAT-21559-pt3: tests added

- cypress/e2e/oai-pmh/list-identifiers/instance-marc-retrieved-with-deleted-item-and-holdings.cy.js
- cypress/e2e/oai-pmh/list-identifiers/instance-marc-retrieved-with-edited-item.cy.js
- cypress/e2e/oai-pmh/list-identifiers/marc-bib-retrieved-with-edited-holding.cy.js
[FAT-21618](https://folio-org.atlassian.net/browse/FAT-21618)
[C380630](https://foliotest.testrail.io/index.php?/cases/view/380630)
[C385648](https://foliotest.testrail.io/index.php?/cases/view/385648)
[C380621](https://foliotest.testrail.io/index.php?/cases/view/380621)
<details><summary>Screenshots</summary> <p>
</p> </details>
> FAT-21618-C380630-C385648-C380621

- cypress/e2e/eholdings/package/cancel-changes-using-cancel-buttom-in-custom-packages.cy.js
- cypress/e2e/eholdings/package/cancel-changes-using-cancel-button-in-custom-packages.cy.js
- cypress/e2e/eholdings/package/cancel-changes-using-x-icon-in-custom-package.cy.js
- cypress/e2e/eholdings/provider/cancel-changes-using-cancel-button.cy.js
- cypress/e2e/eholdings/provider/cancel-changes-using-x-icon-button.cy.js
- cypress/e2e/inventory/call-number-browse/browse-same-call-number-different-copy-diff-instances.cy.js
- cypress/e2e/marc/marc-authority/edit-authority-record/marc-authority-edit-validation-rules-modal.cy.js
- cypress/e2e/permissions/inventory/browse-search-permissions.cy.js
- cypress/support/fragments/eholdings/eHoldingsNewCustomPackage.js
- cypress/support/fragments/eholdings/eHoldingsPackages.js
- cypress/support/fragments/eholdings/eHoldingsProviderEdit.js
https://folio-org.atlassian.net/browse/FAT-20591
https://foliotest.testrail.io/index.php?/cases/view/423475
https://foliotest.testrail.io/index.php?/cases/view/423476
https://foliotest.testrail.io/index.php?/cases/view/423457
https://foliotest.testrail.io/index.php?/cases/view/423458
<details>
<summary> Test results </summary>
</details>
> implement C423475 C423476 C423457 C423458

- cypress/e2e/inventory/search-in-inventory/verify-search-on-contributor.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-holdings-hrid.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-identifier.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-instance-hrid.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-isbn.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-issn.cy.js
- cypress/e2e/inventory/search-in-inventory/verify-search-on-subject.cy.js
- cypress/support/fragments/inventory/inventoryInstances.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-21625 (part 4)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/9207
- https://foliotest.testrail.io/index.php?/cases/view/9206
- https://foliotest.testrail.io/index.php?/cases/view/2323
- https://foliotest.testrail.io/index.php?/cases/view/2322
- https://foliotest.testrail.io/index.php?/cases/view/3611
- https://foliotest.testrail.io/index.php?/cases/view/2321
- https://foliotest.testrail.io/index.php?/cases/view/2320
<details>
</details>
> FAT-21625-pt4

- cypress/e2e/consortia/inventory/item/re-order-items/api-update-ownership-multiple-items-check-order-field.cy.js
- cypress/e2e/consortia/inventory/item/re-order-items/ui-create-item-shared-instance-multiple-holdings.cy.js
- cypress/e2e/consortia/inventory/item/re-order-items/ui-shared-instance-multiple-holdings-update-item-ownership.cy.js
- cypress/e2e/consortia/inventory/item/re-order-items/ui-shared-instance-update-holdings-ownership.cy.js
- cypress/support/fragments/inventory/item/inventoryItems.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-21683 (part 1)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/808508
- https://foliotest.testrail.io/index.php?/cases/view/808509
- https://foliotest.testrail.io/index.php?/cases/view/808510
- https://foliotest.testrail.io/index.php?/cases/view/812992
<details>
</details>
> FAT-21683-pt1: tests added

- cypress/e2e/inventory/subject-browse/browse-subjects-exact-match.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects-header-counter-absent.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects-multiple-records.cy.js
- cypress/e2e/inventory/subject-browse/browse-subjects-query-params.cy.js
- cypress/e2e/inventory/subject-browse/search-by-subject-with-quotes.cy.js
* FAT-21683-pt6: C350707, C356831 added
* FAT-21683-pt6: C357531,C358530,C360947 added
> FAT-21683-last (#5673)

- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-heldby-facet-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-heldby-shared-facets-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-call-numbers-shared-local-member.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/browse-same-call-number-shared-facet.cy.js
- cypress/e2e/consortia/inventory/call-number-browse/facet-options-shown-by-performing-search-in-member.cy.js
https://folio-org.atlassian.net/browse/FAT-21820
Ids update for cloned test cases
> FAT-21820 master-sunflower Ids update

- cypress/e2e/marc/marc-authority/edit-authority-record/edit-marc-auth-which-has-$-sign.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bibl-record-which-has-$-sign.cy.js
https://folio-org.atlassian.net/browse/FAT-21781
Ids update for cloned tests
> FAT-21781-ramsons Ids update

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-notes-columns-titles.cy.js
- cypress/e2e/consortia/bulk-edit/member-tenant/bulk-edit-in-app-instances-add-note-action-in-member-tenant.cy.js
- cypress/e2e/consortia/bulk-edit/member-tenant/bulk-edit-in-app-instances-staff-suppress-in-member-tenant.cy.js
- cypress/e2e/inventory/move-holdings-and-item/moving-holdings.cy.js
- cypress/support/fragments/bulk-edit/query-modal.js
- cypress/support/fragments/inventory/inventoryInstance.js
- cypress/support/fragments/inventory/inventorySearchAndFilter.js
> FAT-21730 Support automated tests

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-bib-invalid-006-007-field-length.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-bib-with-multiple-006-007-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-bib-with-undefined-1XX-field.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-bib-with-undefined-field.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-bib-without-006-007-fields.cy.js
- cypress/support/constants.js
- cypress/support/fragments/quickMarcEditor.js
FAT tickets:
- https://folio-org.atlassian.net/browse/FAT-21798 (part 2)
Test cases:
- https://foliotest.testrail.io/index.php?/cases/view/496227
- https://foliotest.testrail.io/index.php?/cases/view/496233
- https://foliotest.testrail.io/index.php?/cases/view/499621
- https://foliotest.testrail.io/index.php?/cases/view/514992
- https://foliotest.testrail.io/index.php?/cases/view/519973
<details>
</details>
> FAT-21798-pt2

- cypress/e2e/eureka/consortia/login/login-member-tenant-selection-url.cy.js
- cypress/support/login.js
FAT ticket:
https://folio-org.atlassian.net/browse/FAT-21899
Test case:
https://foliotest.testrail.io/index.php?/cases/view/740245
Results:
> FAT-21899: test added

- cypress/e2e/eholdings/package/create-custom-package-remove-date-range.cy.js
- cypress/e2e/eholdings/package/delete-custom-package.cy.js
- cypress/support/fragments/eholdings/eHoldingsNewCustomPackage.js
- cypress/support/fragments/eholdings/eHoldingsPackageView.js
- cypress/support/fragments/eholdings/eHoldingsPackages.js
https://folio-org.atlassian.net/browse/FAT-20591
https://foliotest.testrail.io/index.php?/cases/view/422012
https://foliotest.testrail.io/index.php?/cases/view/605986
<details>
<summary>Test results </summary>
</details>
> Implement C422012 C605986

- cypress/e2e/eholdings/package/export-package-verify-title-columns-no-package-notes.cy.js
- cypress/e2e/eholdings/package/export-single-package-without-titles.cy.js
- cypress/e2e/eholdings/package/remove-date-range-custom-package.cy.js
- cypress/e2e/eholdings/package/remove-date-range-managed-package.cy.js
- cypress/support/fragments/eholdings/eHoldingsNewCustomPackage.js
- cypress/support/fragments/eholdings/eHoldingsPackageView.js
https://folio-org.atlassian.net/browse/FAT-20591
https://foliotest.testrail.io/index.php?/cases/view/357007
https://foliotest.testrail.io/index.php?/cases/view/360110
https://foliotest.testrail.io/index.php?/cases/view/422013
https://foliotest.testrail.io/index.php?/cases/view/422014
<details>
<summary> Test results </summary>
</details>
> Implement C357007 C360110 C422013 C422014

- cypress/support/constants.js
Code of "LC Demographic Group Terms" was changed to "LCDGT"
[FAT-22030](https://folio-org.atlassian.net/browse/FAT-22030)
> FAT-22030 Change code of "LC Demographic Group Terms" Authority source file

- cypress/e2e/inventory/classification-browse/classification-browse-suite1.cy.js
- cypress/e2e/inventory/search-in-inventory/correct-page-title-inventory-search.cy.js
- cypress/e2e/inventory/search-in-inventory/filter-instances-by-language.cy.js
- cypress/e2e/inventory/search-in-inventory/filter-instances-by-mode-of-issuance.cy.js
- cypress/e2e/inventory/search-in-inventory/filter-instances-by-resource-type.cy.js
- cypress/e2e/inventory/search-in-inventory/staff-suppress-facet-oclc-search.cy.js
- cypress/e2e/inventory/search-in-select-instance-plugin/search-marc-by-lccn-normalized-spaces-case-insensitive.cy.js
- cypress/e2e/inventory/version-history/version-history-source-bib-crud-updates-import.cy.js
- cypress/e2e/inventory/version-history/zzz_disable-audit-log-and-check-bib-source.cy.js
- cypress/e2e/marc/marc-bibliographic/validation-rules/specification-storage-fields-api/local-fields-api.cy.js
_Note:_
In C423409, changed record language from English to Japanese because of the data issue (duplicate English language entities). With less used Japanese such situation will be less likely going forward.
> Spitfire S BF TLS fixes 10/8
