folio-org/stripes-testing

- helpers.js
I expect the helper function createInventory in stripes-testing will fail due to a newly introduced mandatory field in ui-inventory Instance form. 
Something like this PR is probably needed to set the field and make tests using this helper pass.
> Set required field `hrid` to unique value UITEST-50

- CHANGELOG.md
- helpers.js
Changes to the aria attributes in MCL must be reflected in the
integration tests as well.
Refs [UITEST-58](https://issues.folio.org/browse/UITEST-58), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
> integration tests must accommodate MCL aria changes

- README.md
- doc/nightmare.md
Write better documentation for running tests, particularly in the
context of folks who are not familiar with front-end code but who may
want to run the tests to check whether they pass based on changes to
back-end modules.
Refs [UITEST-56](https://issues.folio.org/browse/UITEST-56)
> add doc for running tests

- CHANGELOG.md
- folio-ui.config.js
- helpers.js
The `clickable-settings` button may not always be available in the UI.
Specifically if there are more than 11 apps in the bundle, then it will
not be available. But there's still hope! The element in the apps menu
_is_ always available, and this change updates tests to find that
element instead.
Refs [STRIPES-606](https://issues.folio.org/browse/STRIPES-606)
> use always-available settings identifier

- helpers.js
The original signature of the functions was such that they returned functions. This is expected if they're to be used with `.use()`. However, the fact that they take and resolve a `done` Promise means that we can't actually chain them with `use()` - they need to be the last item _anyway_.
So I putzed around trying to get them to work correctly with `use` so that nightmare would let me do something like `.use(helpers.clickApp).click('#button-foo')` but I could never sort it out to a place where that was possible. 
So because of that, I'm just dropping these down to regular functions so that they're usage is clearer and cleaner.
> clickApp/clickSettings: Changed signature to regular function

- CHANGELOG.md
- package.json
A long time ago
in a repository
far, far away ...
STRIPES  FORCE
EPISODE DCXI
It is a period of security concerns
for the consortium. Brave developers,
committing from Canada, have closed
most of the known vulnerabilities.
A lone dependency, held over from
an earlier age before a library was
converted from a framework, remains
and causes warnings.
With that dependency removed, the
package will be from from known
vulnerabilities and there will be
security in the repository...
Refs [STRIPES-611](https://issues.folio.org/browse/STRIPES-611)
> remove unused mocha deps

- CHANGELOG.md
- xnightmare.js
`xclick` triggered events outside the context of Nightmare itself and
that never worked reliably. It seemed to send Nightmare off into some
neverneverland of parallel execution that it could never return from.
> remove xclick

- helpers.js
Do a better job waiting for new instance, holdings record, and items to
be created. Rather then calling `done()` after clicking the `new thing`
button, wait for the `new thing` button to be removed and for the `new
sub-thing` button to appear on the view-instance form.
This may help the app settle down a bit when creating new records.
> better create-inventory wait handling

- CHANGELOG.md
- package.json
Version 3.0.2 uses Electron `^2.0.18`; earlier versions have a security
vulnerability. Thanks, @julianladisch!
> bump Nightmare to 3.0.2

- CHANGELOG.md
- helpers.js
The `copyNumbers` field is now presented as an array, not a scalar, so
the new-item helper needs to reflect that.
> update item-form selector

- CHANGELOG.md
- helpers.js
Semantic selectors appear to be more reliable than markup selectors for
this test.
Refs [UITEST-69](https://issues.folio.org/browse/UITEST-69)
> UITEST-69 prefer semantic over markup selectors

- helpers.js
Sometimes, `wait()`ing for a selector just isn't enough. That doesn't
really make sense, but it's The Truth. Without a numeric wait IN
ADDITION to the selector-wait, the value going into the barcode field
will, occasionally, have its first few characters lopped off.
Refs [UITEST-69](https://issues.folio.org/browse/UITEST-69)
> UITEST-69 add numeric waits as well

- helpers.js
The copy-number field has changed in recent versions between being
repeatable and not. In order to continue using this helper with some
older platforms, we need to avoid interacting with that field because
the selectors for the old and new versions are different, meaning the
test will fail against either the old and new platform. Pity, given that
the only reason this field is in here at all is UITEST-68.
Refs [FOLIO-2248](https://issues.folio.org/browse/FOLIO-2248), [UITEST-68](https://issues.folio.org/browse/UITEST-68)
> FOLIO-2248 avoid copy-number in inventory-helper

- helpers.js
Nightmare appears to be getting hung up in some MCL selections. I'm not
sure how this is coming up now given that this passed for several days,
but here we are. Removing some of the markup and leaving the selector to
stand on semantic markup alone seems to do the trick.
Refs [UITEST-70](https://issues.folio.org/browse/UITEST-70)
> UITEST-70 be less markupy, more semantic

- helpers.js
I have an open PR in stripes-core ([STCOR-377](https://github.com/folio-org/stripes-core/pull/719)) with updates that changes how the main nav items are rendered, which has an effect on the existing integration tests.
In this PR I have made some changes for the test helpers to ensure that tests won't break once the updated MainNav is merged.
**Note:** I have tried to make this change backward compatible so that it will work with both the current stripes-core master and the new changes. 
It's tested and working in `ui-users` but we'll need to run all integration tests to ensure that everything is working as expected.
It's also assumed that all modules are using the updated test helpers to navigate between apps. If there should be some modules out there that are using their own custom …
> Update test helpers to work with new main nav changes in stripes-core

- helpers.js
Let us go then, you and I
When my Nightmare is spread out against the sky
Like an Interactor etherized upon a table.
Let us paw through certain half-functional tests
And CSS resets
For buttons lost in holdings' empty well.
Click new-item button pearls in accordion-shells.
Refs [UITEST-71](https://issues.folio.org/browse/UITEST-71)
> UITEST-71 open closed accordions to find their buttons

- helpers.js
The selector for clicking the holdings-record's accordion was not
sufficiently selective, finding the first accordion in any pane rather
than specifically in the instance-details pane. In tests, the effect was
that the click was directed to an accordion in the search pane rather
than in the details pane.
I'm not sure why this manifested now. It's possible some recent work on
accordions in stripes-components is related, e.g.
https://github.com/folio-org/stripes-components/pull/1191, but isn't
clear how that would be the case.
Refs [UITEST-74](https://issues.folio.org/browse/UITEST-74)
> UITEST-74 click the correct accordion

- helpers.js
- package.json
Don't accept `done` or call it within `checkoutList`. Instead, return
the given `nightmare` instance in order to wait until all the promises
in the `then` block here resolve, allowing the calling function to call
`done` in its own `then` block.
> refactor checkoutList

- helpers.js
Click the `close` button in callouts in order to allow tests to proceed
more quickly. Previously, tests would wait until the callouts were
closed by their automatic/internal timer.
> close callouts

- helpers.js
These buttons moved in folio-org/ui-inventory/pull/998 but folks forgot
to update the integration tests, and existing failures masked this new
error.
> UIIN-917 move new/edit item buttons to footer

- helpers.js
Circulation-related settings used to have a selector like `a div` but it
appears that switched to `div a` ... somewhere, probably in
`<MultiColumnList>` in stripes-components. This update tries to make the
selectors a little bit more semantic/robust. I'm not sure if it actually
does that or if it just rearranges things, but in any case tests work
again, so, yay.
> update MCL anchor handling

- helpers.js
The default format of an MCL row changed, no longer including
`role="row"` by default as of folio-org/stripes-components/pull/1205.
This update reflects that, using a CSS selector instead.
> UICHKOUT-602 update selector

- helpers.js
`ui-inventory` was substantially refactored in [PR #1055](https://github.com/folio-org/ui-inventory/pull/1055). The selector changes here accomodate the DOM changes there.
> handle DOM changes since ui-inventory #1055

- interactors/button.js
- interactors/index.js
Upgrade the Buttton interactor to the new bigtest interactor syntax and make it available for consumption by any test suite. You can see this in action in folio-org/stripes-components#1459
The button can render either as a button tag or as a link, therefore extending the button interactor from bigtest did not feel like the best approach. Instead this uses a custom interactor.
> STCOM-785: Button interactor

- doc/interactors.md
- interactors/keyboard.js
- interactors/tooltip.js
This fixes the tooltip interactor which was in-flight. The main thing that I did was to continue to rely on the `data-test-proximity-tooltip-element` attribute for the interactor which seemed very reasonable given that there is very little else to identify that element.... So you would use it like:
```javascript
await Tooltip("save document").is({ visible: true });
await Tooltip("save document, { proximity: true }).exists();
```
It's unlikely that anybody would use the proximity filter in anything but the stripes-components test suite.
> STCOM-785 ✨New tooltip interactor

- Dockerfile
`wget --no-check-certificate` disables certificate checks and makes the
installation vulnerable to Man-in-the-middle attacks that might install
malware.
No longer use `--no-check-certificate`.
Make sure that the package ca-certificates is installed. wget needs it
to check certificates.
> FOLIO-2923: Drop --no-check-certificate from wget (MitM attack)

- doc/interactors.md
- interactors/icon-button.js
- interactors/index.js
- interactors/text-field.js
Upgrade the `TextField` interactor to the new bigtest interactor syntax, and make it available for consumption by the test suite.
Added a `TextField` interactor, with filters and actions that cover the common ways of interacting with a text field.
See this in action here: https://github.com/folio-org/stripes-components/pull/1468
> STCOM-785: interactors update: text-field

- doc/interactors.md
- interactors/icon-button.js
The original implementation was added here: https://github.com/folio-org/stripes-testing/pull/81
Now that we have a documentation format it's time to backfill some docs.
> STCOM-785: docs for new interactors for button and icon button

- doc/interactors.md
- interactors/button.js
- interactors/dropdown.js
- interactors/index.js
Upgrade the `Dropdown` interactor to the new bigtest interactor syntax, and make it available for consumption by the test suite.
Added a `Dropdown` interactor, with filters and actions that cover the common ways of interacting with a text field.
See this in action here: https://github.com/folio-org/stripes-components/pull/1473
> STCOM-785: interactors update: dropdown

- doc/interactors.md
- interactors/index.js
- interactors/textarea.js
Upgrade the `TextArea` interactor to the new bigtest interactor syntax, and make it available for consumption by the test suite.
Added a `TextArea` interactor, with filters and actions that cover the common ways of interacting with a text field.
See this in action here: https://github.com/folio-org/stripes-components/pull/1470
> STCOM-785: interactors update: textarea

- doc/interactors.md
- interactors/index.js
- interactors/search-field.js
Upgrade the `SearchField` interactor to the new bigtest interactor syntax. Make it available for usage in the test suite.
Added a `SearchField` interactor, with filters and actions for interacting with a search-field.
See this in action here:
> STCOM-785: interactors update: searchField

- doc/interactors.md
- interactors/datepicker.js
- interactors/html.js
- interactors/index.js
- interactors/keyboard.js
- package.json
** note opening a new PR from #97 as it was closed in the merge process **
Upgrade the Datepicker and Calendar interactor to the new bigtest interactor syntax. Make it available for usage in the test suite.
Added a Datepicker and Calendar interactor, with filters and actions for interacting with both the datepicker input field and the calendar widget.
The related `stripes-components` PR will not be opened until this one has been merged in. The related code can be seen [here](https://github.com/jbolda/stripes-components/commit/98583a519e01b65f59267426e828e029ebf62e21) until it is opened.
> STCOM-785: interactors update: Datepicker

- cypress/support/index.js
- doc/differences-in-stripes-components-testing.md
- interactors/accordion.js
- interactors/baseHTML.js
- interactors/checkbox.js
- interactors/datepicker.js
- interactors/index.js
- interactors/key-value.js
- interactors/keyboard.js
- interactors/layer.js
- interactors/list.js
- interactors/multi-column-list.js
- interactors/multi-select.js
- interactors/radio-button.js
- interactors/rich-text-editor.js
- interactors/search-field.js
- interactors/select.js
- interactors/text-field.js
- interactors/textarea.js
- interactors/tooltip.js
- package.json
Interactors are independently useful outside of BigTest and can be used in many different contexts including both Jest and Cypress, so after observing how they were being used in the wild, it didn’t make sense to keep it coupled to BigTest development.
As an independent project, the documentation, APIs, and community can evolve independently without any artificial limits.
The `@bigtest/interactor` and `@bigtest/cypress` projects have been moved in separate monorepo https://github.com/thefrontside/interactors and related packages had been deprecated. I updated dependencies to use actual packages `@interactors/html` and `@interactors/with-cypress` instead.
> Upgrade `@bigtest/interactor` package to `@interactors/html`

- package.json
There was an issue https://github.com/thefrontside/interactors/issues/92 where sometimes interactors try to find elements from the incorrect document root. We change logic how to work resolving the document element in a more consistent way.
> update interactors and with-cypress packages

- CHANGELOG.md
- interactors/index.js
- Export `dispatchFocusout` from `util` so that other Interactors can make use of it. Refs [STSMACOM-541](https://issues.folio.org/browse/STSMACOM-541).
> Export dispatchFocusout from util

- CHANGELOG.md
- cypress/integration/notes/notes.spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- package.json
Setup `cypress-grep` plugin. It gives the ability to filter and run tests by tags, name, etc.
https://github.com/cypress-io/cypress-grep
[FAT-1090](https://issues.folio.org/browse/FAT-1090)
> FAT-1090: Setup cypress-grep plugin

- CHANGELOG.md
- interactors/advanced-search.js
- interactors/index.js
- interactors/select.js
Adding interactor for new `<AdvancedSearch>` component
[UITEST-89](https://issues.folio.org/browse/UITEST-89)
https://github.com/folio-org/stripes-components/pull/1706
https://github.com/folio-org/ui-marc-authorities/pull/57
> UITEST-89 Added AdvancedSearch interactor

- CHANGELOG.md
- interactors/advanced-search.js
`<Select>` doesn't add `aria-label` attribute to `select` html element. We need to use `id` attribute instead to find the component
[UITEST-93](https://issues.folio.org/browse/UITEST-93)
> UITEST-93: Fix AdvancedSearch search option select interactor

- cypress/integration/inventory/create-fast-add-record.spec.js
- cypress/support/fragments/inventory/inventoryActions.js
- Small change to roll back to old version of `open()` method in `inventoryActions` not break other tests.
> FAT-823-FIX: Roll back to old open() in inventoryActions

- interactors/multi-column-list.js
Tests here have been migrated to use the 'content' filter rather than incorrectly using 'column' - this change is the second part of UITEST-78 actually makes 'column' work the way that it should. This is a refresh of https://github.com/folio-org/stripes-testing/pull/439 .
> UITEST-78 fix MCL Interactor 'column' filter

- interactors/datepicker.js
https://github.com/folio-org/stripes-testing/pull/715 may be too harsh a reversion since it removes the added tests. This PR only removes the extended selector for the Datepicker interactor.
> Remove extra selector from datepicker interactor

- package.json
This should have been done as soon as 4.5.0, e970c50f1d8c226d8073788f91a6a4d89fb4bdc5, was tagged so all new tests and new features were merged onto the next version.
> bump minor for new development work

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
In CI, bumpt NodeJS from v16 to v18.
Refs [UITEST-109](https://issues.folio.org/browse/UITEST-109)
> UITEST-109 use NodeJS v18 in CI

- cypress/e2e/permissions/permissions-not-present-in-settings.cy.js
- [FAT-8201](https://issues.folio.org/browse/FAT-8201)
- [Settings (Users): Can view transfer criteria" and  "Settings (Users): Can create, edit and remove transfer criteria" permissions are not present in Settings](https://foliotest.testrail.io/index.php?/cases/view/407705)
- [Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4407/allure/#packages/f1a8b9a2b3eef82f9344c2423e8f99dd/9c065c0199371ee4/)
> FAT-8201/C407705

- cypress/e2e/users/edit-users.cy.js
- cypress/support/fragments/users/userEdit.js
- [FAT-8202](https://issues.folio.org/browse/FAT-8202)
- ["User search results" pane results remain after canceling user's profile editing](https://foliotest.testrail.io/index.php?/cases/view/407662)
- [Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4403/allure/#suites/60aef4739493073e65c5d706506f5371/6d02b41e9f622bfb/)
> FAT-8202/C407662

- interactors/multi-column-list.js
[Changes to MCL in stripes components changed mark-up](https://github.com/folio-org/stripes-components/pull/2125). Typically, filters from interactors would need to be adjusted up front, but in this case problematic filters were not being used by tests in stripes-components, so the typical flow of usage/updates didn't run into issues. 
I have a PR for stripes-components to add tests that make use of the filters, and I've pointed it at this branch: https://github.com/folio-org/stripes-components/pull/2129
> UITEST-110 Update interactors for changes to MCL markup

- cypress/e2e/data-import/permissions/can-view-acquisition-methods-in-order-field-mapping.cy.js
- cypress/support/constants.js
- cypress/support/fragments/data_import/mapping_profiles/newFieldMappingProfile.js
[C377031](https://foliotest.testrail.io/index.php?/cases/view/377031 )
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4507/allure/)
> C377031 A user can view Acquisition Methods in Order field mapping with "Settings (Data import): Can view, create, edit, and remove" (folijet) (TaaS)

- cypress/e2e/inventory/holdings/verify-missing-holding-source-is-not-populated-in-the-ui.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
https://foliotest.testrail.io/index.php?/cases/view/367931
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4807/allure/#suites
> C367931 Verify that missing holdings' source is not populated in the UI with instance's source (Firebird)

- cypress/e2e/orders/holdings-records creation-for-order-with-electronic-resource-format.cy.js
- cypress/support/fragments/orders/basicOrderLine.js
[C402353](https://foliotest.testrail.io/index.php?/cases/view/402353)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4911/allure)
***
> [402353] Holdings records creation when open order Electronic resource (thunderjet) (TaaS)

- cypress/e2e/orders/holdings-records creation-for-order-with-other-format.cy.js
[C402354](https://foliotest.testrail.io/index.php?/cases/view/402354)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4930/allure)
***
> [402354] Holdings records creation when open order with "Other" (thunderjet) (TaaS)

- cypress/e2e/orders/holdings-records creation-for-order-with-pe-mix-format-eresource-none.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
[C402351](https://foliotest.testrail.io/index.php?/cases/view/402351)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4932/allure)
***
> [402351] Holdings records creation when open order with "P/E mix" (thunderjet) (TaaS)

- cypress/e2e/orders/open-order-when-ledger-has-separate-aq-unit.cy.js
- cypress/support/fragments/orders/orderLineDetails.js
- cypress/support/fragments/orders/orderLineEditForm.js
- cypress/support/fragments/settings/acquisitionUnits/acquisitionUnits.js
[C407655](https://foliotest.testrail.io/index.php?/cases/view/407655)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4956/allure)
***
> [407655] Open order when ledger has separate acquisition unit (thunderjet) (TaaS)

- cypress/e2e/finance/fiscalYears/utc-is-displayed-when-create-or-view-fiscal-year.cy.js
- cypress/support/fragments/finance/fiscalYears/fiscalYears.js
***
[C380514](https://foliotest.testrail.io/index.php?/cases/view/380514)
***
> C380514: "UTC" is displayed in "Period begin date" and "Period end date" fields when create or view fiscal year (Orchid +) (thunderjet) (TaaS)

- cypress/e2e/settings/tenant/remote-storage.cy.js
[C163925](https://foliotest.testrail.io/index.php?/cases/view/163925)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5072/allure)
> C163925 View remote storage details in settings > tenant > location (firebird) (TaaS)

- cypress/e2e/marc-authority/create-new-marc-bib-check-pane.cy.js
- cypress/support/fragments/quickMarcEditor.js
[testRail](https://foliotest.testrail.io/index.php?/cases/view/380427)
[AllureReport](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5079/allure)
> C380427 A new MARC bib record is opened in QuickMARC UI (spitfire) (TaaS)

- cypress/e2e/orders/electronic-format-fields-cleared-when-change-format-to-physical.cy.js
- cypress/support/fragments/orders/orderLineDetails.js
- cypress/support/fragments/orders/orderLineEditForm.js
[C354281](https://foliotest.testrail.io/index.php?/cases/view/354281)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5188/allure)
***
> [354281] “Electronic” format fields cleared when changing order format (thunderjet) (TaaS)

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-without-uri.cy.js
https://foliotest.testrail.io/index.php?/cases/view/409429
> C409429 Verify Bulk Edit for Holdings without populated "URI" in electronic access (firebird) (TaaS)'

- cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-email-fields.cy.js
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
https://foliotest.testrail.io/index.php?/cases/view/360537
> C360537 Verify that the "Confirm changes" button is disabled until all fields are filled in Email update (firebird) (TaaS)

- cypress/e2e/orders/encumbered-amount-is-not-changed-after-deleting-received-piece-with-paid-invoice.cy.js
[C375111](https://foliotest.testrail.io/index.php?/cases/view/375111)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5719/allure)
***
> C375111: Encumbered amount is not changed after deleting received piece when related paid invoice exists (thunderjet) (TaaS)

- cypress/e2e/orders/edit-pol-renewal-note.cy.js
- cypress/support/fragments/orders/orderLineEditForm.js
[C353968](https://foliotest.testrail.io/index.php?/cases/view/353968)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5754/allure)
***
> [353968] User can edit 'Renewal note' field on POL (thunderjet) (TaaS)

- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-add-multiple-999.cy.js
[TestRail](https://foliotest.testrail.io/index.php?/cases/view/380716)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5761/allure/)
> C380716 Add multiple 999s when creating MARC Bibliographic record (spitfire) (TaaS)

- cypress/e2e/fee-fine/cancel-fee-fine.cy.js
- cypress/support/fragments/users/cancelFeeFaine.js
- cypress/support/fragments/users/payFeeFaine.js
- cypress/support/fragments/users/refundFeeFine.js
- cypress/support/fragments/users/userAllFeesFines.js
[C356793](https://foliotest.testrail.io/index.php?/cases/view/356793)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5810/allure)
> C356793 Verify that library staff can cancel a fee/fine as an error for a patron if fee/fine has been fully paid and then fully refunded (vega) (TaaS)

- cypress/e2e/fee-fine/claimed-returned-fee-fine-behavior-when-item-checked-out.cy.js
[C367982](https://foliotest.testrail.io/index.php?/cases/view/367982)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5825)
> C367982 Check that "Confirm" button on "Confirm item status: Claimed returned" modal became disabled after clicking on it (vega) (TaaS)

- cypress/e2e/title-level-request/check-that-user-can-not-see-actions-button-in-the-request-detail.cy.js
- cypress/support/fragments/requests/requests.js
[C350530](https://foliotest.testrail.io/index.php?/cases/view/350530)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5875/allure)
> C350530 Check that user can not see Actions button in the Request detail if all request closed and Title level request option closed (vega) (TaaS)

- cypress/e2e/title-level-request/user-can-move-request-if-title-and-item-request-were-created.cy.js
- cypress/support/fragments/requests/move-request.js
[C350521](https://foliotest.testrail.io/index.php?/cases/view/350521)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5915/allure/)
> C350521 Check that user can move request if Title and Item requests were previously created (vega) (TaaS)

- cypress/e2e/title-level-request/user-can-move-request-if-title-and-item-request-were-created.cy.js
- cypress/support/fragments/requests/requests.js
[C350427](https://foliotest.testrail.io/index.php?/cases/view/350427)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6173/allure/)
> C350427 Check that the request has disappeared from the queue after changing the "Close-Cancelled" status (vega) (TaaS)

- cypress/e2e/data-import/settings/check-asterisk-in-existing-mapping-profile.cy.js
- cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfiles.js
[TestRail](https://foliotest.testrail.io/index.php?/cases/view/367955)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6329/allure/)
> C367955 Order field mapping profile: Check asterisks for required fields in existing field mapping profile (folijet) (TaaS)

- cypress/e2e/settings/data-import/check-contributor-type-mappings.cy.js
- cypress/e2e/settings/data-import/check-provider-fields-can-be-manually-updated.cy.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileView.js
[C378896](https://foliotest.testrail.io/index.php?/cases/view/378896)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6409/allure)
***
> [378896] Provider fields can be manually cleared/edited (folijet) (TaaS)

- cypress/e2e/data-import/settings/verify-material-type-inactive-in-open-order.cy.js
- cypress/support/fragments/data_import/mapping_profiles/newFieldMappingProfile.js
[TestRail - C380560](https://foliotest.testrail.io/index.php?/cases/view/380560)
[TestRail - C380561](https://foliotest.testrail.io/index.php?/cases/view/380561)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6354/allure/#suites)
> C380560-C380561 Order field mapping profile: Material type field is inactive when Order status is Open (folijet) (TaaS)

- cypress/e2e/data-import/settings/verify-default-action-profile.cy.js
- cypress/support/fragments/data_import/job_profiles/jobProfileView.js
[TestRail](https://foliotest.testrail.io/index.php?/cases/view/422235)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6328/allure/)
> C422235 Verify that Default Create Instance action profile does NOT link to the wrong job profile (folijet) (TaaS)

- cypress/e2e/consortia/switch-active-affiliation-option-is-not-displayed.cy.js
- cypress/support/fragments/settings/consortium-manager/consortium-manager.js
[C388499](https://foliotest.testrail.io/index.php?/cases/view/388499)
> Implementing of FAT-10199

- cypress/e2e/checkin/check-in-in-house-use.cy.js
[C9198](https://foliotest.testrail.io/index.php?/cases/view/9198)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6528/allure)
> C9198 Check In: in-house use icon (vega) (TaaS)

- cypress/e2e/consortia/orders/shared-instance-can-be-created-linked-instance-when-pol-is-connected.cy.js
- cypress/support/fragments/inventory/inventoryInstance.js
***
https://issues.folio.org/browse/FAT-10862
***
https://foliotest.testrail.io/index.php?/cases/view/411665
***
***
> Implementing of FAT-10862

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-classification-identifier-types/user-with-permission-is-able-add-edit-classification-identifier-type.cy.js
[FAT-11009](https://folio-org.atlassian.net/browse/FAT-11009)
***
[User with "Consortium manager: Can share settings to all members" permission is able to add/edit classification identifier type shared to all affiliated tenants in "Consortium manager" app](https://foliotest.testrail.io/index.php?/cases/view/410901)
> FAT-11009/C410901

- cypress/e2e/consortia/consortium-manager/manage-shared-settings/manage-shared-instance-note-types/user-with-permission-is-able-add-edit-instance-note-types.cy.js
[FAT-11013](https://folio-org.atlassian.net/browse/FAT-11013)
***
[User with "Consortium manager: Can share settings to all members" permission is able to add/edit instance note type shared to all affiliated tenants in "Consortium manager" app
](https://foliotest.testrail.io/index.php?/cases/view/410932)
***
> FAT-11013/C410932

- cypress/e2e/inventory/search/browse-subjects-linked.cy.js
- cypress/e2e/marc/marc-hodings/create-new-marc-holdings.cy.js
Minor fixes for two test suites:
- using `openHoldingViewByID` method instead of a default one for test to not fail when multiple holdings found
- updated source view subfield marker symbol
> Spitfire Poppy minor fixes

- cypress/e2e/invoices/FY-appears-after-fund-distribution-change-when-FY-was-undefined.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-created-in-current-FY-for-previous-FY-order.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-created-in-current-FY-for-previous-FYwhen-POL-created-in-previous-FY.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-in-current-FY-for-previous-FY.cy.js
- cypress/e2e/invoices/approve-and-pay-invoice-with-currency-different-from-default.cy.js
- cypress/e2e/invoices/approve-invoice-in-previous-FY-and-pay-invoice-in-current FY.cy.js
- cypress/e2e/invoices/invoice-with-fund-different-from-related-pol-can-be-approved.cy.js
- cypress/e2e/invoices/save-invoice-FY-after-fund-change.cy.js
- cypress/e2e/invoices/save-invoice-fiscal-year-after-fund-distribution-change.cy.js
- cypress/e2e/invoices/save-invoise-fiscal-year-after-adding-adjustment.cy.js
- cypress/e2e/invoices/update-exchange-rates-on-invoice-lines-with-multiple-funds.cy.js
- cypress/e2e/invoices/user-is-not-able-to-pay-previously-approved-invoice.cy.js
- cypress/e2e/orders/close-order.cy.js
- cypress/e2e/orders/create-one-time-order-with-pol.cy.js
- cypress/e2e/orders/create-order-withPol-different-formats.cy.js
- cypress/e2e/orders/po-search.cy.js
- cypress/e2e/orders/pol-search.cy.js
- cypress/support/fragments/orders/orderLines.js
Fix Thunderjet tests for eureka:
- Add cy.getAdminToken() to tests,
- Find the method OrderLines.POLWithDifferntCurrency() and restore it, because during test C378881 run get the error: 
"TypeError: _orderLines.default.POLWithDifferntCurrency is not a function"
- Add the method Orders.updateOrderViaApi to the precondition to the test C380406 in order to make order status 'Open'. Because in the step where Invoice need to be approved we see a message "Invoice can not be approved. One or more of the related orders has a workflow status of "Pending". If desired, please open the related orders before approving this invoice."
> FAT-12856 Fix Thunderjet tests for eureka

- cypress/e2e/fse/api/agreements.cy.js
- cypress/e2e/fse/api/eholdings.cy.js
- cypress/e2e/fse/api/finance.cy.js
- cypress/support/api/agreements.js
- cypress/support/api/eholdings.js
- cypress/support/api/index.js
[US1261930](https://rally1.rallydev.com/#/21934224700d/myrally?detail=%2Fuserstory%2F780099813575), [US1261920](https://rally1.rallydev.com/#/605272773808d/teamboard?detail=%2Fuserstory%2F780089899749&view=aa30dbe3-2c38-45ee-9267-15de1c227ecb):
3 tests added for FSE AQA suite - re-creation of 3 existing synthetic canaries checks:
- agreements (get by status)
- finance (get fiscal year)
- eholdings (get by title)
See related rally ticket for details and test cases.
For existing synthetic canaries, [check this repo.](https://github.com/EBSCOIS/fse.hosting.aws-synthetics/tree/master)
> US1261930: 3 tests added for FSE sanity AQA suite

- cypress/e2e/eureka/authorization-roles/edit-role-only-name-description.cy.js
- cypress/e2e/eureka/authorization-roles/view-edit-role.cy.js
- cypress/e2e/eureka/users/assigning-roles-user-edit.cy.js
- cypress/e2e/eureka/users/unassigning-roles-user-edit.cy.js
- cypress/support/fragments/settings/authorization-roles/authorizationRoles.js
Updated tests according to UIROLES-46:
- C424003: updated login to open role directly
- C424001: added steps to check URL in role detailed view
- C466114: updated visit steps to open role directly
Results:
> FAT-13899: tests updated

- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-folio-authority-file.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-auth-file-with-default-prefix.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-record-with-local-authority-file.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-new-marcAuth-without-folio-authority-file.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/create-record-with-different-prefix-in-010-field.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/created-marcAuth-could-be-found-using-search-and-browse.cy.js
- cypress/e2e/marc/marc-authority/create-marc-authority/verify-005-and-999-fields-system-generated.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/manual-linking/link-marcBib-with-created-on-ui-marcAuth.cy.js
- cypress/support/fragments/marcAuthority/marcAuthority.js
Implement a new method addNewFieldAfterExistingByTag(). This method adds a new field to the MARC authority record without relying on a hardcoded row index. Replace with it the existing addNewField() method.
> FAT-14422 Support automated tests in daily run

- cypress/e2e/aaa.cy.js
Added `skip` to the test suite for MARC specification sync.
Such synchronization is now done automatically when the env is built (https://folio-org.atlassian.net/browse/MRSPECS-53).
If this change will not cause any issues, corresponding spec file could be later removed completely.
> skipping validation sync

- cypress/e2e/inventory/settings/instance-date-types/date-type-cannot-update-certain-fields-api.cy.js
- cypress/e2e/inventory/settings/instance-date-types/update-instance-date-type-name-api.cy.js
- cypress/support/api/inventory.js
- cypress/support/dictionary/permissions.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-16627
Test case - https://foliotest.testrail.io/index.php?/cases/view/506695
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7477/allure
- - - - 
Also updated C506694 to work with user having proper permissions
> FAT-16627-C506695

- CHANGELOG.md
- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
- cypress/support/fragments/check-in-actions/checkInPane.js
- cypress/support/fragments/circulation-log/searchPane.js
- cypress/support/fragments/circulation-log/searchResults.js
- cypress/support/fragments/circulation/editStaffClips.js
- cypress/support/fragments/consortium-manager/modal/confirm-create.js
- cypress/support/fragments/consortium-manager/modal/confirm-share.js
- cypress/support/fragments/consortium-manager/modal/delete-cancel-reason.js
- cypress/support/fragments/data-export/dataExportResults.js
- cypress/support/fragments/data-export/exportJobProfile/exportJobProfiles.js
- cypress/support/fragments/data-export/exportMappingProfile/exportFieldMappingProfiles.js
- cypress/support/fragments/data-export/exportMappingProfile/singleFieldMappingProfilePane.js
- cypress/support/fragments/data_import/matchOnVRN.js
- cypress/support/fragments/inventory/holdings/inventoryHoldings.js
- cypress/support/fragments/inventory/search/browseSubjects.js
- cypress/support/fragments/loans/loansPage.js
- cypress/support/fragments/oai-pmh/general.js
- cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileView.js
- cypress/support/fragments/settings/dataImport/matchProfiles/newMatchProfile.js
- cypress/support/fragments/settings/inventory/instance-holdings-item/urlRelationship.js
- cypress/support/fragments/settings/users/customFields.js
- cypress/support/fragments/settings/users/paymentMethods.js
- cypress/support/fragments/settings/users/waiveReasons.js
- cypress/support/fragments/users/feeFines.js
- cypress/support/fragments/users/loans/userLoans.js
- cypress/support/fragments/users/userCharge.js
- package.json
Just like it says on the tin: migrate imports from `bigtest`, which contains many unmaintained dependencies (e.g. old versions of `minimist` vulnerable to CVE-2021-44906), to imports from `@interactors/html` which is maintained.
Refs [UITEST-120](https://folio-org.atlassian.net/browse/UITEST-120)
> UITEST-120 migrate imports from "bigtest" to "@interactors/html"

- cypress/e2e/eureka/authorization-roles/create-role-add-app.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-no-capabilities-or-sets.cy.js
- cypress/e2e/eureka/authorization-roles/create-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-add-app.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-only-capabilities.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps-sets.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-selecting-apps.cy.js
- cypress/e2e/eureka/authorization-roles/edit-role-unassign-button-select-apps.cy.js
- cypress/e2e/eureka/users/assigning-roles-user-edit-without-keycloak.cy.js
FAT ticket - https://folio-org.atlassian.net/browse/FAT-17148
Test case - https://foliotest.testrail.io/index.php?/cases/view/499897
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/7626/allure
> FAT-17148-C499897

- CHANGELOG.md
- cypress/support/dictionary/permissions.js
Update `ui-quick-marc.quick-marc-editor.duplicate` and `ui-quick-marc.quick-marc-authority-records.linkUnlink` permissions to match https://github.com/folio-org/ui-quick-marc/pull/751
https://folio-org.atlassian.net/browse/UITEST-125
> UITEST-125: Update `ui-quick-marc.quick-marc-editor.duplicate` and `ui-quick-marc.quick-marc-authority-records.linkUnlink` permissions.

- CHANGELOG.md
- interactors/advanced-search.js
Advanced search uses `ariaLabel` to find the input box. If the label is changed, it also requires changing the `stripes-testing` module each time. The solution is to rely only on `dataTestID`, which should be persistent.
[UITEST-127](https://folio-org.atlassian.net/browse/UITEST-127)
> UITEST-127: Change `advanced-search` -> `fillQuery` interactor from `ariaLabel` to `dataTestID`.

- cypress/support/fragments/bulk-edit/bulk-edit-actions.js
Rename download preview button according to the story [https://folio-org.atlassian.net/browse/UIBULKED-568](https://folio-org.atlassian.net/browse/UIBULKED-568)
> FAT-17417 Support automated tests

- cypress/e2e/eureka/consortia/consortium-manager/share-role-edit-central.cy.js
In test C523609, a workaround for the following issue is removed as the issue is now fixed and tested:
https://folio-org.atlassian.net/browse/UISAUTHCOM-51
> C523609: workaround removed

- cypress/e2e/marc/marc-authority/advanced-search/marc-authority-advanced-search-not-splitting.cy.js
- cypress/e2e/marc/marc-authority/verify-subject-option-uses-all-search-operator.cy.js
- cypress/e2e/marc/marc-bibliographic/derive-marc-bib/automated-linking/derive-marc-bib-automated-linking-except-already-linked-fields.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField110-to-authority110-with-record.cy.js
- cypress/e2e/marc/marc-bibliographic/edit-marc-bib/manual-linking/linking-bibField111-to-authority111-with-record.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-browse/plug-in-marc-authority-browse-by-corporate.cy.js
- cypress/e2e/marc/plug-in-marc-authority/plug-in-marc-authority-browse/plug-in-marc-authority-browse-by-personal-name.cy.js
Double hyphens before marc authority subfield values are not expected on Snapshot/Cypress envs, while double hyphens for MARC instance subject subfields are still expected.
Reviewed/updated tests with "--" in test data strings:
C405513 - no changes
C356824 - no changes
C375259 - no changes
C466296 - no changes
C627240 - no changes
C584450 - removed hyphens
C466217 - removed hyphens
C388641 - minor fix, no hyphen changes
C374194 - removed string (not used)
C374197 - removed string (not used)
C375070 - no changes
C380552 - removed hyphens
C380551 - removed hyphens
Verified no issues caused by these updates.
> Spitfire double hyphen updates

- cypress/e2e/consortia/marc/marc-bibliographic/create-new-marcBib/create-local-marc-bib-in-member.cy.js
- cypress/e2e/consortia/marc/marc-bibliographic/create-new-marcBib/create-shared-marc-bib-in-central.cy.js
- cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-check-pane.cy.js
- cypress/e2e/marc/marc-holdings/create-new-marc-holdings.cy.js
- cypress/support/fragments/quickMarcEditor.js
https://folio-org.atlassian.net/browse/FAT-20132
Label of create pane in "quickmarc" was updated.
Allure reports:
Non-ECS:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8300/allure/#suites/a64df16dd423bcf8901a28ccfb6cab2d/cd8f5d15bf793e1b/
ESC:
https://jenkins.ci.folio.org/job/folioTestingTools/job/runCypressTests/8306/allure/#suites
> FAT-20132 - update pane header label of create quickmarc pane

- CHANGELOG.md
- cypress/support/fragments/users/usersCard.js
This is a fix for the https://jenkins.ci.folio.org/job/folioScheduledTesting/job/folioQualityGates/1659/allure/#suites/cd1af563c364c83f0cb7307ff326d221/211c29e7693e70a4/
Test C11020 failed due to recent changes in the patron block message banner:
https://folio-org.atlassian.net/browse/UIU-3120 
https://folio-org.atlassian.net/browse/UIU-3394 
Use `MessageBanner` stripes component for user patron blocks warning. Update its message.
https://folio-org.atlassian.net/browse/UITEST-136
> UITEST-136: Use `MessageBanner` stripes component for user patron blocks warning. Update its message.

- cypress/support/fragments/eholdings/eHoldingsTitle.js
Fix C16994. Okapi request was being sent with an extra slash in the path. The issue was that `cy.okapiRequest` adds a slash between hostname and pathname, but `changePackageStatusViaApi` also included a slash in the pathname, resulting in two slashes
> C16994 fix double slash on okapi request

- cypress/e2e/settings/users/owners-service-points-association.cy.js
Settings -> Users -> Owners: If "Circ Desk 2" is already selected, it will not be available in the other rows' dropdown, so we need to use a unique service point that no one else has used.
> FAT-21841-C503131-fix

- cypress/e2e/staff-slips/metadata-accordion-unknown-user-deleted.cy.js
It looks like the user is not being deleted, since "Source: Unknown user" is not displayed in the [screenshot](https://report-portal.ci.folio.org/ui/#cypress-nightly/launches/all/7960/2421049/2421068/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%26filter.cnt.name%3Dvolaris%26page.page%3D1). Let's check the status and throw an error if the user hasn't been deleted to better understand the cause of the test instability. The test fails in the env but not locally.
> FAT-21830: C387438 add log to check if user is deleted

- cypress/support/fragments/settings/tenant/locations/createLocations.js
The C163922 sometimes fails because the new location is saved without the selected remote storage. Remote storage field waits for a GET request and only then contains options. Wait for the option to be available, select it and only then do the rest.
Fixes https://report-portal.ci.folio.org/ui/#cypress-nightly/launches/all/7960/2426043/2426051/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%26filter.cnt.name%3Dvolaris%26page.page%3D1
> FAT-21830-C163922-fix
