folio-org/stripes-testing

package.json
test-module.js

Only one import reordering needed.

Use eslint-config-stripes 3.2.1

---

xnightmare.js

Added a new `.input(selector, stringToType)` action. It's basically like `.type()`, but doesn't `blur` the field after the text is entered. This is useful for components like `AutoSuggest` that hide their dropdown and make it unavailable for Nightmare when they receive a blur event.

Nightmare: Added new 'input' action

---

helpers.js

pause on request

---

helpers.js

replace organization with tenant-settings

---

CHANGELOG.md
helpers.js

New helpers for common actions.

add checkout, setCirculationRules helpers

---

helpers.js

Returning a value from a Promise isn't that hard if you know what you're
doing, but I had no idea what I was doing. The light went on while I was
doing the dishes. Maybe I should spend more time washing the dishes.
Refs [UITEST-67](https://issues.folio.org/browse/UITEST-67)

UITEST-67 fix setCirculationRules

---

helpers.js

Sometimes, creating a new inventory item record would fail. Why?
Couldn't say. It seems like nightmare was executing things out of order,
like it was clicking submit before selecting a material type. The
symptom was that we'd see electron hanging out with a validation error
that no material-type was selected when, clearly, a material-type was
selected. This made no sense. Logging to the console would show a
`selectedIndex` of 0 when clearly it was not.
Why? I got nothin'. Sometimes Nightmare just gets it's knickers in a
twist.
Refs [UIIN-671](https://issues.folio.org/browse/UIIN-678)

UIIN-671 reorganize new-item handler

---

helpers.js

How do I loathe thee? Let me count they ways.
I loathe thee to the depth and breadth and height
Windows can reach, when render'd out of sight
Whether pixelated or by rays, trace'd.
I loathe thee to the level of every test's
Most quiet need: to PASS on every night
I loathe thee when I click an `<option>`, right?
Then click `submit` and lay my form to ReST
And find no `blur` event is ever fired
So validation never comes to pass
Three days, I lost, and nights, red eyes, I tired.
John called: "Set A, then B! It works! At last!
That blurs select and gets you out' the mire!"
'Twas he smashed the bug, but I'll kick your ass.
Alternatively, instead of interacting with a non-select element immediately after every select element in order to make sure its blur handlers fire, @JohnC-80 figured out …

UIIN-671 fix new-item integration helper

---

helpers.js

The add-item portion of the `createInventory` helper has always been
difficult, but after the conversion of ui-inventory from redux-form to
final-form it stopped working altogether. This appears to be related to
the onBlur validation handler and its odd interaction with select
elements.
In many different situations, I've observed that Nightmare seems to lose
track of its browser instance and get lost in an add neverneverland of
parallel execution. I can't quite explain it. But that appeared to be
what was happening here: after interacting with select elements,
validation wouldn't fire consistently for them, and validation of the
barcode field (with async validation) was flaky too.
Adding interaction with other fields seems to mitigate the flakiness. I
can't explain exactly how, but it …

fix add-item instance helper

---

helpers.js

The new-item tests continues to be unreliable. These changes attempt to improve reliability.

tweak new-item test and pray

---

helpers.js

Bring some consistency to finding a barcode for an active user.

UIU-897 add findActiveUserBarcode function

---

helpers.js

* `createNInventory` creates N item records under a single
instance and holdings record and returns an array of the item-records'
barcodes.
* `checkoutList` checks out an array of barcodes to a user

create and checkout many things

---

helpers.js

The nav-bar IDs are going away and will be replaced by what had
been the nav-menu IDs.
Refs [STCOR-377](https://issues.folio.org/browse/STCOR-377)

STCOR-377 test tweaks

---

helpers.js

Provide helpers for add/remove over due fine policies, lost item fee
policies, and patron notice policies.
Refs [FOLIO-2440](https://issues.folio.org/browse/FOLIO-2440)

FOLIO-2440 add policy helpers

---

.eslintrc
package.json

Ignoring new rules that don't make sense in stripes-testing context.

Upgrading eslint to 6.2.1

---

helpers.js

Use a more semantic selector for retrieving user data.
MCL DOM internals changed in folio-org/stripes-components/pull/1205.

UICHKOUT-602 more semantic user selector

---

helpers.js

Lots has changed even though functionality is basically the same.
* converting from redux-form to final-form means we sometimes have to
wait a second for a form to settle after it loads. This sucks. It really
really really sucks, but so far we have not been able to find a way
around it. @doytch even filed a bug for it, but it's gotten no traction.
* renamed some button `id` values, because that's always a fun game.
* moved fixed-due-date-schedule handling out of platform-core's test and
into a helper here.
* checkout multiple items with array-reduce rather than iteration in
order to handle the promises sequentially rather than in parallel.

clean up for stripes v5, final-form, etc

---

interactors/index.js
interactors/radio-button.js

This adds a new `RadioButton` Interactor which is coupled with and required in folio-org/stripes-components#1453.
/cc @JohnC-80

STCOM-785: interactors update - radio button

---

doc/interactors.md
interactors/select.js

This finishes the select interactor which is based on the native `@bigtest/interactor`

STCOM-785 ✨Complete Select Interactor

---

doc/interactors.md

The original implementation is in #78 and #79. Now that we have a defined process for docs, time to add them.

STCOM-785: docs for new interactors for checkbox and radio button

---

doc/interactors.md

Get straight to the good stuff

Link to the interactor guide itself and not the landing page

---

package.json

See https://github.com/thefrontside/bigtest/pull/869

fix for interactors not working in JSDOM

---

package.json

Reverts folio-org/stripes-testing#106

Revert " FOLIO-2946 bump version v4"

---

package.json

Reverts folio-org/stripes-testing#107

FOLIO-2946 bump version v4

---

.eslintrc
.gitignore
cypress.json
cypress/fixtures/example.json
cypress/integration/checkin/checkin.basic.spec.js
cypress/integration/checkout/checkout.basic.spec.js
cypress/plugins/index.js
cypress/support/api/auth.js
cypress/support/api/circulation.js
cypress/support/api/index.js
cypress/support/api/inventory.js
cypress/support/api/users.js
cypress/support/checkin.js
cypress/support/checkout.js
cypress/support/index.js
cypress/support/login.js
cypress/support/stripes.js
interactors/dropdown.js
interactors/index.js
interactors/modal.js
package.json

Reverts folio-org/stripes-testing#108

FOLIO-2946 initialize cypress tests

---

cypress/integration/eholdings/notes.spec.js
cypress/integration/eholdings/provider-edit.spec.js
cypress/integration/eholdings/provider-search.spec.js
cypress/integration/inventory/quick-marc.spec.js
cypress/support/eholdings.js
cypress/support/index.js
cypress/support/inventory.js
cypress/support/login.js
package.json

Add Cypress tests for following cases:
- quickMARC
- Derive a new MARC bib record
- Add a new MARC tag that it adds a default $a
- Editing a 006/00 value
- eHoldings
- Edit Provider record (proxy)
- Searching Providers
- Notes
- Create a note
- Edit a note
- View a note
- Assign/Unassign a note
- Is there a way to wait for an element to appear? Using constant timeouts doesn't seem to be the right way to do this.

FAT-899: Spike: learn how to build UI e-2-e test with Cypress+BigTest

---

cypress.json
cypress/integration/checkin/checkin.basic.spec.js
cypress/integration/checkout/checkout.basic.spec.js
cypress/integration/eholdings/notes.spec.js
cypress/integration/eholdings/provider-edit.spec.js
cypress/integration/eholdings/provider-search.spec.js
cypress/integration/inventory/quick-marc.spec.js
cypress/support/checkin.js
cypress/support/checkout.js
cypress/support/eholdings.js
cypress/support/index.js
cypress/support/inventory.js
cypress/support/login.js
doc/interactors.md
interactors/accordion.js
interactors/button.js
interactors/checkbox.js
interactors/dropdown.js
interactors/index.js
interactors/list.js
interactors/multi-select.js
interactors/pane.js
interactors/rich-text-editor.js
interactors/text-field.js

- Rewrote tests by using stripes interactors
- Found and document tests that are failing with the reason why they are failing
- Added a few new interactors, like `List`, `MultiSelect` and `RichTextEditor`
- Refactored some tests which used `after` hook as an antipattern https://docs.cypress.io/guides/references/best-practices#Using-after-or-afterEach-hooks

Migrate to interactors

---

.github/workflows/build-npm-release.yml
.github/workflows/build-npm.yml

- Thanks to @funkymalc for instructions on turning off publishing module descriptor to correct the Github Flow build

Turn off publish mod descipter since this is not a module

---

package.json

related with fresh interactors

hotfix of dependencies

---

cypress/integration/data-export/export-instance-records.spec.js
cypress/support/fragments/data-export/dataExportResults.js
cypress/support/fragments/data-export/exportFile.js
cypress/support/fragments/inventory/inventoryActions.js
cypress/support/fragments/inventory/inventorySearch.js
cypress/support/utils/dateTools.js

https://foliotest.testrail.io/index.php?/cases/view/9288

FAT-741 Export small number of instance records - default instance mapping profile

---

CHANGELOG.md
cypress/integration/inventory/create-holdings-as-different-user.spec.js
cypress/support/fragments/inventory/holdingsRecordView.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/newHoldingsRecord.js

- Implement e-2-e automation of test case `C1294`: Create a Holdings record as another user than the one that created the Instance
- https://issues.folio.org/browse/FAT-817

FAT-817: Implement e-2-e automation of test case C1294

---

CHANGELOG.md
cypress/integration/inventory/create-fast-add-record.spec.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/inventory/fastAddNewRecord.js
cypress/support/fragments/inventory/instanceRecordView.js
cypress/support/fragments/inventory/inventoryActions.js
cypress/support/fragments/inventory/itemRecordView.js
cypress/support/fragments/topMenu.js

- Implement e-2-e automation of test case C15850: Create a fast add record from Inventory. Monograph.
- https://issues.folio.org/browse/FAT-823

FAT-823: Implement e-2-e automation of test case C15850

---

CHANGELOG.md
cypress/integration/requests/request-types-filter.spec.js
cypress/support/fragments/requests/requests.js

- Implement e-2-e automation of test case `C540`: Make sure that request type filters are working properly.
- https://foliotest.testrail.io/index.php?/cases/view/540

FAT-887: Implement e-2-e automation of test case C540

---

cypress.json
cypress/integration/inventory/enter-different-type-of-identifiers.spec.js
cypress/support/api/instance.js
cypress/support/api/inventory.js
cypress/support/fragments/data_import/logs/logs.js
cypress/support/fragments/data_import/logs/logsViewAll.js
cypress/support/index.js
interactors/selection.js

Reverts folio-org/stripes-testing#322

Revert "Fat 1640 greening lotus branch"

---

CHANGELOG.md
cypress/integration/inventory/filter-instances-by-tags.spec.js
cypress/support/fragments/inventory/filterInstancesByTags.js

- Implement e-2-e automation of test case `C343215`: Filter instances by tags
- https://foliotest.testrail.io/index.php?/cases/view/343215

FAT-1626: Implement e-2-e automation of test case C343215

---

CHANGELOG.md
cypress/integration/users/loans/declare-lost.spec.js
cypress/support/api/index.js
cypress/support/api/loan-history.js
cypress/support/api/users.js
cypress/support/constants.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/app-paths.js
cypress/support/fragments/inventory/item.js
cypress/support/fragments/service_point/service-point.js
cypress/support/fragments/settings/users/usersOwners.js
cypress/support/fragments/user/loan-details.js
cypress/support/fragments/user/loans.js
cypress/support/fragments/users/usersCard.js
cypress/support/utils/dateTools.js
cypress/support/utils/users.js

Implement e-2-e automation of test case C9191: Loans: Declare lost
https://issues.folio.org/browse/FAT-838
https://foliotest.testrail.io/index.php?/cases/view/9191

Implement e-2-e automation of test case C9191: Loans: Declare lost

---

cypress/integration/users/bulk-edit.spec.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/users/usersCard.js
cypress/support/fragments/users/usersEditPage.js

https://foliotest.testrail.io/index.php?/cases/view/350765

FAT-1683 Verify BULK EDIT permissions list

---

cypress.json
cypress/integration/notes/notes.spec.js
cypress/integration/quickmark/holding-quickmark.spec.js
cypress/support/index.js

first portion of greening + set short timeout

Fat 1692 - greening

---

cypress/support/fragments/loans/renewals.js

Fix failed renewal functionality
[FAT-1721](https://issues.folio.org/browse/FAT-1721)

FAT-1721: Fix e2e fail

---

cypress/integration/loans/renewal-failure.spec.js

**Should be merged after deploying changes [of this PR](https://github.com/folio-org/ui-users/pull/2166)**

Remove redundant exception handler

---

cypress/integration/bulk-edit/in-app/bulk-edit-in-app-users.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

https://foliotest.testrail.io/index.php?/cases/view/357579

FAT-2825 Bulk edit: In app - Update user records permission enabled - Preview of records matched

---

cypress/integration/eholdings/eholdings-packages.spec.js
cypress/integration/eholdings/eholdings-titles-packages.spec.js
cypress/integration/eholdings/eholdings-titles.spec.js
cypress/integration/eholdings/provider-edit.spec.js
cypress/integration/inventory/holdings/holdings-record-through-upload.spec.js
cypress/integration/inventory/holdings/holdings-records-Instancesource-folio.spec.js
cypress/integration/inventory/holdings/holdings-records-Instancesource-marc.spec.js
cypress/integration/inventory/moving-items.spec.js
cypress/integration/inventory/search/browse-call-number-with-space.spec.js
cypress/integration/marc-authority/marc-authority.spec.js
cypress/integration/notes/notes.spec.js
cypress/integration/quickmark/holding-quickmark.spec.js
cypress/integration/quickmark/instance-quickmark.spec.js
cypress/integration/settings/circulation/fee-fine/overdue-fine-policies.spec.js
cypress/support/fragments/inventory/search/browseContributors.js

made fixes for tests (C353639, C353640, C358140) and added tags to spitfire tests where there were none

Fat 2877/c353639

---

cypress/integration/bulk-edit/in-app/bulk-edit-in-app-update-users.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/357578

FAT-2826 Verify "In app - Update user records" permission

---

cypress/integration/bulk-edit/csv/bulk-edit-csv-user-barcodes.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/347872

C347872 Populating preview of matched records

---

cypress/integration/bulk-edit/csv/bulk-edit-csv-user-barcodes.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/360556

C360556 Populating preview of matched records in case no matches

---

cypress/integration/checkout/checkout.basic.spec.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/check-out-actions/check-out-actions.js
cypress/support/fragments/settings/circulation/otherSettings.js
cypress/support/fragments/users/users.js

https://foliotest.testrail.io/index.php?/cases/view/356772&group_by=cases:priority_id&group_order=asc&display_deleted_cases=0&group_id=3

FAT-2479: Implement e-2-e automation of test case C356772

---

cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/347871

FAT3089 - C347871 Uploading file with identifiers

---

cypress/e2e/inventory/export.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/inventory/inventoryActions.js
cypress/support/fragments/settings/remote-storage/remote-storage-configuration.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/260/allure/#suites

greening - firebird tests FAT 2982

---

cypress/e2e/bulk-edit/permissions/bulk-edit-csv-permissions.cy.js
cypress/e2e/bulk-edit/permissions/bulk-edit-in-app-permissions.cy.js
cypress/e2e/circulation-log/search.cy.js
cypress/support/fragments/circulation-log/searchPane.js

https://foliotest.testrail.io/index.php?/cases/view/16978

FAT-1229 C16978 Filter circulation log by checked-out

---

cypress/e2e/circulation-log/search.cy.js
cypress/support/fragments/circulation-log/searchPane.js

https://foliotest.testrail.io/index.php?/cases/view/16980

C16980 Filter circulation log by changed due date

---

cypress/support/fragments/users/users.js

https://issues.folio.org/browse/FAT-3346

greening of autotest C356772

---

cypress.config.js
cypress/e2e/settings/users/patron-block/patron-block-maximum-items-charged-out-removed-after-item-returned.cy.js
cypress/e2e/settings/users/patron-block/patron-block-maximum-items-overdue-removed-after-item-returned.cy.js
cypress/support/api/inventory.js
cypress/support/fragments/settings/users/limits.js
cypress/support/fragments/users/users.js

https://issues.folio.org/browse/FAT-2667

init FAT-2667-nolana

---

cypress/e2e/loans/loans-claim-returned.cy.js

https://issues.folio.org/browse/FAT-3550

FAT-3550/C10959

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/inventory/inventoryInstance.js

https://foliotest.testrail.io/index.php?/cases/view/359225

FAT-3561 C359225 Verify the in-app bulk edit temporary loan type

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/inventory/inventoryInstance.js

https://foliotest.testrail.io/index.php?/cases/view/359226

C359226 Verify user can clear temporary loan type value

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-users.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/users/usersCard.js
interactors/datepicker.js

https://foliotest.testrail.io/index.php?/cases/view/359237

C359237 Verify "Expiration date" option in the dropdown

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-uuids.cy.js

https://foliotest.testrail.io/index.php?/cases/view/359585

C359585 Verify clicking on the "Commit changes" button

---

cypress/e2e/bulk-edit/csv/bulk-edit-csv-external-ids.cy.js
cypress/e2e/bulk-edit/csv/bulk-edit-csv-usernames.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-former-ids.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items-with-deleting.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-items.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-location-filter.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-uuids.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-files.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
cypress/support/fragments/users/usersCard.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/479/allure/

greening - Firebird fixes

---

cypress/e2e/bulk-edit/permissions/bulk-edit-all-permissions.cy.js

https://foliotest.testrail.io/index.php?/cases/view/360090

C360090 Verify switching between Inventory record types radio buttons

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-elements.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/360089

FAT-3681 C360089 Verify "Inventory - holdings" option on "Bulk edit" app

---

cypress/e2e/notes/notes-permission.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/notes/notesEholdings.js

https://issues.folio.org/browse/FAT-3593
https://foliotest.testrail.io/index.php?/cases/view/1300

FAT-3593/C1300

---

cypress/e2e/notes/notes-permission.cy.js

https://issues.folio.org/browse/FAT-1404
https://foliotest.testrail.io/index.php?/cases/view/527

FAT-1404/C527

---

cypress/e2e/notes/notes-permission.cy.js
cypress/support/fragments/notes/notesEholdings.js

https://issues.folio.org/browse/FAT-1406
https://foliotest.testrail.io/index.php?/cases/view/1245

FAT-1406/C1245

---

cypress/e2e/notes/notes-permission.cy.js
cypress/support/fragments/notes/notesEholdings.js

https://issues.folio.org/browse/FAT-1346
https://foliotest.testrail.io/index.php?/cases/view/16993

FAT-1346/C16993 

---

cypress/e2e/checkin/check-in-item-with-open-request.cy.js
cypress/support/fragments/check-in-actions/checkInActions.js
cypress/support/fragments/checkin/modals/awaitingPickupForARequest.js
cypress/support/fragments/checkin/modals/inTransit.js
cypress/support/fragments/servicePoint/switchServicePoint.js

[Implement e-2-e automation of test case C7148: Check In: item with at least one open request](https://issues.folio.org/browse/FAT-1218)

FAT-1218/C7148

---

cypress/e2e/staff-slips/hold-slip.cy.js
cypress/support/fragments/checkin/modals/awaitingPickupForARequest.js
cypress/support/fragments/requests/newRequest.js

[Implement e-2-e automation of test case C347898: Hold slip](https://issues.folio.org/browse/FAT-1431)

FAT-1431/C347898

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/360114

C360114 Verify that User can upload file with Holdings UUIDs

---

cypress/e2e/bulk-edit/in-app/bulkd-edit-in-app-different-identifiers.cy.js

https://foliotest.testrail.io/index.php?/cases/view/360119

C360119 Verify that different Holdings identifiers are supported for Bulk edit

---

cypress/e2e/checkout/checkout.basic.cy.js
cypress/e2e/loans/loans-claim-returned.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js
cypress/e2e/settings/circulation/patron-notices/create-patron-notice-template.cy.js
cypress/support/fragments/check-in-actions/checkInActions.js
cypress/support/fragments/circulation/newNoticePolicyTemplate.js
cypress/support/fragments/users/users.js

- [C7148 Check In: item with at least one open request](https://foliotest.testrail.io/index.php?/cases/view/7148)
- [C356772 An active user with barcode can Check out item](https://foliotest.testrail.io/index.php?/cases/view/356772)
- [C199656 Create notice template](https://foliotest.testrail.io/index.php?/cases/view/199656)
- [C2268 Add notice policy to circulation rules](https://foliotest.testrail.io/index.php?/cases/view/2268)
- [C10959 Loans: Claim returned](https://foliotest.testrail.io/index.php?/cases/view/10959)

Fix failed tests

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/e2e/inventory/search/browse-contributors-exact.cy.js
cypress/e2e/inventory/search/browse-contributors-non-exact.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseCallNumber.js
cypress/support/fragments/inventory/search/browseContributors.js

https://foliotest.testrail.io/index.php?/cases/view/353639
https://foliotest.testrail.io/index.php?/cases/view/353640
https://foliotest.testrail.io/index.php?/cases/view/358140

Fixes of autotests C353639, C353640 and 358140

---

cypress/e2e/inventory/catalogue-new-ordered-recieved-title.cy.js

fixed C3506

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

https://foliotest.testrail.io/index.php?/cases/view/360530

C360530 Verify that User cannot clear permanent loan type

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
cypress/support/fragments/inventory/inventoryInstance.js

Added tests  [C358939](https://foliotest.testrail.io/index.php?/cases/view/358939), [C359210](https://foliotest.testrail.io/index.php?/cases/view/359210), [C359225](https://foliotest.testrail.io/index.php?/cases/view/359225), [C359226](https://foliotest.testrail.io/index.php?/cases/view/359226)

Firebird tests one

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://issues.folio.org/browse/FAT-3180
https://foliotest.testrail.io/index.php?/cases/view/359589

FAT-3180/C359589

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseCallNumber.js

https://foliotest.testrail.io/index.php?/cases/view/359593
https://issues.folio.org/browse/FAT-3181

add test C359593

---

cypress/e2e/inventory/search/search-in-inventory.cy.js
cypress/support/fragments/inventory/inventoryInstance.js

https://foliotest.testrail.io/index.php?/cases/view/360555
https://foliotest.testrail.io/index.php?/cases/view/360548

FAT-4094/Fixed tests C360555, C360548

---

cypress/e2e/quickmark/holding-quickmark.cy.js
cypress/e2e/quickmark/instance-quickmark.cy.js
cypress/support/fragments/quickMarcEditor.js

https://foliotest.testrail.io/index.php?/cases/view/353612
https://issues.folio.org/browse/FAT-4321

FAT-4321/Fixed test C353612

---

cypress/e2e/inventory/actions-menu.cy.js

Test passed locally and if I run only firebird tests
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/680/allure/
But in general run test fails

greening - C196753

---

cypress/e2e/settings/tenant/service-point-creating.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/settings/settingsPane.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js

https://foliotest.testrail.io/index.php?/cases/view/375150

C375150 Verify that user can save new Service point

---

cypress/e2e/data-import/importing-marc-bib-files/updates-should-add-035-field.cy.js
cypress/support/fragments/data_import/match_profiles/newMatchProfile.js
package.json

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/718/allure/
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/712/allure/#suites/295a61c1d664084ad0893db0ec2447e3/35d090f40a1ecc09/

Fixed c358998

---

interactors/textarea.js

Added selector for `cols` attribute of `textarea` interactor
https://github.com/folio-org/stripes-components/pull/1976

STCOM-1101 Added cols selector for textarea

---

cypress/e2e/bulk-edit/csv/bulk-edit-csv-external-ids.cy.js
cypress/e2e/bulk-edit/csv/bulk-edit-csv-usernames.cy.js

fixed tests [C353954](https://foliotest.testrail.io/index.php?/cases/view/353954) and [C353964](https://foliotest.testrail.io/index.php?/cases/view/353964)

fixed C353954 and C353964

---

cypress/e2e/export-manager/search-filter-verify.cy.js

fixed [C350727](https://foliotest.testrail.io//index.php?/cases/view/350727)

fixed a test

---

cypress/e2e/data-import/importing-marc-authority-files.cy.js
cypress/e2e/inventory/holdings/holdings-records-Instancesource-folio.cy.js
cypress/e2e/inventory/holdings/holdings-records-Instancesource-marc.cy.js
cypress/e2e/inventory/moving-items.cy.js

https://issues.folio.org/browse/FAT-4096

FAT-4096 autotests stabilization

---

cypress/e2e/inventory/actions-menu.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress%20tests/786/allure/#

Firebird test fixes

---

cypress/e2e/marc-authority/marc-authority-delete.cy.js
cypress/support/fragments/data_import/dataImport.js
cypress/support/fragments/marcAuthority/marcAuthorities.js
cypress/support/fragments/marcAuthority/marcAuthoritiesDelete.js

https://issues.folio.org/browse/FAT-2759
https://foliotest.testrail.io/index.php?/cases/view/357549

FAT-2759/C357549

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/users/usersCard.js

https://foliotest.testrail.io/index.php?/cases/view/359592

C359592 Verify updating Email in Bulk edit

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/support/fragments/marcAuthority/marcAuthority.js

https://issues.folio.org/browse/FAT-2703
https://foliotest.testrail.io/index.php?/cases/view/353536

FAT-2703/C353536

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/support/fragments/marcAuthority/marcAuthorities.js

https://issues.folio.org/browse/FAT-2706
https://foliotest.testrail.io/index.php?/cases/view/353583

FAT-2706/C353583

---

cypress/e2e/bulk-edit/permissions/bulk-edit-query-permissions.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1169/
https://foliotest.testrail.io/index.php?/cases/view/366073

FAT-4794/C366073

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/support/fragments/marcAuthority/marcAuthority.js
cypress/support/fragments/quickMarcEditor.js

https://issues.folio.org/browse/FAT-2748
https://foliotest.testrail.io/index.php?/cases/view/353604
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1211/allure/#

FAT-2748/C356840

---

cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-barcodes-preview.cy.js
cypress/e2e/bulk-edit/csv/bulk-edit-csv-user-barcodes.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

autotest updates according to updates in test cases [C347872](https://foliotest.testrail.io/index.php?/cases/view/347872) and [C360556](https://foliotest.testrail.io/index.php?/cases/view/360556)
[jenkins run](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1228/)

FAT-4732/FAT-4734

---

cypress/e2e/fee-fine/fee-fine-history.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js

https://issues.folio.org/browse/FAT-4854
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1319/console
https://foliotest.testrail.io/index.php?/cases/view/2268

C2268 is fixed

---

cypress/e2e/fee-fine/fee-fine-history.cy.js
cypress/e2e/recieve-notice/recieve-notice-checkout.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1335/console

C347621 is fixed

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
cypress/support/fragments/inventory/inventoryInstance.js

https://foliotest.testrail.io/index.php?/cases/view/367975
https://issues.folio.org/browse/FAT-4797
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1303/allure/

FAT-4797/C367975

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
cypress/support/fragments/inventory/inventoryInstance.js

https://foliotest.testrail.io/index.php?/cases/view/367975

FAT-4797 orchid

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/support/fragments/quickMarcEditor.js

https://issues.folio.org/browse/FAT-4808
https://foliotest.testrail.io/index.php?/cases/view/359238

FAT-4808/C359238 to orchid

---

cypress/e2e/loans/loans-claim-returned.cy.js
cypress/e2e/settings/users/fee&Fine/maximum-number-of-items-borrower-for-loan-type.cy.js
cypress/e2e/users/loans/loan-reached-maximum-renewals.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1366/allure/

changed creating loan policy

---

cypress/e2e/fee-fine/fee-fine-history.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1426/console

C347919 is fixed

---

cypress/e2e/bulk-edit/bulk-edit-landing-page.cy.js
cypress/e2e/bulk-edit/permissions/bulk-edit-csv-query-permissions.cy.js
cypress/e2e/bulk-edit/permissions/bulk-edit-in-app-query-permissions.cy.js
cypress/e2e/circulation-log/marked-as-missing.cy.js

[C380424](https://foliotest.testrail.io/index.php?/cases/view/380424)
[C380425](https://foliotest.testrail.io/index.php?/cases/view/380425)
[C380426](https://foliotest.testrail.io/index.php?/cases/view/380426)

test cases number update

---

cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users.cy.js

https://foliotest.testrail.io/index.php?/cases/view/375217
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1507/allure/

FAT-4968/C375217

---

cypress/e2e/data-import/importing-marc-bib-files/001-003-005-handling-for-new-and-update-srs-record.cy.js
cypress/e2e/finance/fiscalYears/rollover-fiscal-year.cy.js
cypress/support/fragments/data_import/dataImport.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1523/allure/

fixed C17039

---

cypress/e2e/eholdings/eholdings-packages.cy.js
cypress/e2e/marc-authority/marc-authority-delete.cy.js
cypress/e2e/marc-authority/marc-authority-edit.cy.js

https://issues.folio.org/browse/FAT-4807

FAT-4807 Autotests maintenance (orchid)

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/support/fragments/marcAuthority/marcAuthority.js
cypress/support/fragments/quickMarcEditor.js

https://issues.folio.org/browse/FAT-4809
https://foliotest.testrail.io/index.php?/cases/view/375120

FAT-4809-orchid add test C375120

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-uuids.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/users/usersCard.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1616/allure/

C359214 fix

---

cypress/e2e/inventory/search/browse-search-permissions.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

***
[FAT-4984](https://issues.folio.org/browse/FAT-4984)
***
[C375072](https://foliotest.testrail.io/index.php?/cases/view/375072)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1614/allure/)
***

Implementing of FAT-4984

---

cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
cypress/support/fragments/inventory/instanceRecordEdit.js
cypress/support/fragments/inventory/inventoryInstances.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1662/allure/
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1663/allure/

Firebird orchid fixes

---

cypress/e2e/fee-fine/fee-fine-history.cy.js
cypress/e2e/loans/renewal-failure.cy.js
cypress/e2e/recieve-notice/recieve-notice-checkout.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js
cypress/support/fragments/users/feeFineDetails.js
cypress/support/fragments/users/payFeeFaine.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1683/allure/
https://issues.folio.org/browse/FAT-5161

vega autotests fixes: C347919, C347621, C2268, C568

---

cypress/e2e/export-manager/search-filter-verify.cy.js

fixed [C350727](https://foliotest.testrail.io/index.php?/cases/view/350727)
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1697

C350727 fixed

---

cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-barcodes.cy.js
cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-holdings.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-files.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

[C375215](https://foliotest.testrail.io/index.php?/cases/view/375215)

FAT-4961-orchid

---

cypress/e2e/circulation-log/marked-as-missing.cy.js

[C17001](https://foliotest.testrail.io/index.php?/cases/view/17001)
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1703

C17001 fixed

---

cypress/e2e/bulk-edit/permissions/bulk-edit-with-logs-permissions.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/368013

FAT-4970 orchid/C368013

---

cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-usernames.cy.js
cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-holdings.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

[C375216](https://foliotest.testrail.io/index.php?/cases/view/375216)

FAT-4962-orchid

---

cypress/support/fragments/inventory/fastAddNewRecord.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1716/allure/

fixed C15850, C3501

---

cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-barcodes.cy.js
cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-usernames.cy.js
cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-holdings.cy.js
cypress/e2e/export-manager/search-filter-verify.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

[C350727](https://foliotest.testrail.io/index.php?/cases/view/350727) fix and refactoring😭
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1731

fixed tests

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js

[C359225](https://foliotest.testrail.io/index.php?/cases/view/359225)
[C359210](https://foliotest.testrail.io/index.php?/cases/view/359210)
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1749/

C359225-C359210-FIX

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/support/fragments/data-export/dataExportResults.js

[C359225](https://foliotest.testrail.io/index.php?/cases/view/359225)
[C359210](https://foliotest.testrail.io/index.php?/cases/view/359210)
[C196757](https://foliotest.testrail.io/index.php?/cases/view/196757)
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1781

tests fixed

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-barcodes.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-location-filter.cy.js
cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-items.cy.js
cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-items.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
interactors/repeatablefield.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/1855/allure
https://foliotest.testrail.io/index.php?/cases/view/375273
- replaced cy.get for interactors in bulk-edit-actions
- changed function names for more undertandable in bulk-edit-actions
- added new test 375273

FAT-5267/375273

---

cypress/e2e/marc-authority/marc-authority.cy.js
cypress/support/fragments/marcAuthority/marcAuthorities.js

https://issues.folio.org/browse/FAT-2662
https://foliotest.testrail.io/index.php?/cases/view/350641

FAT-2662/C350641 to orchid

---

cypress/support/fragments/inventory/inventoryInstance.js

https://issues.folio.org/browse/FAT-5245

FAT-5245/fix in test C359015

---

cypress/e2e/marc-authority/marc-authority.cy.js

https://issues.folio.org/browse/FAT-2681
https://foliotest.testrail.io/index.php?/cases/view/350680

FAT-2681/C350680-orchid

---

cypress/e2e/bulk-edit/logs/csv/bulk-edit-logs-csv-users-barcodes.cy.js
cypress/e2e/bulk-edit/permissions/bulk-edit-with-logs-permissions.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2053/allure
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2051/allure
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2050/allure
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2041/allure

Orchid firebird fix

---

cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-items-hrids.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2065/allure/

firebird master fixes

---

cypress/e2e/orders/edifact-exports/delete-order-by-user.cy.js
cypress/e2e/orders/editing-fund-and-increasing-cost-in-pol.cy.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/orders/orderLines.js

Allure report:
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2067/

add tests to orchid

---

cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2089/allure

orchid firebird fixes

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js

https://issues.folio.org/browse/FAT-4811
https://foliotest.testrail.io/index.php?/cases/view/375172

FAT-4811/C375172-orchid

---

cypress/e2e/data-import/importing-marc-bib-files/create-holdings-and-item-when-job-profile-not-create-instance.cy.js
cypress/e2e/data-import/importing-marc-bib-files/protected-fields-in-incoming-records-not-deleted-scen2.cy.js
cypress/e2e/data-import/importing-marc-bib-files/single-record-import-with-running-large-job.cy.js
cypress/e2e/data-import/log-details/import-summary-table-for creating-actions.cy.js
cypress/e2e/inventory/single-record-import/import-by-oclc-source-folio.cy.js

***
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2185/allure/#suites/58e1242c35ef9ba789b784065feec439
***

fixed C368009

---

cypress/support/fragments/eholdings/eHoldingsProviderEdit.js

https://issues.folio.org/browse/FAT-5160

FAT-5160-orchid-parallel

---

cypress/e2e/settings/circulation/fee-fine/overdue-fine-policies.cy.js

https://issues.folio.org/browse/FAT-5395
https://foliotest.testrail.io/index.php?/cases/view/9267
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2338/allure/

FAT-5395 Fix test C9267

---

cypress/e2e/settings/orders/preffix-suffix-create.cy.js
cypress/support/fragments/finance/financeHelper.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/settings/orders/newPreffixSuffix.js
cypress/support/fragments/settings/orders/settingsOrders.js
cypress/support/fragments/settingsMenu.js

***
[FAT-1367](https://issues.folio.org/browse/FAT-1367)
***
[C671](https://foliotest.testrail.io/index.php?/cases/view/671)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2381/allure/)
***

Implementing of FAT-1367

---

cypress/e2e/marc-authority/marc-authority-reporting.cy.js

https://issues.folio.org/browse/FAT-5565
https://foliotest.testrail.io/index.php?/cases/view/375231
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2403/allure/

FAT-5565/Fixed test C375231

---

cypress/e2e/settings/orders/change-PO-number.cy.js
cypress/support/fragments/orders/orders.js

***
[FAT-1371](https://issues.folio.org/browse/FAT-1371)
***
[C15493](https://foliotest.testrail.io/index.php?/cases/view/15493)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2477/allure/)
***

Implementing of FAT-1371

---

cypress/e2e/marc-authority/marc-authority-advanced-search.cy.js
cypress/support/fragments/marcAuthority/marcAuthorities.js

https://issues.folio.org/browse/FAT-2661
https://foliotest.testrail.io/index.php?/cases/view/350607
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2502/allure/

FAT-2661/C350607

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-expiration-date.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2511/allure
https://issues.folio.org/browse/FAT-5611
https://foliotest.testrail.io/index.php?/cases/view/359216

FAT-5611/C359216

---

cypress/e2e/settings/orders/increase-pol-limit.cy.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/settings/orders/settingsOrders.js

***
[FAT-1372](https://issues.folio.org/browse/FAT-1372)
***
[C15497](https://foliotest.testrail.io/index.php?/cases/view/15497)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2551/allure/)
***

Implementing of FAT-1372

---

cypress/e2e/inventory/search/browse-contributors.cy.js
cypress/support/fragments/inventory/instanceRecordEdit.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseContributors.js

https://issues.folio.org/browse/FAT-2727
https://foliotest.testrail.io/index.php?/cases/view/353999
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2605/allure/

FAT-2727/C353999

---

cypress/e2e/inventory/search/browse-contributors.cy.js

https://issues.folio.org/browse/FAT-2719
https://foliotest.testrail.io/index.php?/cases/view/353660
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2609/allure/

FAT-2719/C353660

---

cypress/e2e/inventory/search/browse-contributors.cy.js
cypress/support/fragments/inventory/instanceRecordEdit.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/search/browseContributors.js

https://issues.folio.org/browse/FAT-2747
https://foliotest.testrail.io/index.php?/cases/view/356837
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2660/allure/

FAT-2747/C356837

---

cypress/support/fragments/inventory/inventoryActions.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2699/allure/

changed function

---

cypress/e2e/marc-authority/marc-authority-edit.cy.js

https://issues.folio.org/browse/FAT-5962
https://foliotest.testrail.io/index.php?/cases/view/353585
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2708/allure/

FAT-5962/Fixed test C353585

---

cypress/e2e/circulation-log/users-can-select-filters-but-not-actions-menus.cy.js
cypress/e2e/recieve-notice/item-aged-to-lost-triggers.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/circulation-log/searchPane.js
cypress/support/fragments/circulation-log/searchResults.js

- [C365625: Verify that users can select filters, but not the Actions menus with "Circulation log: View permission "](https://issues.folio.org/browse/FAT-5058)
- currently the test is failing due to a bug [UIREQ-961](https://issues.folio.org/browse/UIREQ-961)

FAT-5058/C365625

---

cypress/e2e/orders/receiving-and-check-in/update-barcode.cy.js
cypress/support/fragments/inventory/itemRecordView.js

***
[FAT-1375](https://issues.folio.org/browse/FAT-1375)
***
[C736](https://foliotest.testrail.io/index.php?/cases/view/736)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2777/allure/)
***

Implementing of FAT-1375

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-uuids-with-null.cy.js

https://issues.folio.org/browse/FAT-6024
https://foliotest.testrail.io/index.php?/cases/view/380589
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2790/allure

FAT-6024/C380589 

---

cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/quickMarcEditor.js

https://issues.folio.org/browse/FAT-6065
https://foliotest.testrail.io/index.php?/cases/view/353612
https://foliotest.testrail.io/index.php?/cases/view/345398
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2800/allure/
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2799/allure/

FAT-6065/Fixed tests C353612 and C345398

---

cypress/e2e/settings/data-export/default-field-mapping-profiles.cy.js
cypress/support/fragments/data-export/exportMappingProfile/singleFieldMappingProfilePane.js

[C15822](https://foliotest.testrail.io/index.php?/cases/view/15822)
[C15825](https://foliotest.testrail.io/index.php?/cases/view/15825)
[jenkins run](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2829)

FAT-2573/FAT-2574

---

cypress/e2e/users/financial-transactions/financial-transactions-report-menu-option.cy.js
cypress/support/fragments/users/financialTransactionDetailReportModal.js
cypress/support/fragments/users/usersSearchResultsPane.js

https://issues.folio.org/browse/FAT-2605
https://foliotest.testrail.io/index.php?/cases/view/343317
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2884/allure/

C343317 is added

---

cypress/e2e/circulation-log/filtering-circulation-log-by-waived-fully.cy.js
cypress/support/fragments/users/waiveFeeFineModal.js

- [C17054: Check the Actions button from filtering Circulation log by waived fully](https://issues.folio.org/browse/FAT-1256)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2901/allure/)

FAT-1256/C17054

---

cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-search-by-subject.cy.js

https://issues.folio.org/browse/FAT-6071
https://foliotest.testrail.io/index.php?/cases/view/380571
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2902/allure/

FAT-6071/Fixed test C380571

---

cypress/e2e/inventory/marc-bibliographic.cy.js
cypress/e2e/inventory/moving-items.cy.js
cypress/e2e/quickmark/instance-quickmark.cy.js

https://issues.folio.org/browse/FAT-5845
https://foliotest.testrail.io/index.php?/cases/view/345404
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2915/allure/

FAT-5845/Fixed test C345404

---

cypress/e2e/inventory/search/browse-deleted-contributors.cy.js
cypress/support/fragments/inventory/search/browseContributors.js
cypress/support/fragments/quickMarcEditor.js

https://issues.folio.org/browse/FAT-2754
https://foliotest.testrail.io/index.php?/cases/view/357021
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2932/allure/

FAT-2754/C357021

---

cypress/e2e/circulation-log/filtering-circulation-log-by-waived-fully.cy.js

- [C17053: Filter circulation log by waived fully](https://issues.folio.org/browse/FAT-1255)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2905/allure/)

FAT-1255/C17053

---

cypress/e2e/circulation-log/filtering-circulation-log-by-waive-action.cy.js

- [C17055: Filter circulation log by waived partially](https://issues.folio.org/browse/FAT-1257)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2957/allure/)

FAT-1257/C17055

---

cypress/e2e/finance/funds/funds.search.cy.js
cypress/e2e/finance/ledgers/ledgers.search.cy.js
cypress/support/fragments/finance/fiscalYears/fiscalYears.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/finance/groups/groups.js
cypress/support/fragments/finance/ledgers/ledgers.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/organizations/organizations.js

***
[FAT-6105](https://issues.folio.org/browse/FAT-6106)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2951/allure/)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/2953/allure/)
***

Fix master tests with reset buuton

---

cypress/e2e/inventory/search/browse-subjects.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/inventory/search/browseSubjects.js

[FAT-2633](https://issues.folio.org/browse/FAT-2633) [C350392](https://foliotest.testrail.io/index.php?/cases/view/350392)
[FAT-2634](https://issues.folio.org/browse/FAT-2634) [C350393](https://foliotest.testrail.io/index.php?/cases/view/350393)
[jenkins run](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3066)

FAT-2633-2634

---

cypress/e2e/invoices/search-invoices.cy.js
cypress/support/fragments/invoices/invoices.js

***
[FAT-1333](https://issues.folio.org/browse/FAT-1333)
***
[C6723](https://foliotest.testrail.io/index.php?/cases/view/6723)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3021/allure/)
***

Implementing of FAT-1333

---

cypress/e2e/invoices/filter-invoices.cy.js
cypress/e2e/invoices/search-invoices.cy.js
cypress/e2e/orders/pol-export-by-filters.cy.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/orders/orderLines.js

***
[FAT-1334](https://issues.folio.org/browse/FAT-1334)
***
[C6724](https://foliotest.testrail.io/index.php?/cases/view/6724)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3071/allure/)
***

Implementing of FAT-1334

---

cypress/e2e/settings/acquisition-units/edit-acquisition-unit.cy.js
cypress/support/fragments/settings/acquisitionUnits/acquisitionUnits.js

***
[FAT-1212](https://issues.folio.org/browse/FAT-1212)
***
[C6729](https://foliotest.testrail.io/index.php?/cases/view/6729)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3107/allure/)
***

Implementing of FAT-1212

---

cypress/e2e/organizations/edit-organization.cy.js
cypress/support/fragments/organizations/organizations.js

***
[FAT-1385](https://issues.folio.org/browse/FAT-1385)
***
[C673](https://foliotest.testrail.io/index.php?/cases/view/673)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3112/allure/)
***

Implementing of FAT-1385

---

cypress/e2e/circulation-log/filtering-circulation-log-by-actions.cy.js

- [C17059: Filter circulation log by refunded partially](https://issues.folio.org/browse/FAT-1261)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3108/allure/#suites/3f5005bfc856b474f5504f930414e596/7b664a4c1421d470/)

FAT-1261/C17059

---

cypress/e2e/circulation-log/filtering-circulation-log-by-actions.cy.js

- [C17050: Check the Actions button from filtering Circulation log by Paid fully](https://issues.folio.org/browse/FAT-1252)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3151/allure/#suites/3f5005bfc856b474f5504f930414e596/d82d6a09ce500ef8/)

FAT-1252/C17050

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes-error.cy.js
cypress/e2e/settings/data-export/default-field-mapping-profiles.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3167/allure
https://issues.folio.org/browse/FAT-6463
https://foliotest.testrail.io/index.php?/cases/view/347883

FAt-6463/C347883

---

cypress/e2e/organizations/create-interface-to-organization.cy.js
cypress/support/fragments/organizations/newOrganization.js
cypress/support/fragments/organizations/organizations.js

***
[FAT-2546](https://issues.folio.org/browse/FAT-2546)
***
[C3467](https://foliotest.testrail.io/index.php?/cases/view/3467)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3190/allure/)
***

Implementing of FAT-2546

---

cypress/e2e/data-import/importing-marc-bib-files/edit-protected-and-linked-fields-using-update-marcbib-profile.cy.js
cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://issues.folio.org/browse/FAT-1325
https://foliotest.testrail.io/index.php?/cases/view/347906
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3225/allure/

FAT-1325/C347906

---

cypress/e2e/bulk-edit/permissions/bulk-edit-all-permissions.cy.js

https://issues.folio.org/browse/FAT-6532
https://foliotest.testrail.io/index.php?/cases/view/347870
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3232/allure

FAT-6532/C347870

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseCallNumber.js

https://issues.folio.org/browse/FAT-1327
https://foliotest.testrail.io/index.php?/cases/view/347910
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3248/allure/

FAT-1327/C347910

---

cypress/e2e/bulk-edit/permissions/bulk-edit-without-permissions.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3257/allure
https://issues.folio.org/browse/FAT-6534
https://foliotest.testrail.io/index.php?/cases/view/376993

FAT-6534/C376993

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseCallNumber.js

https://issues.folio.org/browse/FAT-1326
https://foliotest.testrail.io/index.php?/cases/view/347909
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3259/allure/

FAT-1326/C347909

---

cypress/e2e/users/browse-permissions.cy.js

[FAT-6672](https://issues.folio.org/browse/FAT-6672) [FAT-6673](https://issues.folio.org/browse/FAT-6673)
[C350673](https://foliotest.testrail.io/index.php?/cases/view/350673) [C350674](https://foliotest.testrail.io/index.php?/cases/view/350674)
[jenkins](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3266/)

FAT-6672-6673

---

cypress/e2e/inventory/search/browse-call-number-with-space.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://issues.folio.org/browse/FAT-1329
https://foliotest.testrail.io/index.php?/cases/view/347918
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3305/allure/

FAT-1329/C347918

---

cypress/e2e/bulk-edit/permissions/bulk-edit-permission-for-all-approaches.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

https://foliotest.testrail.io/index.php?/cases/view/353561
https://issues.folio.org/browse/FAT-6533
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3306/allure

FAT-6533/C353561

---

cypress/e2e/checkin/sessionId-while-check-in.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3322/console
https://issues.folio.org/browse/FAT-6746
https://foliotest.testrail.io/index.php?/cases/view/398022&group_by=cases:section_id&group_id=88&group_order=asc&display_deleted_cases=0

C398022 is added

---

cypress/e2e/bulk-edit/permissions/bulk-edit-try-to upload-without-permissions.cy.js

https://foliotest.testrail.io/index.php?/cases/view/388491
https://issues.folio.org/browse/FAT-6536
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3344/allure

FAT-6536/C388491

---

cypress/e2e/data-import/log-details/log-details-for-created-imported-order-records.cy.js

https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3354/allure/

fixed C375178

---

cypress/e2e/data-import/log-details/record-title-is-present-in-log-details-when-job-profile-only-involves-holdings-and-items.cy.js
cypress/e2e/inventory/settings/create-edit-mode-for-isri-profiles.cy.js

https://issues.folio.org/browse/FAT-6717

issue with looping and terminated agents is solved

---

cypress/e2e/data-import/importing-marc-bib-files/update-controllable-subfield0.cy.js
cypress/e2e/inventory/search/browse-contributors-exact.cy.js
cypress/e2e/inventory/search/browse-contributors-non-exact.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseContributors.js

https://issues.folio.org/browse/FAT-6967
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3533/allure/

FAT-6967/Fixed tests of inventory browse call number

---

cypress/e2e/orders/blocked-when-PO-line-has-related-approved-invoice.cy.js
cypress/support/fragments/orders/orderLines.js
cypress/support/utils/interactorsTools.js

***
[FAT-5076](https://issues.folio.org/browse/FAT-5076)
***
[C368485](https://foliotest.testrail.io/index.php?/cases/view/368485)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3559/allure/)
***

Implementing of FAT-5076

---

cypress/e2e/settings/orders/change-the-POL-limit.cy.js
cypress/support/fragments/orders/orderLines.js

***
[FAT-1365](https://issues.folio.org/browse/FAT-1365)
***
[C668](https://foliotest.testrail.io/index.php?/cases/view/668)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3577/allure/)
***

Implementing of FAT-1365

---

cypress/e2e/checkin/sessionId-while-check-in.cy.js
cypress/e2e/data-import/e2e/match-on-instance-identifier-scen1.cy.js
cypress/e2e/data-import/e2e/match-on-instance-identifier-scen2.cy.js
cypress/e2e/data-import/importing-marc-bib-files/import-to-create-open-orders-electronic-resource-with-no-inventory.cy.js
cypress/e2e/data-import/importing-marc-bib-files/match-on-instance-identifier-scen4.cy.js
cypress/support/utils/dateTools.js
cypress/support/utils/exceptionTools.js
cypress/support/utils/generateIdentifierCode.js

***
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3617/allure/
***

fixed C347831

---

cypress/e2e/data-import/log-details/import-holdings-and-instance-using-marc-to-marc-submatch.cy.js
cypress/support/fragments/data_import/job_profiles/newJobProfile.js
cypress/support/fragments/data_import/match_profiles/newMatchProfile.js
cypress/support/fragments/inventory/instanceRecordView.js

***
https://issues.folio.org/browse/FAT-7010
***
https://foliotest.testrail.io/index.php?/cases/view/397383
***
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3719/allure/
***

Fat 7010 c397383

---

cypress/e2e/users/user-able-to-edit-user-records.cy.js
cypress/support/fragments/users/userEdit.js
cypress/support/fragments/users/users.js

- [FAT-7322](https://issues.folio.org/browse/FAT-7322)
- [Verify that user is able to edit user records without error messages](https://foliotest.testrail.io/index.php?/cases/view/398021)

FAT-7322/C398021

---

cypress/e2e/permissions/permission-sets/setting-users-view-all-settings-works-as-expected.cy.js
cypress/support/fragments/settings/users/departments.js
cypress/support/fragments/settings/users/usersSettingsGeneral.js
cypress/support/fragments/settingsMenu.js

- [FAT-7365](https://issues.folio.org/browse/FAT-7365)
- [Verify that "Settings(users):View all settings" works as expected Scenario 6](https://foliotest.testrail.io/index.php?/cases/view/405545)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3875/allure/#suites/5c95f95184854306a611e6ea0cd1a6fa/7e75cf051d2ce790/)

FAT-7365/C405545

---

cypress/e2e/permissions/permission-sets/setting-users-view-all-settings-works-as-expected.cy.js
cypress/support/fragments/settings/users/conditions.js

- [FAT-7381](https://issues.folio.org/browse/FAT-7381)
- [Verify that "Settings(users):View all settings" works as expected Scenario 5](https://foliotest.testrail.io/index.php?/cases/view/404383)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3881/allure/#suites/5c95f95184854306a611e6ea0cd1a6fa/6d7812fb8fb6105f/)

FAT-7381/C404383

---

cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://issues.folio.org/browse/FAT-7101

FAT-7101/fix in browse call numbers

---

cypress/e2e/staff-slips/add-notice-token.cy.js

- [FAT-7379](https://issues.folio.org/browse/FAT-7379)
- [Add "user.preferredFirstName" as staff slip token in Settings](https://foliotest.testrail.io/index.php?/cases/view/375248)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3916/allure/#suites/ff16f7de182a11a393f2b760ca00ef11/e6bcfb63f035b767/)

FAT-7379/C375248

---

cypress/e2e/permissions/save-is-disabled-in-case-of-errors-on-my-profile.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/settings/my-profile/change-password.js
cypress/support/utils/arrays.js
cypress/support/utils/generatePassword.js

- [FAT-7380](https://issues.folio.org/browse/FAT-7380)
- [Verify that "Save" button is disabled in case of validation errors on "My profile" form
](https://foliotest.testrail.io/index.php?/cases/view/375097)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/3951/allure/#suites/0a8115c5127d22135cf21e3d9ac8d3f5/a98d32845e121bc0/)

FAT-7380/C375097

---

cypress/e2e/users/financial-transactions/financial-transactions-report-menu-option.cy.js
cypress/support/fragments/users/financialTransactionDetailReportModal.js
cypress/support/fragments/users/usersSearchResultsPane.js

https://issues.folio.org/browse/FAT-2615
https://issues.folio.org/browse/FAT-2596
https://foliotest.testrail.io/index.php?/cases/view/343306
https://foliotest.testrail.io/index.php?/cases/view/343308
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4031/

Added automated tests for FAT-2596, FAT-2615

---

cypress/support/fragments/circulation/circulation-rules.js

Fix for https://foliotest.testrail.io/index.php?/cases/view/6530
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4095/allure/

fix for circulation rules

---

cypress/e2e/ideyalabs/eholdings/G_eholdings.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js
cypress/support/fragments/circulation/circulation-rules.js

https://foliotest.testrail.io/index.php?/cases/view/654
https://foliotest.testrail.io/index.php?/cases/view/656
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4102/allure/

Fat 7670 fat 7671

---

cypress/e2e/marc-authority/marc-holdings/modify-marc-holdings-of-deleted-user.cy.js
cypress/e2e/marc-authority/modify-marc-file-of-deleted-user.cy.js

https://issues.folio.org/browse/FAT-2776
https://foliotest.testrail.io/index.php?/cases/view/358996
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4119/allure/

FAT-2776/C358996

---

cypress/e2e/data-import/settings/no-duplicates-profiles-appears-in-job-profile-with-repeatable-profiles.cy.js

***
https://issues.folio.org/browse/FAT-7816
***
https://foliotest.testrail.io/index.php?/cases/view/385629
***
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4166/allure/
***

FAT-7816-C385629

---

.eslintrc
cypress/e2e/users/financial-transactions/financial-transactions-report-menu-option.cy.js
cypress/support/fragments/users/financialTransactionDetailReportModal.js

https://foliotest.testrail.io/index.php?/cases/view/343322
https://foliotest.testrail.io/index.php?/cases/view/343315
https://issues.folio.org/browse/FAT-2610
https://issues.folio.org/browse/FAT-2603
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4181/allure/

Added tests for FAT 2610, 2603

---

cypress/e2e/ideyalabs/users.cy.js
cypress/e2e/users/preferred-first-name-displays-in-user-record-view.cy.js
cypress/support/fragments/users/userEdit.js
cypress/support/fragments/users/users.js

- [FAT-7735](https://issues.folio.org/browse/FAT-7735)
- [Add Preferred first name and confirm its display in the User record View and Edit screens](https://foliotest.testrail.io/index.php?/cases/view/11096)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4197/allure/#suites/60aef4739493073e65c5d706506f5371/43349ffb537ffbe3/)

FAT-7735/C11096

---

cypress/e2e/settings/circulation/patron-notices/metadata-info-patron-notice-templates.cy.js
cypress/support/fragments/circulation/notice-policy-template.js

- [FAT-7813](https://issues.folio.org/browse/FAT-7813)
- [Add metadata info to view of Patron Notice Templates scenario 1,4,5](https://foliotest.testrail.io/index.php?/cases/view/387439)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4210/allure/#suites/60aef4739493073e65c5d706506f5371/7aea739a1cf83378/)

FAT-7813/C387439

---

cypress/e2e/staff-slips/metadata-information-staff-slips-scenario.cy.js
cypress/support/fragments/circulation/editStaffClips.js

- [FAT-7814](https://issues.folio.org/browse/FAT-7814)
- [Add metadata information to view of Staff Slips scenario 1,4,5](https://foliotest.testrail.io/index.php?/cases/view/387437)
- [Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4211/allure/#suites/72a0711ded3b8300e4ff9c90c69c1597/63f2162cc5f8395a/)

FAT-7814/C387437

---

cypress/e2e/finance/fiscalYears/fiscalYearRollover/encumbrances-are-rolled-over.cy.js
cypress/support/fragments/finance/funds/funds.js

***
[FAT-7703](https://issues.folio.org/browse/FAT-7703)
***
[С375267](https://foliotest.testrail.io/index.php?/cases/view/375267)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4177/allure/)
***

Idea Labs: Implementing of FAT-7703

---

cypress/e2e/agreements/agreement-notes/create-agreement-notes.cy.js
cypress/support/dictionary/devTeams.js
cypress/support/fragments/agreements/agreements.js
cypress/support/fragments/agreements/agreementsDetails.js
cypress/support/fragments/notes/newNote.js
cypress/support/fragments/settings/notes/notes.js

testrail_link https://foliotest.testrail.io/index.php?/cases/view/1308
allure_link https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4206/allure/
team ERM

FAT-1308 Create a note for an Agreement record (ERM)

---

cypress/e2e/marc-authority/marc-authority-reporting-date-input.cy.js
cypress/support/fragments/marcAuthority/marcAuthorities.js

***
[C375218](https://foliotest.testrail.io/index.php?/cases/view/375218)
***
[Allure report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4233/allure/)
***

FAT-375218

---

cypress/e2e/settings/tenant/settings-remain-for-library.cy.js
cypress/support/fragments/settings/settingsPane.js
cypress/support/fragments/settings/tenant/baseTenantPane.js
cypress/support/fragments/settings/tenant/index.js
cypress/support/fragments/settings/tenant/location-setup/campuses.js
cypress/support/fragments/settings/tenant/location-setup/institutions.js
cypress/support/fragments/settings/tenant/location-setup/libraries.js
cypress/support/fragments/settings/tenant/location-setup/locations.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js
cypress/support/fragments/settings/tenant/tenantPane.js
cypress/support/fragments/settingsMenu.js
cypress/support/utils/stringTools.js

***
[C99077](https://foliotest.testrail.io/index.php?/cases/view/399077)
***
[Allure report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4239/allure/)
***

FAT-399077

---

cypress/e2e/settings/remote-storage/accession-tables-final-location.cy.js
cypress/e2e/settings/remote-storage/accession-tables.cy.js
cypress/e2e/settings/remote-storage/configurations.cy.js
cypress/e2e/settings/remote-storage/remote-storage.cy.js
cypress/support/fragments/settings/remote-storage/accessionTables.js
cypress/support/fragments/settings/remote-storage/configurations.js
cypress/support/fragments/settings/remote-storage/index.js
cypress/support/fragments/settings/remote-storage/mappings.js
cypress/support/fragments/settings/tenant/baseTenantPane.js
cypress/support/fragments/settings/tenant/location-setup/campuses.js
cypress/support/fragments/settings/tenant/location-setup/libraries.js
cypress/support/fragments/settings/tenant/locations/newLocation.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js

***
[C343224](https://foliotest.testrail.io/index.php?/cases/view/343224)
***
[Allure report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4235/allure/)
***

FAT-343224 (Firebird)

---

cypress/e2e/marc-authority/marc-bibliographic.cy.js
cypress/support/fragments/quickMarcEditor.js
interactors/button.js

[FAT-7516](https://automate.test.io/projects/49/tasks/7516)
[C360541](https://foliotest.testrail.io/index.php?/cases/view/360541)
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4275/allure/)

FAT-7516-C360541 (Spitfire)

---

cypress/e2e/checkout/checkout.notes.cy.js
cypress/support/fragments/check-out-actions/check-out-actions.js
cypress/support/fragments/notes/newNote.js
cypress/support/fragments/users/usersCard.js

[C356781](https://foliotest.testrail.io/index.php?/cases/view/356781)
[Allure Report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4272/allure/#suites/183769fa7b875e86608837de88041680/1fec4cb32377e147/)

C356781: Verify that all notes assigned to user pop up when user scan patron card (Spitfire)

---

cypress/e2e/checkout/checkout.notes.cy.js
cypress/e2e/ideyalabs/notes/note-type.cy.js

[Allure Report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4309/allure/)

C356781: fixed import statement

---

cypress/e2e/data-import/importing-marc-bib-files/add-subfields-to-linked-fields.cy.js
cypress/e2e/data-import/importing-marc-bib-files/edit-protected-and-linked-fields-using-update-marcbib-profile.cy.js
cypress/e2e/data-import/importing-marc-bib-files/marc-bib-import-delete-linked-field.cy.js
cypress/e2e/data-import/importing-marc-bib-files/update-controllable-subfield0.cy.js
cypress/e2e/data-import/importing-marc-bib-files/update-controlled-and-not-controlled-subfields.cy.js
cypress/e2e/eholdings/eholdings-titles.cy.js
cypress/e2e/ideyalabs/eholdings/G_eholdings.cy.js
cypress/e2e/ideyalabs/eholdings/eHolding.js
cypress/e2e/inventory/marc-bibliographic.cy.js
cypress/e2e/marc-authority/manual-linking/linking-bibField100-to-authority100-with-subfield-0.cy.js
cypress/e2e/marc-authority/manual-linking/linking-bibField240-to-authority100-with-subfield-t.cy.js
cypress/e2e/marc-authority/marc-authority-edit.cy.js
cypress/e2e/marc-authority/marc-authority-import.cy.js
cypress/e2e/marc-authority/marc-authority-sort.cy.js
cypress/e2e/marc-authority/marc-authority-view.cy.js
cypress/e2e/marc-authority/marc-authority.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-corporate.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-genre.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-geographic-name.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-name-title.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-personal-name.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-subject.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-browse-by-uniform-title.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-search-by-childrens-subject-heading.cy.js
cypress/e2e/marc-authority/plug-in-marc-authority/plug-in-marc-authority-search.cy.js

https://issues.folio.org/browse/FAT-7691
https://foliotest.testrail.io/index.php?/cases/view/17090
https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4310/allure/

FAT-7691/C17090

---

cypress/e2e/loans/loan-details.cy.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/loans/loansPage.js

[C561](https://foliotest.testrail.io/index.php?/cases/view/561)
[Allure Report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4304/allure/)

C561: Loan Details: test links (vega)

---

cypress/e2e/orders/delete-fund-in-POL.cy.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/orders/orderLines.js

***
[FAT-5093](https://issues.folio.org/browse/FAT-5093)
***
[С374192](https://foliotest.testrail.io/index.php?/cases/view/374192)
***
***

Implementing of FAT-5093

---

cypress/e2e/requests/filter-request-by-tags.cy.js
cypress/support/fragments/requests/requests.js

FAT-9320
https://foliotest.testrail.io/index.php?/cases/view/9320
[Allure report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4297/allure/)

FAT-9320 Filter request by tag (Vega)

---

cypress/e2e/settings/tenant/location-setup.cy.js
cypress/support/fragments/settings/tenant/baseTenantPane.js
cypress/support/fragments/settings/tenant/location-setup/campuses.js
cypress/support/fragments/settings/tenant/location-setup/libraries.js
cypress/support/fragments/settings/tenant/location-setup/locations.js
cypress/support/fragments/settings/tenant/locations/newLocation.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js

[C365628](https://foliotest.testrail.io/index.php?/cases/view/365628)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4359/allure/)
***

FIX-365628 (Firebird)

---

cypress/e2e/orders/unrelease-encumbrances-when-reopen-unreceived-order.cy.js
cypress/support/fragments/orders/orders.js

***
[FAT-5024](https://issues.folio.org/browse/FAT-5024)
***
[С358539](https://foliotest.testrail.io/index.php?/cases/view/358539)
***
***

Implementing of FAT-5024

---

cypress/e2e/orders/can-not-be-delete-pol-and-order.cy.js
cypress/support/fragments/orders/orders.js

***
[FAT-5130](https://issues.folio.org/browse/FAT-5130)
***
[С375962](https://foliotest.testrail.io/index.php?/cases/view/375962)
***
***

Implementing of FAT-5130

---

cypress/e2e/loans/loan-details.cy.js
cypress/support/dictionary/permissions.js

[C561](https://foliotest.testrail.io/index.php?/cases/view/561)

C561: Loan details: test links (vega) (TaaS) refactor

---

cypress/e2e/permissions/permission-sets/setting-users-view-all-settings-works-as-expected.cy.js
cypress/e2e/settings/users/fee&Fine/view-all-settings-permission-cannot-edit-transfer-accounts.cy.js
cypress/e2e/settings/users/waiveReasons.cy.js
cypress/support/fragments/settings/users/usersSettingsGeneral.js
cypress/support/fragments/settingsMenu.js

- [FAT-8204](https://issues.folio.org/browse/FAT-8204)
- [User with "Setting (Users): View all settings" permission cannot edit transfer accounts](https://foliotest.testrail.io/index.php?/cases/view/407704)
- [Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4395/allure/#suites/f5a99b7f06d2b2248ebb1e1e9a831598/616f4e1b0db0e23d/)

FAT-8204/C407704

---

cypress/e2e/loans/lost-loans.cy.js
cypress/support/fragments/circulation/lost-item-fee-policy.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/users/userDefaultObjects/loanDetails.js

[C10949](https://foliotest.testrail.io/index.php?/cases/view/10949)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4378/allure/)

C10949: Close declared lost loan (vega)

---

cypress/e2e/agreements/agreement-notes/assign-note-to-agreemnet.cy.js
cypress/e2e/agreements/agreement-notes/unassign-note-from-agreemnet.cy.js
cypress/support/fragments/notes/modal/assign-unassign-notes.js
cypress/support/fragments/notes/notes.js
interactors/checkbox.js

https://foliotest.testrail.io/index.php?/cases/view/1311
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4380/allure/

Fat 1311 Unassign a note from an Agreement record (ERM)

---

cypress/e2e/settings/tenant/location-setup.cy.js
cypress/e2e/settings/tenant/service-points-view.cy.js
cypress/support/fragments/settings/tenant/baseTenantPane.js
cypress/support/fragments/settings/tenant/location-setup/locations.js
cypress/support/fragments/settings/tenant/locations/locationDetails.js
cypress/support/fragments/settings/tenant/locations/locationEditForm.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js

[C359588](https://foliotest.testrail.io/index.php?/cases/view/359588)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4381/allure/)
***

FAT-359588 Verify view of services points on the view page (firebird)

---

cypress/e2e/users/financial-transactions/financial-transactions-report-refund.cy.js
cypress/support/fragments/users/financialTransactionDetailReportModal.js

https://issues.folio.org/browse/FAT-2617
https://foliotest.testrail.io/index.php?/cases/view/343329
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4390/allure/

Added test for FAT-2617

---

cypress/e2e/users/financial-transactions/financial-transactions-report-transfer.cy.js

https://issues.folio.org/browse/FAT-2618
https://foliotest.testrail.io/index.php?/cases/view/343330
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4411/allure/

Added test for FAT-2618

---

cypress/e2e/agreements/agreement-notes/delete-note.cy.js
cypress/support/fragments/notes/existingNoteView.js
cypress/support/fragments/notes/modal/deleteConfirmationModal.js

https://foliotest.testrail.io/index.php?/cases/view/1312
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4414/allure/

Fat 1312 Delete a note (erm)

---

cypress/support/dictionary/testTypes.js

Reverts folio-org/stripes-testing#1652

Revert "Fix typo in 'TestTypes' options"

---

cypress/e2e/data-import/e2e/match-on-pol-and-update-instance.cy.js
cypress/e2e/data-import/e2e/match-on-pol-and-update-items.cy.js
cypress/e2e/data-import/e2e/match-on-vrn-and-update-items.cy.js
cypress/e2e/inventory/catalogue-new-ordered-recieved-title.cy.js
cypress/e2e/inventory/item-status-date-updates.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings-for-existing-location.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/orders/basicOrderLine.js
cypress/support/fragments/orders/newOrder.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/orders/selectLocationModal.js
cypress/support/fragments/organizations/newOrganization.js
cypress/support/fragments/settings/tenant/location-setup/locations.js
interactors/pane.js

[C375232](https://foliotest.testrail.io/index.php?/cases/view/375232)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4391/allure/)
***

FAT-375232 Create new holdings for existing location (Thunderjet)

---

cypress/e2e/fee-fine/manual-fee-fine-notices-by-fee-fine-type-charge-and-action.cy.js
cypress/e2e/fee-fine/overdue-fine-renewed-triggers.cy.js
cypress/e2e/fee-fine/overdue-fine-returned-triggers.cy.js
cypress/e2e/recieve-notice/item-aged-to-lost-triggers-short-term.cy.js
cypress/e2e/recieve-notice/item-recalled-recall-request-awaiting-pickup-hold-shelf-expiration-triggers.cy.js
cypress/e2e/recieve-notice/page-request-cancel-request-triggers.cy.js
cypress/e2e/settings/users/fee&Fine/manual-charges.cy.js
cypress/support/fragments/check-in-actions/checkInActions.js
cypress/support/fragments/check-out-actions/check-out-actions.js
cypress/support/fragments/circulation-log/searchPane.js
cypress/support/fragments/settings/circulation/patron-notices/newNoticePolicy.js
cypress/support/fragments/settings/circulation/patron-notices/newNoticePolicyTemplate.js
cypress/support/fragments/settings/circulation/patron-notices/noticePolicies.js
cypress/support/fragments/settings/circulation/patron-notices/noticeTemplates.js
interactors/form.js

[C347864](https://foliotest.testrail.io/index.php?/cases/view/347864)
***
[Allure report](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4269/allure/)
***

FAT-347864 Loan due date/time triggers: short term (Vega)

---

cypress/e2e/agreements/agreement-organizations/remove-organization-from-agreement.cy.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/agreements/agreements.js
cypress/support/fragments/agreements/editAgreement.js

https://foliotest.testrail.io/index.php?/cases/view/1329
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4398/allure/

Fat 1329 Remove an Organization record from an Agreement record (erm)

---

cypress/e2e/agreements/agreement-notes/view-note-on-agreemnet.cy.js

https://foliotest.testrail.io/index.php?/cases/view/1347
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4401/allure/

Fat 1347 View a note on an Agreement record (erm)

---

cypress/e2e/inventory/holdings/fill-852-field-while-creating-new-holdings.cy.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4441/allure/)

FIX-C358990

---

cypress/e2e/settings/tenant/change-interface-language.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/settings/tenant/general/addresses.js
cypress/support/fragments/settings/tenant/general/index.js
cypress/support/fragments/settings/tenant/general/localication.js
cypress/support/fragments/settings/tenant/tenantPane.js

[C377044](https://foliotest.testrail.io/index.php?/cases/view/377044)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4406/allure/)
***

FAT-377044 Verify interface language (Firebird)

---

cypress/e2e/orders/adding-funds-to-POL-with-different-expense-classes.cy.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/orders/orderLines.js

***
[FAT-8586](https://issues.folio.org/browse/FAT-8586)
***
[С399087](https://foliotest.testrail.io/index.php?/cases/view/399087)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4460/allure/)
***

Implementing of FAT-8586

---

cypress/e2e/agreements/agreement-internal-contacts/assign-library-staff-member-to-agreement.cy.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/agreements/editAgreement.js
cypress/support/fragments/users/modal/selectUser.js

https://foliotest.testrail.io/index.php?/cases/view/1314
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4423/allure/

C1314 Assign a library staff member to an Agreement (erm)

---

cypress/e2e/settings/tenant/settings-remain-for-library.cy.js
cypress/support/fragments/settings/tenant/baseTenantPane.js
cypress/support/fragments/settings/tenant/location-setup/institutions.js
cypress/support/fragments/settings/tenant/location-setup/locations.js
cypress/support/fragments/settings/tenant/locations/newLocation.js

[C399077](https://foliotest.testrail.io/index.php?/cases/view/399077)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4439/allure/)
***

FIX-399077

---

cypress/e2e/data-import/e2e/match-on-pol-and-update-items.cy.js
cypress/e2e/data-import/e2e/match-on-vrn-and-update-items.cy.js
cypress/e2e/inventory/catalogue-new-ordered-recieved-title.cy.js
cypress/e2e/inventory/item-status-date-updates.cy.js
cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-payed-or-cancelled.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/finance/budgets/budgets.js
cypress/support/fragments/invoices/index.js
cypress/support/fragments/invoices/invoiceEditForm.js
cypress/support/fragments/invoices/invoiceLines.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/invoices/vouchers.js
cypress/support/fragments/orders/basicOrderLine.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/organizations/newOrganization.js
interactors/button.js

[C387536](https://foliotest.testrail.io/index.php?/cases/view/387536)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4479/allure/)
***

FAT-387536 "Fiscal year" field is not editable for paid invoice (Thunderjet)

---

cypress/e2e/orders/pol-can-not-be-saved-without-expense-class.cy.js
cypress/support/fragments/orders/orderLines.js
interactors/section.js

***
[FAT-8588](https://issues.folio.org/browse/FAT-8588)
***
[С402773](https://foliotest.testrail.io/index.php?/cases/view/402773)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/4460/allure/)
***

Implementing of FAT-8588

---

cypress/e2e/requests/filter-requests-by-service-point.cy.js
cypress/support/fragments/requests/requests.js

https://foliotest.testrail.io/index.php?/cases/view/15178
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4491/allure/

FAT-15178 Filter requests by pickup service point (vega) (TaaS)

---

cypress/e2e/circulation-log/loan-periods.cy.js
cypress/support/fragments/circulation/loan-policy.js

[C646](https://foliotest.testrail.io/index.php?/cases/view/646)
[C647](https://foliotest.testrail.io/index.php?/cases/view/647)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4495/allure/)

FAT 646 647

---

cypress/e2e/loans/multiple-loans.cy.js
cypress/support/fragments/loans/loansPage.js
cypress/support/fragments/users/userDefaultObjects/loanDetails.js

[FAT-572](https://foliotest.testrail.io/index.php?/cases/view/572)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4500/allure/)

FAT-572: Multiple loans: Test change due date (vega) (TaaS)

---

cypress/e2e/inventory/holdings/back-to-holdings-edit-page-from-another-app.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js
cypress/support/fragments/topMenu.js

[C397327 ](https://foliotest.testrail.io/index.php?/cases/view/397327)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4449/allure/)

C397327 Verify that no error appears after switch from Holdings Edit screen to another app and back (TaaS)

---

cypress/e2e/checkin/check-in-service-point-not-assigned.cy.js

[C588](https://foliotest.testrail.io/index.php?/cases/view/588)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4440/allure/)

C588 Check in: at service point not assigned to item's effective location (vega) (TaaS)

---

cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-payed-or-cancelled.cy.js
cypress/e2e/settings/circulation/general/edit-circulation-rules.cy.js
cypress/support/constants.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/settings/inventory/newMaterialType.js

[C387537](https://foliotest.testrail.io/index.php?/cases/view/387537)
[C387534](https://foliotest.testrail.io/index.php?/cases/view/387534)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4509/allure/)
***

FAT-387537 "Fiscal year" field is not editable (Thunderjet)

---

cypress/e2e/orders/inventory-interaction/create-new-holdings-for-existing-location.cy.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4526/allure/)

FIX-375232

---

cypress/e2e/data-import/e2e/match-on-pol-and-update-items.cy.js
cypress/e2e/data-import/e2e/match-on-vrn-and-update-items.cy.js
cypress/e2e/inventory/catalogue-new-ordered-recieved-title.cy.js
cypress/e2e/inventory/item-status-date-updates.cy.js
cypress/e2e/invoices/invoices.manuallyCreateLineFromPol.cy.js
cypress/e2e/invoices/invoices.testPolSearchPlugin.cy.js
cypress/e2e/orders/close-order.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/e2e/orders/orders.unreceivePiece.cy.js
cypress/e2e/orders/po-search.cy.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4532/allure/)

FIX extract poNumber from order response

---

cypress/e2e/agreements/agreement-supplementary-documents/add-supplementary-document-to-agreement.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/agreements/editAgreement.js

https://foliotest.testrail.io/index.php?/cases/view/1318
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4454/allure/

Fat 1318 Add supplementary document to an agreement (erm)

---

cypress/e2e/data-import/e2e/match-on-pol-and-update-items.cy.js
cypress/e2e/data-import/e2e/match-on-vrn-and-update-items.cy.js
cypress/e2e/export-manager/check-view-jobs.cy.js
cypress/e2e/export-manager/orders-export-to-a-vendor/downloading-the-exact-edi-file.cy.js
cypress/e2e/finance/funds/create-encumbrance-from-order.cy.js
cypress/e2e/inventory/filter/filter-instances-by-tags.cy.js
cypress/e2e/inventory/single-record-import/import-by-oclc-source-folio.cy.js
cypress/e2e/invoices/search-invoices.cy.js
cypress/e2e/orders/check-duplicate-POL.cy.js
cypress/e2e/orders/duplicate-order.cy.js
cypress/e2e/orders/edifact-export-to-a-vendor.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings-for-existing-location.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/e2e/orders/receiving-and-check-in/receiving-pieces-from-order-for-PE-mix.cy.js
cypress/e2e/orders/receiving-and-check-in/update-barcode.cy.js
cypress/e2e/orders/unopen-order-with-receiving-workflow.cy.js
cypress/support/fragments/inventory/holdings/inventoryHoldings.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/orders/basicOrderLine.js
cypress/support/fragments/orders/modals/selectInstanceModal.js
cypress/support/fragments/orders/modals/selectLocationModal.js
cypress/support/fragments/orders/modals/unopenConfirmationModal.js
cypress/support/fragments/orders/newOrder.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/orders/orders.js

[C377041](https://foliotest.testrail.io/index.php?/cases/view/377041)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4538/allure)
***

FAT-377041 Select "Keep Holdings" option (Thunderjet)

---

cypress/e2e/orders/unopen-order-with-receiving-workflow.cy.js
cypress/support/fragments/orders/basicOrderLine.js
cypress/support/fragments/orders/modals/unopenConfirmationModal.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/orders/orders.js

[C377040](https://foliotest.testrail.io/index.php?/cases/view/377040)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4492/allure/)
***

FAT-377040 Select "Delete items" option (Thunderjet)

---

cypress/e2e/title-level-request/requester_has_open_request_for_this_item_message_appears.cy.js
cypress/support/fragments/requests/newRequest.js
cypress/support/fragments/settings/circulation/titleLevelRequests.js

https://foliotest.testrail.io/index.php?/cases/view/1283
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4533/allure/

Implemented C1283 (TaaS)

---

cypress/e2e/data-export/empty-cql-file.cy.js

Fix for the failing test:
https://foliotest.testrail.io/index.php?/cases/view/399097
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4539/allure

c399097_fix (firebird)

---

cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-payed-or-cancelled.cy.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4553/allure)
***

FIX-387534

---

cypress/e2e/marc-authority/marc-bibliographic.cy.js
cypress/support/fragments/marcAuthority/marcAuthority.js

[C353526](https://foliotest.testrail.io/index.php?/cases/view/353526)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4542/allure/#suites/f2e3164122807db61df57d8b83ecb94f)

c353526 added test

---

cypress/e2e/finance/funds/moving-allocation-between-funds.cy.js
cypress/e2e/finance/transactions/moving-allocation.cy.js
cypress/e2e/invoices/fiscal-year-is-not-displayed.cy.js
cypress/support/fragments/finance/index.js
cypress/support/fragments/inventory/holdings/inventoryHoldings.js
cypress/support/fragments/inventory/inventoryItem/itemActions.js
cypress/support/fragments/invoices/invoiceEditForm.js
cypress/support/fragments/invoices/invoices.js

[C387533](https://foliotest.testrail.io/index.php?/cases/view/387533)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4546/allure)
***

FAT-387533 "Fiscal year" field is NOT displayed (Thunderjet)

---

cypress/e2e/agreements/agreement-lines/view-an-agreement-line.cy.js
cypress/support/fragments/agreements/agreementLines.js
cypress/support/fragments/agreements/agreementViewDetails.js
interactors/index.js

https://foliotest.testrail.io/index.php?/cases/view/761
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4508/allure/

Fat 761 View an Agreement line (erm)

---

cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/marcAuthority/marcAuthorities.js
interactors/advanced-search-inventory.js

FAT ticket - https://issues.folio.org/browse/FAT-8816
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4571/allure/
- - -
Fixes for advanced search tests (elements were updated be devs) - C350607, C400616, C400610

FAT-8816-Fixes

---

cypress/e2e/inventory/tags/assign-tags-to-holdings-record.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

- [FAT-8602](https://issues.folio.org/browse/FAT-8602)
- [Assign tags to a Holdings record](https://foliotest.testrail.io/index.php?/cases/view/196770)
- [Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4572/allure/#suites/2671cd2d552e86f5ff1850d6999df33d/bf3e20a482132170/)

FAT-8602/C196770

---

cypress/e2e/inventory/tags/filter-by-tags.cy.js

- [FAT-8605](https://issues.folio.org/browse/FAT-8605)
- [Filter Holdings by Tags](https://foliotest.testrail.io/index.php?/cases/view/343216)
- [Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4580/allure/#suites/2671cd2d552e86f5ff1850d6999df33d/ce2df5a3dbac5124/)

FAT-8605/C343216

---

cypress/e2e/settings/remote-storage/remote-storage-provider-name.cy.js
cypress/support/fragments/settings/remote-storage/configurations.js

[C365623](https://foliotest.testrail.io/index.php?/cases/view/365623)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4576/allure/)

C365623 Verify that "Provider name" is renamed (firebird) (TaaS)

---

cypress/e2e/agreements/agreement-lines/add-tags-to-agreement-line-record.cy.js
cypress/support/fragments/agreements/agreementLineInformation.js
cypress/support/fragments/agreements/agreementLines.js
cypress/support/fragments/agreements/agreementViewDetails.js
package.json

https://foliotest.testrail.io/index.php?/cases/view/343340
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4505/allure/

Fat 343340 Add tags to an Agreement Line record (erm)

---

cypress/e2e/invoices/release-encumbrance-checkbox-is-not-checked.cy.js
cypress/support/constants.js
cypress/support/fragments/finance/budgets/budgets.js
cypress/support/fragments/invoices/index.js
cypress/support/fragments/invoices/invoiceLineEditForm.js
cypress/support/fragments/invoices/invoiceLines.js
cypress/support/fragments/invoices/invoiceStates.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/invoices/invoices.js

[C389582](https://foliotest.testrail.io/index.php?/cases/view/389582)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4579/allure)
***

FAT-389582 "Release encumbrance" checkbox is NOT checked after creating (Thunderjet) (TaaS)

---

cypress/e2e/data-import/settings/error-message-for-linking-action-and-mapping-profiles-with-different-record-type.cy.js
cypress/support/fragments/data_import/action_profiles/actionProfileView.js
cypress/support/fragments/data_import/action_profiles/newActionProfile.js

***
https://issues.folio.org/browse/FAT-7768
***
https://foliotest.testrail.io/index.php?/cases/view/404371
***
***

FAT-7768-C404371

---

cypress/e2e/checkin/check-in-items-at-service-points.cy.js
cypress/support/fragments/settings/tenant/location-setup/locations.js

[C589](https://foliotest.testrail.io/index.php?/cases/view/589)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4621/allure)

FAT-589 Check in items at service points for effective location (vega) (TaaS)

---

cypress/e2e/agreements/agreement-lines/add-agreement-line-with-description-only.cy.js
cypress/support/fragments/agreements/agreementLineInformation.js
cypress/support/fragments/agreements/agreementLines.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/agreements/newAgreementLine.js

https://foliotest.testrail.io/index.php?/cases/view/15829
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4511/allure/

Fat 15829 Add agreement line with description only (erm)

---

cypress/e2e/loans/loan-details.cy.js

[C561](https://foliotest.testrail.io/index.php?/cases/view/561)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4622/allure)

fixed test C561

---

cypress/e2e/circulation-log/loan-date-and-time.cy.js
cypress/e2e/loans/loan-dates.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/circulation-log/searchPane.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/loans/loansPage.js

[C350710](https://foliotest.testrail.io/index.php?/cases/view/350710)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4603/allure/)

C350710 Check date and time -- loans (firebird) (TaaS)

---

cypress/e2e/export-manager/job-for-order-with-acquisition-unit.cy.js
cypress/support/fragments/exportManager/exportManagerSearchPane.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/settings/acquisitionUnits/acquisitionUnits.js

***
[C380640](https://foliotest.testrail.io/index.php?/cases/view/380640)
***

C380640: Schedule export job for order with Acquisition unit (thunderjet) (TaaS)

---

cypress/e2e/invoices/approve-and-pay-invoice-in-current-FY-for-previous-FY.cy.js
cypress/support/fragments/finance/fiscalYears/fiscalYears.js
cypress/support/fragments/finance/ledgers/ledgers.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/orders/orders.js
cypress/support/utils/dateTools.js

***
[C388526](https://foliotest.testrail.io/index.php?/cases/view/388526)
***
Here is bug in this testcase, but I finished test by steps.

C388526 Approve and pay invoice created in current FY for previous FY when related order line was created in current FY (thunderjet) (TaaS)

---

cypress/e2e/circulation-log/filter-circulation-log-by-renewed.cy.js

[C17005](https://foliotest.testrail.io/index.php?/cases/view/17005)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4668/allure)

C17005 Filter circulation log by renewed (firebird) (TaaS)

---

cypress/e2e/inventory/holdings/save-empty-statistical-code-on-holdings-page.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js
interactors/fieldset.js
interactors/repeatablefield.js

https://foliotest.testrail.io/index.php?/cases/view/396396
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4616/allure/

C396396 Verify the inability to save empty statistical code field on Holdings create/edit page (folijet)

---

cypress/e2e/invoices/approve-and-pay-invoice-in-current-FY-for-previous-FY.cy.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/orders/orders.js
cypress/support/utils/dateTools.js

Fix C388526 TaaS testcase

---

cypress/e2e/inventory/holdings/marc-holdings-edit-ldr.cy.js
cypress/support/fragments/inventory/holdingsRecordView.js

FAT ticket - https://issues.folio.org/browse/FAT-2756
Test case - https://foliotest.testrail.io/index.php?/cases/view/357063
Allure report - https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4702/allure

FAT-2756-C357063

---

cypress/e2e/requests/request-moved-to-fulfillment-in-progress.cy.js
cypress/support/fragments/check-in-actions/checkInActions.js
cypress/support/fragments/requests/requestDetail.js

https://foliotest.testrail.io/index.php?/cases/view/350425
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4634/allure/

implemented C350425 (vega) (TaaS)

---

cypress/e2e/notes/note-types.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/settings/notes/noteTypes.js

[C357554](https://foliotest.testrail.io/index.php?/cases/view/357554)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4683/allure)

FAT-357554 Verify that user cant delete a Note type when the Note was created (spitfire) (TaaS)

---

cypress/e2e/agreements/agreement-lines/delete-agreement-line.cy.js
cypress/support/fragments/agreements/agreementLineInformation.js
cypress/support/fragments/agreements/agreementLines.js
cypress/support/fragments/agreements/agreementViewDetails.js
cypress/support/fragments/agreements/modals/deleteConfirmationModal.js
cypress/support/fragments/agreements/searchAndFilterAgreementLines.js

https://foliotest.testrail.io/index.php?/cases/view/405546
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4516/allure/

Fat 405546 Delete Agreement Line (erm)

---

cypress/e2e/invoices/approve-and-pay-invoice-with-currency-different-from-default.cy.js
cypress/e2e/invoices/fiscal-year-is-not-displayed.cy.js
cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
cypress/e2e/invoices/release-encumbrance-checkbox-is-not-checked.cy.js
cypress/support/fragments/finance/funds/fundDetails.js
cypress/support/fragments/invoices/invoiceEditForm.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/invoices/modal/payInvoiceModal.js

[C380406](https://foliotest.testrail.io/index.php?/cases/view/380406)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4701/allure)
***

[380406] Approve and pay invoice with currency different from default (Thunderjet) (TaaS)

---

cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
cypress/e2e/invoices/release-encumbrance-checkbox-is-not-checked.cy.js
cypress/support/fragments/finance/funds/fundDetails.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/orders/newOrder.js
interactors/checkbox.js

[C388545](https://foliotest.testrail.io/index.php?/cases/view/388545)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4768/allure)
***

FAT-388545 Approve and pay invoice created in current FY (Thunderjet) (TaaS)

---

cypress/e2e/marc-authority/add-controllable-subfield-to-linked-field.cy.js

[C375954](https://foliotest.testrail.io/index.php?/cases/view/375954)

Fixed test C375954

---

cypress/e2e/agreements/agreement-notes/assign-note-to-agreemnet.cy.js
cypress/e2e/agreements/agreement-notes/create-agreement-notes.cy.js
cypress/e2e/agreements/agreement-notes/delete-note.cy.js
cypress/e2e/agreements/agreement-notes/edit-agreement-notes.cy.js
cypress/e2e/checkout/checkout.notes.cy.js
cypress/e2e/circulation-log/same-date-and-time-format-as-fee-fine-details-page.cy.js
cypress/e2e/data-export/data-export-errors-accordion.cy.js
cypress/e2e/finance/funds/moving-allocation-between-funds.cy.js
cypress/e2e/inventory/derive-fields-crud.cy.js
cypress/e2e/inventory/holdings/edit-marc-holdings.cy.js
cypress/e2e/inventory/marc-bib-save-and-close.cy.js
cypress/e2e/inventory/search/browse-contributors-name-type.cy.js
cypress/e2e/inventory/search/browse-contributors-return-back-via-browser-button.cy.js
cypress/e2e/invoices/save-invoice-fiscal-year-after-fund-distribution-change.cy.js
cypress/e2e/loans/resolve-claim-returned.cy.js
cypress/e2e/marc-authority/reporting/marc-authority-reporting-date-input.cy.js
cypress/e2e/requests/filter-request-by-tags.cy.js
cypress/e2e/settings/remote-storage/accession-tables-final-location.cy.js
cypress/e2e/settings/tenant/location-setup.cy.js
cypress/e2e/settings/users/fee&Fine/manual-charges.cy.js
cypress/e2e/settings/users/owners.cy.js

The scope of work is to add "TaaS" to tests where it was missed.
No test run, because no code changes

Maintenance: add "TaaS" to tests where it was missed

---

cypress/e2e/data-import/settings/duplicate-an-existing-field-mapping-profile.cy.js
cypress/support/fragments/data_import/mapping_profiles/newFieldMappingProfile.js

[testrail](https://foliotest.testrail.io/index.php?/cases/view/2352)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4733/allure/#suites/0f29a4212ddbc0a40cf0646f9bcb6758/e3166401eb577534/)

[C2352] duplicate an existing field mapping profile (folijet) (TaaS)

---

cypress/e2e/invoices/approve-invoice-when-balance-is-close-to-encumbrance.cy.js
cypress/e2e/invoices/fiscal-year-specifies-expecse-class-selection.cy.js
cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
cypress/support/fragments/finance/budgets/budgets.js
cypress/support/fragments/finance/ledgers/ledgerRollovers.js
cypress/support/fragments/invoices/invoiceEditForm.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/invoices/invoiceLineEditForm.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/settings/finance/expenseClasses.js

[C396400](https://foliotest.testrail.io/index.php?/cases/view/396400)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4778/allure)
***

FAT-395400 Select Expense class related to Fiscal year specified in invoice (Thunderjet) (TaaS)

---

cypress/e2e/invoices/approve-and-pay-invoice-created-in-current-FY-for-previous-FY-order.cy.js
cypress/e2e/invoices/approve-invoice-in-previous-FY-and-pay-invoice-in-current FY.cy.js

***
[C388538](https://foliotest.testrail.io/index.php?/cases/view/388538)
***

C388538 Approve invoice in previous FY and pay invoice in current FY (for previous FY) (thunderjet) (TaaS)

---

cypress/e2e/bulk-edit/logs/in-app/bulk-edit-logs-in-app-suppressed-holdings-false.cy.js

[Testrail](https://foliotest.testrail.io/index.php?/cases/view/399063)

C399063 Verify generated Logs files for Holdings suppressed from discovery (Set false) (firebird)

---

cypress/e2e/invoices/cancel-invoice-created-in-current-fy-and-paid-against-previous-fy.cy.js
cypress/support/fragments/invoices/invoiceStates.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/invoices/modal/cancelInvoiceModal.js
cypress/support/utils/stringTools.js

[C388563](https://foliotest.testrail.io/index.php?/cases/view/388563)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4841/allure)
***

FAT-388563 Cancel invoice created in current FY and paid against previous FY (Thunderjet) (TaaS)

---

cypress/e2e/inventory/holdings/check-new-formatting-statistical-code-on-holding-screen.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js

https://foliotest.testrail.io/index.php?/cases/view/400653
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4710/allure/#suites

Fat-400653 Check the new formatting of Statistical codes field on Holdings create/edit screen (Folijet)

---

cypress/e2e/circulation-log/action-buttons-from-filtering-circ-log.cy.js

[C17000](https://foliotest.testrail.io/index.php?/cases/view/17000)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4763/allure/)

C17000 Check the Actions button from filtering Circulation log by closed loan (volaris) (TaaS)

---

cypress/e2e/circulation-log/circulation-log-barcodes.cy.js

[C17094](https://foliotest.testrail.io/index.php?/cases/view/17094)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4723/allure/)

C17094 Verify User barcode appears in Circulation log (volaris) (TaaS)

---

cypress/e2e/orders/unrelease-encumbrances-when-reopen-one-time-order.cy.js
cypress/e2e/orders/unrelease-encumbrances-when-reopen-unreceived-order.cy.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orders.js

[C354279](https://foliotest.testrail.io/index.php?/cases/view/354279)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4874/allure)
***

[354279] Unrelease encumbrances when reopen order (thunderjet) (TaaS)

---

cypress/e2e/orders/encumbrance-released-when-order-closed.cy.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderLineEditForm.js
cypress/support/fragments/orders/orderStates.js
interactors/index.js
interactors/warning.js

[C380392](https://foliotest.testrail.io/index.php?/cases/view/380392)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4884/allure)
***

FAT-380392 Encumbrance is released when an Order was closed (thunderjet) (TaaS)

---

cypress/e2e/organizations/add-note-to-contact-people-list.cy.js
cypress/support/fragments/organizations/organizations.js

***
[FAT-8826](https://issues.folio.org/browse/FAT-8826)
***
[С380642](https://foliotest.testrail.io/index.php?/cases/view/380642)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4896/allure/)
***

Implementing of FAT-8826

---

cypress/e2e/inventory/holdings/see-holdings-with-1000+-items.cy.js
cypress/e2e/inventory/search/browse-call-numbers-all.cy.js
cypress/support/constants.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/item/itemRecordNew.js

[C387477](https://foliotest.testrail.io/index.php?/cases/view/387477)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4894/allure/)

C387477 Browsing call number types when "Call numbers (all)" browse option selected (based on "Item") (spitfire) (TaaS)

---

cypress/e2e/settings/tenant/settings-remain-for-campus.cy.js
cypress/support/fragments/settingsMenu.js

[C397997 ](https://foliotest.testrail.io/index.php?/cases/view/397997)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4885/allure/)

C397997 Verify that selected settings remain for "Campuses" (firebird) (TaaS)

---

cypress/e2e/inventory/search/browse-contributors-exact.cy.js
cypress/e2e/inventory/search/browse-contributors-name-type.cy.js
cypress/e2e/inventory/search/browse-contributors-non-exact.cy.js
cypress/e2e/inventory/search/browse-contributors-return-back-via-browser-button.cy.js
cypress/support/fragments/inventory/search/browseContributors.js

[C353644](https://foliotest.testrail.io/index.php?/cases/view/353644)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4914/allure)
***

FIX-353644

---

cypress/e2e/checkin/check-in-items-at-service-points.cy.js
cypress/e2e/circulation-log/action-buttons-from-filtering-circ-log.cy.js
cypress/e2e/circulation-log/verify-service-point-in-circ-history.cy.js
cypress/e2e/fee-fine/closed-fee-fines.cy.js
cypress/e2e/orders/unopen-order-with-receiving-workflow.cy.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4921/allure)
***

Fix for Location extraction

---

cypress/e2e/inventory/item/trashcan-is-aligned-with-the-corresponding-data-row.cy.js
cypress/support/fragments/inventory/item/itemRecordNew.js

https://foliotest.testrail.io/index.php?/cases/view/380748
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4856/allure/#suites

C380748 Item Create screen: trashcan is aligned with the corresponding data row (folijet) (TaaS)

---

cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-approved.cy.js
cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-cancelled.cy.js
cypress/e2e/invoices/fiscal-year-is-not-etitable-if-invoice-is-paid.cy.js

[C387536](https://foliotest.testrail.io/index.php?/cases/view/387536)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4924/allure)
***

FIX-387536

---

cypress/e2e/circulation-log/same-date-and-time-format-as-fee-fine-details-page.cy.js
cypress/support/fragments/circulation-log/searchResults.js

[Test rail](https://foliotest.testrail.io/index.php?/cases/view/350712)
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4834/allure/)

FIX-C350712 (Volaris) (TaaS)

---

cypress/e2e/orders/holdings-records creation-for-order-with-pe-mix-format-eresource-i.cy.js
cypress/e2e/orders/holdings-records creation-for-order-with-pe-mix-format-eresource-ih.cy.js
cypress/e2e/orders/holdings-records creation-for-order-with-pe-mix-format-eresource-ihi.cy.js

[C402382](https://foliotest.testrail.io/index.php?/cases/view/402382)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4936/allure)
***

[402382] Holdings records for order with "P/E mix" E-resource IHI (thunderjet) (TaaS)

---

cypress/support/fragments/requests/newRequest.js

https://foliotest.testrail.io/index.php?/cases/view/1283
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4831/allure/

Updated C1283 (TaaS) (vega) after modal message was changed

---

cypress/e2e/export-manager/orders-export-to-a-vendor/days-for-weekly-scheduling-are-not-displaying-in-new-scheduling-settings.cy.js
cypress/support/fragments/organizations/organizations.js

***
[C359200](https://foliotest.testrail.io/index.php?/cases/view/359200)
***

C359200: Days previously chosen for weekly scheduling are NOT displaying in new current scheduling settings (thunderjet) (TaaS)

---

cypress/e2e/export-manager/orders-export-to-a-vendor/trying-to-open-an-order-with-2-pol,.cy.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/orders/orders.js

***
[C350410](https://foliotest.testrail.io/index.php?/cases/view/350410)
***

C350410: Check if a User is alerted trying to open an Order with 2 POL, having more than 1 unique accounts for export (thunderjet) (TaaS)

---

cypress/e2e/title-level-request/recall-request-for-instance-with-item-statuses-awaiting-pickup-and-checked-out.cy.js

- [FAT-8952](https://issues.folio.org/browse/FAT-8952)
- [https://foliotest.testrail.io/index.php?/cases/view/380488](https://foliotest.testrail.io/index.php?/cases/view/380488)
-

FAT-8952/C380488

---

cypress/e2e/title-level-request/check_cannot_change_tlr_modal.cy.js
cypress/support/fragments/settings/circulation/titleLevelRequests.js

https://foliotest.testrail.io/index.php?/cases/view/1285
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4967/allure/

C1285 Check that "Cannot change -Allow title level requests-" modal appears (vega) (TaaS)

---

cypress/e2e/orders/open-order-having-po-line-with-two-fund-distributions.cy.js
cypress/support/fragments/finance/ledgers/ledgerRollovers.js

[C407711](https://foliotest.testrail.io/index.php?/cases/view/407711)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/4990/allure)
***

[407711] Open order having PO line with two fund distributions (thunderjet) (TaaS)

---

cypress/e2e/checkin/check-in-multipiece-items.cy.js
cypress/e2e/ideyalabs/checkin.cy.js
cypress/support/fragments/checkin/modals/multipieceCheckIn.js

[testRail](https://foliotest.testrail.io/index.php?/cases/view/590)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5045/allure)

C590 Check in: multipiece items (vega) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-item-line-break.cy.js
cypress/e2e/inventory/cataloging/create-instance-holdings-and-item.cy.js
cypress/e2e/inventory/catalogue-new-ordered-recieved-title.cy.js
cypress/e2e/inventory/holdings/create-holdings-as-different-user.cy.js
cypress/e2e/inventory/holdings/holdings-records-Instancesource-folio.cy.js
cypress/e2e/inventory/instance/create-instance-with-add-new.cy.js
cypress/e2e/inventory/search/browse-call-numbers-sorting.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/e2e/orders/items-for-receiving-includes-order-closed-statuses.cy.js
cypress/e2e/orders/receiving-and-check-in/item-statuses-are-set-to-status-other.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js
cypress/support/fragments/inventory/instanceStates.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventoryNewInstance.js
cypress/support/fragments/inventory/item/itemRecordEdit.js

[C3505](https://foliotest.testrail.io/index.php?/cases/view/3505)
***
[Allure report - test branch](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5036/allure)
[Allure report - master branch](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5039/allure)
***

[3505] Create instance, holdings, and item records for a print resource (folijet) (TaaS)

---

cypress/e2e/settings/tenant/settings-remain-for-location.cy.js
cypress/support/fragments/settings/tenant/location-setup/locations.js

[C399083](https://foliotest.testrail.io/index.php?/cases/view/399083)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5059/allure/#suites/708eb977e1e8fab43fbb3fe7167899c3/93c52e9d02e3cc9f/)

C399083 Verify that selected settings remain for "Locations" (firebird) (TaaS)

---

cypress/e2e/inventory/cataloging/item-moved-from-one-shelf-to-another.cy.js
cypress/support/fragments/inventory/holdingsRecordView.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

[C3500](https://foliotest.testrail.io/index.php?/cases/view/3500)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5067/allure)
***

[3500] An item is being moved from one shelf to another (folijet) (TaaS)

---

cypress/e2e/checkin/checkin-note-is-readable.cy.js
cypress/support/fragments/check-in-actions/checkInActions.js

[C8358](https://foliotest.testrail.io/index.php?/cases/view/8358)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5051/allure)

C8358 Verify checkin note is readable with screenreader (vega) (TaaS)

---

cypress/e2e/requests/create-new-request-for-Recall-type.cy.js
cypress/support/fragments/requests/newRequest.js

https://foliotest.testrail.io/index.php?/cases/view/547
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5019/allure/

C547 Create new request for "Recall" type (vega) (TaaS)

---

cypress/e2e/inventory/search/browse-and-search-capabilities-are-separated.cy.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js
cypress/support/fragments/inventory/search/browseContributors.js
cypress/support/fragments/inventory/search/browseSubjects.js

https://foliotest.testrail.io/index.php?/cases/view/368482
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5011/allure/#suites/70cae361de89575d08e2aa2ffb0cebf1/e098057af5d34cf1/

C368482 Browse and Search capabilities are separated (spitfire) (TaaS)

---

cypress/e2e/inventory/moving-item-between-holdings.cy.js
cypress/e2e/inventory/moving-items-non-remote.cy.js
cypress/e2e/inventory/moving-items-remote.cy.js
cypress/e2e/inventory/moving-items.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings-for-existing-location.cy.js
cypress/e2e/orders/inventory-interaction/create-new-holdings.cy.js
cypress/support/fragments/inventory/holdings/inventoryHoldings.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/item/inventoryItems.js

[C15184](https://foliotest.testrail.io/index.php?/cases/view/15184)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5083/allure)
***

[15184] Move one item between holdings within an instance (firebird) (TaaS)

---

cypress/e2e/settings/tenant/settings-remain-for-campus.cy.js

[Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5089/allure/#suites)

FIX-C397997 (firebird) (TaaS)

---

cypress/e2e/title-level-request/item-checked-in-fulfills-tlr-recall-at-top-of-queue.cy.js
cypress/e2e/title-level-request/recall-request-for-instance-with-item-statuses-paged-and-checked-out.cy.js
cypress/support/fragments/requests/requestDetail.js

[C350682](https://foliotest.testrail.io/index.php?/cases/view/350682)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5151/allure/#suites/b70f38150dbe0eeeb5d27d029f5ad49b/8b71f4d5b06a3594/)
***

C350682: Check that item checked in fulfills the TLR recall at the top of the queue (vega) (Taas)

---

cypress/e2e/title-level-request/user-can-move-item-level-request.cy.js
cypress/support/fragments/requests/move-request.js

[C350523 ](https://foliotest.testrail.io/index.php?/cases/view/350523)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5152/allure/#suites/c56ff4a46d791962be12a0bb68d600a3/2d81ed958f0548c3/)
***

C350523: Check that user can move Item level request (vega) (TaaS)

---

cypress/e2e/title-level-request/user-can-create-title-level-request-from-user-app.cy.js
cypress/support/fragments/users/usersCard.js

[C347888](https://foliotest.testrail.io/index.php?/cases/view/347888)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5155/allure/#suites/38b58d2fc42b8d38f5e158f1902cbc3b/44c156d6ef773f/)
***

C347888: Check that user can create Title level request from User app (use Actions) (vega) (Taas)

---

cypress/e2e/title-level-request/patron-cannot-place-tlr-if-they-already-placed-item-level-request.cy.js

[C350686](https://foliotest.testrail.io/index.php?/cases/view/350686)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5154/allure/#suites/38b58d2fc42b8d38f5e158f1902cbc3b/b81420a1be158bc3/)
***

C350686: Verify that patron cannot place title level request if they already placed an item level request (same instance) (vega) (Taas)

---

cypress/e2e/orders/encumbrance-transaction-updates-when-fund-name-is-changed.cy.js
cypress/support/fragments/orders/orderLines.js

***
[С357540](https://foliotest.testrail.io/index.php?/cases/view/357540)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5161/allure/)
***

C357540 Encumbrance transaction updates when fund name is changed in Open ongoing order and Open invoice related to POL exists (thunderjet) (TaaS)

---

cypress/e2e/orders/changing-order-format-from-pe-mix-to-electronic.cy.js
cypress/support/fragments/orders/orderLines.js

***
[С357550](https://foliotest.testrail.io/index.php?/cases/view/357550)
***
[Allure](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5172/allure/)
***

C357550: Physical format specific fields are cleared when changing order format from P/E Mix to Electronic Resource (thunderjet) (TaaS)

---

cypress/e2e/inventory/search/browse-search-subjects.cy.js

[C350420](https://foliotest.testrail.io/index.php?/cases/view/350420)
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5109/allure/

C350420 Verify Browse Subjects field data validation (spitfire) (TaaS)

---

cypress/e2e/fee-fine/waive-fees-fines.cy.js
cypress/support/fragments/users/userAllFeesFines.js
cypress/support/fragments/users/waiveFeeFineModal.js

[C462](https://foliotest.testrail.io/index.php?/cases/view/462)
[C463](https://foliotest.testrail.io/index.php?/cases/view/463)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5100/allure)

C462 c463 Waive Fees/Fines (vega) (TaaS)

---

cypress/e2e/inventory/cataloging/maintaining-the-catalog/add-item-to-an-existing-title.cy.js
cypress/e2e/inventory/cataloging/maintaining-the-catalog/item-moved-from-one-shelf-to-another.cy.js

[C3493](https://foliotest.testrail.io/index.php?/cases/view/3493)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5158/allure)
***

[3493] Add an item to an existing title (folijet) (TaaS)

---

cypress/e2e/inventory/call-number/browse-call-number-wo-specified-call-number-type.cy.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

[C407697](https://foliotest.testrail.io/index.php?/cases/view/407697)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5149/allure)
***

[407697] Browse for call number w/o specified type (spitfire) (TaaS)

---

cypress/e2e/orders/open-order-w-not-unique-po-line-title.cy.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/settings/configs.js
cypress/support/fragments/settings/invoices/approvals.js
cypress/support/fragments/settings/orders/openOrder.js

[C353562](https://foliotest.testrail.io/index.php?/cases/view/353562)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5181/allure)
***

[353562] User is able to open order with NOT unique PO line title (thunderjet) (TaaS)

---

cypress/e2e/inventory/contributors-browse/not-exact-match-placeholder-displays-fully-in.contributor-column.cy.js
cypress/support/fragments/inventory/inventoryInstance.js

[C357577](https://foliotest.testrail.io/index.php?/cases/view/357577)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5179/allure)
***

[357577] Verify placeholder displays fully in "Contributor" column (spitfire) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-line-break.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-user.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-several-holdings.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-barcodes.cy.js
cypress/e2e/inventory/holdings/verify-missing-holding-source-is-not-populated-in-the-ui.cy.js
cypress/e2e/inventory/locations/item-locations.cy.js
cypress/e2e/inventory/moving-item-between-holdings.cy.js
cypress/e2e/inventory/moving-items-non-remote.cy.js
cypress/e2e/inventory/moving-items-remote.cy.js
cypress/support/fragments/inventory/item/itemRecordView.js

firebird-poppy-fixes

---

cypress/e2e/requests/create-new-request-for-Hold-type.cy.js

https://foliotest.testrail.io/index.php?/cases/view/545
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5107/allure/#behaviors

C545 Create new request for "Hold" type and check links to/from user and item (vega) (TaaS)

---

cypress/e2e/inventory/cataloging/edit-title-of-instance-with-source-folio.cy.js
cypress/support/fragments/inventory/instanceRecordEdit.js

[C3497](https://foliotest.testrail.io/index.php?/cases/view/3497)
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5125/allure/)

C3497 Edit the title of an instance which has Source FOLIO (no underlying MARC record in SRS) (folijet) (TaaS)

---

cypress/e2e/settings/tenant/num-of-locations-link-navigation.cy.js
cypress/support/fragments/settings/tenant/location-setup/libraries.js

[C399079](https://foliotest.testrail.io/index.php?/cases/view/399079)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5177/allure/#suites/204047e0fad7be0bb5a7b6c0b9323602/a474e87b45525a22/)

C399079 Verify that hyperlink "# of Locations" navigates to a list of Locations (firebird) (TaaS)

---

cypress/e2e/agreements/agreement-notes/assign-note-to-agreemnet.cy.js
cypress/e2e/agreements/agreement-notes/create-agreement-notes.cy.js
cypress/e2e/agreements/agreement-notes/delete-note.cy.js
cypress/e2e/agreements/agreement-notes/edit-agreement-notes.cy.js
cypress/e2e/agreements/agreement-notes/unassign-note-from-agreemnet.cy.js
cypress/e2e/agreements/agreement-notes/view-note-on-agreemnet.cy.js
cypress/e2e/settings/notes/view-note-type.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/settings/notes/noteTypes.js

[C380447](https://foliotest.testrail.io/index.php?/cases/view/380447)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5160/allure)
***

[380447] Settings | View a note type (spitfire) (TaaS)

---

cypress/e2e/settings/tenant/num-of-libraries-link-navigation.cy.js
cypress/support/fragments/settings/tenant/location-setup/campuses.js

[C399080](https://foliotest.testrail.io/index.php?/cases/view/399080)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5195/allure/#suites/204047e0fad7be0bb5a7b6c0b9323602/4ea2eca3546650d/)

C399080 Verify that hyperlink  "# of Libraries" navigates to a list of Libraries (firebird) (TaaS)

---

cypress/e2e/settings/tenant/hyperlinks-campuses.cy.js
cypress/support/fragments/settings/tenant/location-setup/institutions.js

[C398009](https://foliotest.testrail.io/index.php?/cases/view/398009)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5184/allure)

C398009 Verify that hyperlink '# of Campuses' navigates to a list of Campuses (firebird) (TaaS)

---

cypress/e2e/circulation-log/filtering-circulation-log-by-fee-fine-actions.cy.js

[FAT-1265](https://issues.folio.org/browse/FAT-1265)
***
[Filter circulation log by transferred partially](https://foliotest.testrail.io/index.php?/cases/view/17063)

FAT-1265/C17063

---

cypress/e2e/ideyalabs/orders/receiving-and-check-in/encumbrance-releases-with-payment-not-required-status.cy.js
cypress/e2e/orders/search-order-w-special-symbols.cy.js
cypress/support/fragments/orders/orderLines.js

[C380409](https://foliotest.testrail.io/index.php?/cases/view/380409)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5192/allure)
***

[380409] Search for order title with special characters (thunderjet) (TaaS)

---

cypress/e2e/export-manager/orders-export-to-a-vendor/set-daily-scheduling-for-new-integration.cy.js
cypress/support/fragments/exportManager/exportManagerSearchPane.js
cypress/support/fragments/organizations/index.js
cypress/support/fragments/organizations/integrations/integrationEditForm.js
cypress/support/fragments/organizations/integrations/integrationStates.js
cypress/support/fragments/organizations/integrations/integrationViewForm.js
cypress/support/fragments/organizations/integrations/integrations.js
cypress/support/fragments/organizations/organizationDetails.js
cypress/support/fragments/organizations/organizations.js

[C377048](https://foliotest.testrail.io/index.php?/cases/view/377048)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5255/allure)
***

[377048] Setting 'daily' scheduling on 12 PM (thunderjet) (TaaS)

---

cypress/e2e/invoices/remove-invoice-number-from-invoice-line-column.cy.js
cypress/support/fragments/invoices/index.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/invoices/invoiceView.js

[C350949](https://foliotest.testrail.io/index.php?/cases/view/350949)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5254/allure)
***

[350949] Remove 'Folio invoice number' from invoice line column (thunderjet) (TaaS)

---

cypress/e2e/consortia/view-user-affiliations-accordion.cy.js
cypress/support/api/users.js
cypress/support/fragments/users/users.js
cypress/support/fragments/users/usersCard.js
cypress/support/login.js

***
[FAT-9484](https://issues.folio.org/browse/FAT-9484)
***
[C380505: View a user's affiliations accordion in the third details pane(Consortia)](https://foliotest.testrail.io/index.php?/cases/view/380505)
***
[Allure](https://jenkins-aws.indexdata.com/job/Testing/job/Cypress_tests/5301/allure/)
***

Implementing of FAT-9484

---

cypress/e2e/bulk-edit/bulk-edit-landing-page-without-functional-permissions.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

https://foliotest.testrail.io/index.php?/cases/view/409430
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5259/allure/

C409430 Verify Bulk Edit app landing page without functional permissions (Firebird) (TaaS)

---

cypress/e2e/circulation-log/filtering-circulation-log-by-fee-fine-actions.cy.js
cypress/e2e/inventory/tags/find-tag-with-special-characters-using-api.cy.js
cypress/e2e/permissions/permission-sets/create-new-permission-set.cy.js
cypress/e2e/permissions/permission-sets/view-all-settings-allows-only-view-templates.cy.js
cypress/e2e/recieve-notice/patron-notice-duplication-works-as-expected.cy.js
cypress/support/fragments/settings/users/permissionSets.js

[FAT-1264](https://issues.folio.org/browse/FAT-1264)
***
[Check the Actions button from filtering Circulation log by transferred fully](https://foliotest.testrail.io/index.php?/cases/view/17062)

FAT-1264/C17062

---

cypress/e2e/fee-fine/check-the-entries-are-deleted-for-renewed-items.cy.js
cypress/support/fragments/users/lostItemsRequiringActualCostPage.js

[C375274](https://foliotest.testrail.io/index.php?/cases/view/375274) 
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5296/allure/)

C375274 Check that entries are deleted for renewed items (Declared lost items) (vega) (TaaS)

---

cypress/e2e/fee-fine/check-that-entries-are-deleted-for-returned-items.cy.js

[C375279](https://foliotest.testrail.io/index.php?/cases/view/375279)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5302/allure/)

C375279 Check that entries are deleted for returned items (Declared lost items) (vega) (TaaS)

---

cypress/e2e/inventory/search/advanced-or-not-search-in-holdings.cy.js
cypress/support/fragments/inventory/inventoryInstances.js

[C400619](https://foliotest.testrail.io/index.php?/cases/view/400619)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5327/allure/#suites)

C400619 Search Holdings using advanced search with "OR", "NOT" operators (spitfire) (TaaS)

---

cypress/e2e/requests/cancel-request.cy.js
cypress/support/fragments/requests/requestDetail.js

[C3533](https://foliotest.testrail.io/index.php?/cases/view/3533)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5388/allure)

C3533 Cancel request (vega) (TaaS)

---

cypress/e2e/inventory/search/advanced-search-in-holdings.cy.js
cypress/support/fragments/inventory/inventoryInstances.js

[C400617 ](https://foliotest.testrail.io/index.php?/cases/view/400617)
[report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5271/allure/#suites)

C400617 Search Holdings using advanced search with "AND" operator (spitfire) (TaaS)

---

cypress/e2e/marc-authority/ldr-length-tag-validation-when-creating-new-marcBib.cy.js

https://issues.folio.org/browse/FAT-9291
https://foliotest.testrail.io/index.php?/cases/view/380715

FAT-9291/C380715

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-narrow-down-options.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js
cypress/support/fragments/bulk-edit/bulk-edit-search-pane.js

[C356778](https://foliotest.testrail.io/index.php?/cases/view/356778)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5286/allure)

'C356778 Verify narrow down options dropdown choices on Items in-app bulk edit form (firebird) (TaaS)'

---

cypress/e2e/settings/tenant/tenant-general-html-title.cy.js
cypress/e2e/settings/tenant/tenant-location-setup-html-title.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/settings/tenant/servicePoints/servicePoints.js
cypress/support/fragments/settings/tenant/tenantPane.js

[C410826](https://foliotest.testrail.io/index.php?/cases/view/410826)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5390/allure)

C410826 Verify "Tenant -> General" settings HTML page title format (firebird) (TaaS)

---

cypress/e2e/orders/edit-account-number-in-po-line.cy.js
cypress/support/fragments/orders/index.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderLineEditForm.js
cypress/support/fragments/orders/orderStates.js
cypress/support/fragments/organizations/newOrganization.js

[C358545](https://foliotest.testrail.io/index.php?/cases/view/358545)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5450/allure)
***

[358545] User can select account number (thunderjet) (TaaS)

---

cypress/e2e/orders/open-order-from-pol-edit-form.cy.js
cypress/support/fragments/orders/modals/unopenConfirmationModal.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderLineEditForm.js
cypress/support/fragments/settings/orders/openOrder.js
cypress/support/utils/interactorsTools.js

[C6531](https://foliotest.testrail.io/index.php?/cases/view/6531)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5478/allure)
***

[6531] Save and open PO from POL create or edit form (thunderjet) (TaaS)

---

cypress/e2e/marc-authority/create-new-marc-bib-verify-focus-behavior.cy.js
cypress/support/e2e.js
cypress/support/fragments/inventory/inventoryHotkeys.js
cypress/support/fragments/inventory/inventoryKeyboardShortcuts.js
cypress/support/fragments/quickMarcEditor.js
interactors/textarea.js
package.json

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/380717)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5487/allure/)

C380717 Verify focus behavior when using field level action icons upon creation of a new "MARC bib" record

---

cypress/e2e/orders/renewal-field-prefilled-from-template.cy.js
cypress/support/fragments/orders/orderEditForm.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderLineEditForm.js
cypress/support/fragments/orders/orderStates.js
cypress/support/fragments/orders/orders.js
cypress/support/fragments/settings/orders/index.js
cypress/support/fragments/settings/orders/orderTemplates.js

[C353575](https://foliotest.testrail.io/index.php?/cases/view/353575)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5490/allure)
***

[353575] Renewal note field is prefilled from order template (thunderjet) (TaaS)

---

cypress/e2e/invoices/initial-encumbrance-remain-the same-after-cancelling-related-invoice.cy.js
cypress/support/fragments/invoices/invoices.js

[C400614](https://foliotest.testrail.io/index.php?/cases/view/400614)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5499/allure)
***

[400614] Encumbrance amount remains the same (thunderjet) (TaaS)

---

cypress/e2e/invoices/settings/voucher-export-not-present-in-actions-if-no-permissions.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/invoices/invoices.js

[C353222](https://foliotest.testrail.io/index.php?/cases/view/353222)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5495/allure)
***

[353222] Run batch export with NO Voucher export permission (thunderjet) (TaaS)

---

cypress/e2e/inventory/search/search-option-dropdown-doesnt-reset-value-after-cleared-search-box.cy.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

https://foliotest.testrail.io/index.php?/cases/view/353938
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5376/

C353938 Verify that the search option dropdown doesn't reset selected value after user cleared search box (Spitfire)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-icon.cy.js

https://foliotest.testrail.io/index.php?/cases/view/396401

C396401 Verify reset state after clicking "Bulk edit" icon from the bulk edit In app form (firebird) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-special-chars.cy.js

https://foliotest.testrail.io/index.php?/cases/view/368481

C368481 Verify that there no errors during bulk editing Holdings with special characters (firebird) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-email-partial.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

https://foliotest.testrail.io/index.php?/cases/view/365590

C365590 Verify that User\'s Email can be edited partially (firebird) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-holdings-sourse-null.cy.js

https://foliotest.testrail.io/index.php?/cases/view/380592

C380592 Verify that Holdings without "Source" populated can be updated(firebird) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-deleted-user.cy.js
cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-user-changed-progress-bar.cy.js

https://foliotest.testrail.io/index.php?/cases/view/409432

C409432 Verify progressbar starting bulk edit by changed identifiers_Users (firebird) (TaaS)

---

cypress/e2e/invoices/upload-file-to-invoice.cy.js
cypress/support/fragments/invoices/invoiceEditForm.js
cypress/support/fragments/invoices/invoiceView.js

[C15856](https://foliotest.testrail.io/index.php?/cases/view/15856)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5457/allure)

C15856 Upload file to invoice (thunderjet) (TaaS)

---

cypress/e2e/title-level-request/edit-recall-request.cy.js
cypress/support/fragments/circulation-log/searchPane.js
cypress/support/fragments/inventory/item/itemRecordView.js
cypress/support/fragments/requests/edit-request.js
cypress/support/fragments/requests/requestDetail.js
cypress/support/fragments/users/loans/renewConfirmationModal.js

[C380500](https://foliotest.testrail.io/index.php?/cases/view/380500)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5476/allure/)

C380500: Editing recall request does not change recalled item (vega) (TaaS)

---

cypress/e2e/export-manager/export-orders-in-edifact-format/job-type-filter-has-valid-options-list.cy.js
cypress/support/fragments/exportManager/exportManagerSearchPane.js
cypress/support/fragments/organizations/integrations/integrations.js

[C378884](https://foliotest.testrail.io/index.php?/cases/view/378884)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5532/allure)
***

[378884] "EDIFACT" option is added to job type filter (thunderjet) (TaaS)

---

cypress/e2e/circulation-log/filtering-circulation-log-by-fee-fine-actions.cy.js
cypress/e2e/circulation-log/users-can-select-filters-but-not-actions-menus.cy.js
cypress/e2e/circulation-log/verify-service-point-in-circ-history.cy.js
cypress/e2e/inventory/tags/find-tag-with-special-characters-using-api.cy.js
cypress/e2e/permissions/save-is-disabled-in-case-of-errors-on-my-profile.cy.js
cypress/support/fragments/settings/users/permissionSets.js

[FAT-9633](https://issues.folio.org/browse/FAT-9633)

Volaris autotests maintenance

---

cypress/e2e/invoices/approve-invoice-when-balance-is-close-to-encumbrance.cy.js
cypress/e2e/invoices/initial-encumbrance-remain-the same-after-cancelling.cy.js
cypress/support/fragments/invoices/invoiceLineEditForm.js

[C399092](https://foliotest.testrail.io/index.php?/cases/view/399092)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5516/allure)
***

[399092] Encumbrance amount remains the same (thunderjet) (TaaS)

---

cypress/e2e/eholdings/package/eholdings-packages-export-sort.cy.js
cypress/support/fragments/eholdings/eHoldingsPackageView.js
cypress/support/fragments/eholdings/modals/filterTitlesModal.js
cypress/support/fragments/exportManager/exportManagerSearchPane.js

[C366591](https://foliotest.testrail.io/index.php?/cases/view/366591)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5536/allure)
***

[366591] Verify rows in exported file sorted alphabetically (spitfire) (TaaS)

---

cypress/e2e/fee-fine/input-incorrect-value-to-bill-actual-cost.cy.js
cypress/support/fragments/users/billActualCostModal.js
cypress/support/fragments/users/lostItemsRequiringActualCostPage.js

[C374123](https://foliotest.testrail.io/index.php?/cases/view/374123)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5541/allure)

C374123 Verify ability to input incorrect value to bill actual cost for item with "Declared lost" status (vega) (TaaS)

---

cypress/e2e/eholdings/package/eholdings-export-package-with-10k-plus.cy.js
cypress/e2e/eholdings/package/eholdings-export-selected-package-without-titles.cy.js
cypress/e2e/eholdings/package/eholdings-packages-export-selected.cy.js
cypress/e2e/eholdings/package/eholdings-packages-export-sort.cy.js
cypress/e2e/eholdings/package/eholdings-packages-export.cy.js
cypress/e2e/eholdings/package/eholdings-packages-titles.cy.js
cypress/e2e/eholdings/title+package/export-not-selected-package+title.cy.js
cypress/e2e/eholdings/title+package/export-package+title-with-user-selected-fields.cy.js
cypress/support/fragments/eholdings/eHoldingsPackageView.js
cypress/support/fragments/eholdings/eHoldingsPackages.js
cypress/support/fragments/eholdings/eHoldingsResourceView.js
cypress/support/fragments/eholdings/modals/exportSettingsModal.js
cypress/support/fragments/exportManager/exportManagerSearchPane.js
interactors/list.js

[C354000](https://foliotest.testrail.io/index.php?/cases/view/354000)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5555/allure)
***

[354000] Export all selected titles in a "Package" (spitfire) (TaaS)

---

cypress/e2e/finance/funds/multiple-budgets-for-same-fund.cy.js
cypress/support/constants.js
cypress/support/fragments/finance/funds/fundDetails.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/finance/modals/addBudgetModal.js
cypress/support/fragments/finance/states.js

[C353527](https://foliotest.testrail.io/index.php?/cases/view/353527)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5608/allure)
***

[353527] Allow user to create multiple planned budgets (thunderjet) (TaaS)

---

cypress/e2e/finance/funds/transfer-allocation-between-funds.cy.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/funds/fundDetails.js
cypress/support/fragments/finance/index.js
cypress/support/fragments/finance/modals/addTransferModal.js
cypress/support/fragments/finance/states.js
cypress/support/fragments/finance/transfer/transfers.js

[C375066](https://foliotest.testrail.io/index.php?/cases/view/375066)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5615/allure)
***

[375066] Money transfer between funds (thunderjet) (TaaS)

---

cypress/e2e/eholdings/package/eholdings-packages-titles.cy.js
cypress/e2e/eholdings/package/eholdings-packages.cy.js
cypress/e2e/eholdings/title+package/eholdings-titles-packages-export-selected.cy.js
cypress/e2e/eholdings/title+package/export-not-selected-package+title.cy.js
cypress/e2e/eholdings/title+package/export-package+title-with-user-selected-fields.cy.js
cypress/support/fragments/eholdings/eHoldingsPackageView.js
cypress/support/fragments/eholdings/eHoldingsPackages.js
cypress/support/fragments/eholdings/eHoldingsResourceView.js

[C354001](https://foliotest.testrail.io/index.php?/cases/view/354001)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5555/allure)
***

[354001] Export all selected titles in a "Title+Package" (spitfire) (TaaS)

---

cypress/e2e/finance/fiscalYears/calulate-available-balance-for-negative-amount.cy.js
cypress/support/fragments/finance/fiscalYears/fiscalYearDetails.js
cypress/support/fragments/finance/fiscalYears/fiscalYears.js

[C375283](https://foliotest.testrail.io/index.php?/cases/view/375283)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5621/allure)
***

[375283] Available balance at the fiscal year level is calculated correctly (thunderjet) (TaaS)

---

cypress/e2e/marc-authority/record-opens-heading-reference-value-clicked-highlighted-row.cy.js

[Test Rail](https://foliotest.testrail.io/index.php?/cases/view/375089)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5635/)

C375089 View Authority Record: record opens in third pane when "Heading/Reference" value clicked for highlighted row (spitfire)

---

cypress/e2e/circulation-log/verify-icon-in-action-column.cy.js
cypress/support/fragments/circulation-log/searchResults.js

[C368490](https://foliotest.testrail.io/index.php?/cases/view/368490)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5491/allure/)

C368490 Verify the icon "..." in "Actions" column (volaris) (TaaS)

---

cypress/e2e/finance/funds/transfer-allocation-between-funds.cy.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/modals/addTransferModal.js

[C374183](https://foliotest.testrail.io/index.php?/cases/view/374183)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5651/allure)
***

[374183] Money transfer between funds (thunderjet) (TaaS)

---

cypress/e2e/fee-fine/check-buttons-manual-patron-blocks.cy.js
cypress/support/api/blocks.js
cypress/support/fragments/users/usersCard.js

[C374700](https://foliotest.testrail.io/index.php?/cases/view/374700)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5701/allure)

C374700 Verify buttons layout editing manual Patron blocks (vega) (TaaS)

---

cypress.config.js
cypress/e2e/finance/ledgers/export-ledger-w-different-fund-content.cy.js
cypress/support/fragments/finance/ledgers/ledgerDetails.js
cypress/support/fragments/finance/modals/exportBudgetModal.js
cypress/support/fragments/finance/states.js

[C350963](https://foliotest.testrail.io/index.php?/cases/view/350963)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5694/allure)
***

[350963] User can export Ledger with different Funds content (thunderjet) (TaaS)

---

cypress/e2e/loans/single-loan.cy.js
cypress/support/fragments/loans/changeDueDateForm.js

[C565](https://foliotest.testrail.io/index.php?/cases/view/565)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5703/allure/)

C565 Single loan: Test change due date (vega) (TaaS)

---

cypress/e2e/invoices/add-invoice-line-from-pol-w-inactive-budget.cy.js
cypress/e2e/invoices/fiscal-year-specifies-expecse-class-selection.cy.js
cypress/e2e/invoices/release-encumbrance-checkbox-is-not-checked.cy.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/invoices/modal/selectOrderLinesModal.js

[C353572](https://foliotest.testrail.io/index.php?/cases/view/353572)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5705/allure)
***

[353572] Saving invoice line from POL with inactive budget (thunderjet) (TaaS)

---

cypress/e2e/orders/encumbered-amount-is-not-changed-after-deleting-received-piece.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/receiving/receiving.js

[C375110](https://foliotest.testrail.io/index.php?/cases/view/375110)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5719/allure)
***

C375110: Encumbered amount is not changed after deleting received piece when related approved invoice exists (thunderjet) (TaaS)

---

cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-when-po-line-contains-two-fund-distributions.cy.js
cypress/support/fragments/finance/ledgers/ledgerRolloverDetails.js
cypress/support/fragments/finance/ledgers/ledgerRolloverInProgress.js
cypress/support/fragments/finance/transactions/transactions.js

[C397990](https://foliotest.testrail.io/index.php?/cases/view/397990)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5712/allure)
***

[397990] Rollover when PO line contains two fund distributions (thunderjet) (TaaS)

---

cypress/e2e/loans/loans-actions-while-claim-returned.cy.js
cypress/e2e/title-level-request/edit-recall-request.cy.js
cypress/support/fragments/loans/changeDueDateForm.js
cypress/support/fragments/users/loans/renewConfirmationModal.js
cypress/support/fragments/users/loans/userLoans.js
cypress/support/fragments/users/userDefaultObjects/loanDetails.js

[C10958](https://foliotest.testrail.io/index.php?/cases/view/10958)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5711/allure)

C10958 Loans: Actions while Claimed returned (vega) (TaaS)

---

cypress/e2e/loans/renewal-failure-not-loanable.cy.js
cypress/support/fragments/users/loans/overrideAndRenewModal.js
cypress/support/fragments/users/loans/renewConfirmationModal.js

[C15492](https://foliotest.testrail.io/index.php?/cases/view/15492)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5731/allure/)

C15492 Renewal: failure because loan was not loanable (vega) (TaaS)

---

cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-when-po-line-contains-two-fund-distributions.cy.js
cypress/e2e/orders/delete-fund-in-pol-w-reviewed-invoice.cy.js
cypress/support/constants.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/transactions/transactions.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/invoices/invoiceView.js
cypress/support/fragments/invoices/invoices.js
cypress/support/fragments/orders/orderLineEditForm.js

[C374191](https://foliotest.testrail.io/index.php?/cases/view/374191)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5727/allure)
***

[374191] Deleting fund distribution in PO line (thunderjet) (TaaS)

---

cypress/e2e/inventory/instance/cancelling-creation-order-from-instance-record.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/modals/newOrderModal.js

https://foliotest.testrail.io/index.php?/cases/view/353992
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5696/

C353992 Cancelling creation an order from instance record (thunderjet) (TaaS)

---

cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-with-multiple-001-fields.cy.js
cypress/support/fragments/quickMarcEditor.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/380699)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5717/allure/)

C380699 Add multiple 001s when creating MARC Bibliographic record (Spitfire) (TaaS)

---

cypress/e2e/marc/marc-bibliographic/create-new-marc-bib/create-new-marc-bib-008-field-validation.cy.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/387449)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5769/allure/)

C387449 008 field existence validation when create new MARC bib (spitfire) (TaaS)

---

cypress/e2e/consortia/affiliation-in-central-tenant-is-automatically-added.cy.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/users/users.js

[C387512](https://foliotest.testrail.io/index.php?/cases/view/387512)
***
[FAT-9489](https://issues.folio.org/browse/FAT-9489)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5803/allure)
***

Implementing of FAT-9489

---

cypress/e2e/orders/section-w-validation-errors-remains-expanded.cy.js
cypress/support/fragments/orders/orderEditForm.js
interactors/section.js
interactors/select.js

[C353592](https://foliotest.testrail.io/index.php?/cases/view/353592)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5759/allure)
***

[353592] Verify validation errors expanded (thunderjet) (TaaS)

---

cypress/e2e/orders/copy-icon-present-on-po-and-pol-panes.cy.js
cypress/support/clipboard.js
cypress/support/e2e.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderLineDetails.js

[C353661](https://foliotest.testrail.io/index.php?/cases/view/353661)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5811/allure)
***

[353661] 'Copy' icon is added to PO & POL number (thunderjet) (TaaS)

---

cypress/support/fragments/orders/orderLineEditForm.js

[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5853/allure)
***

[FIX] Opening of OrderLine edit form

---

cypress/e2e/invoices/approve-invoice-when-balance-is-close-to-encumbrance.cy.js
cypress/e2e/invoices/cancel-invoice-created-in-current-fy-and-paid-against-previous-fy.cy.js
cypress/e2e/invoices/fiscal-year-specifies-expecse-class-selection.cy.js
cypress/e2e/invoices/initial-encumbrance-remain-the same-after-cancelling.cy.js
cypress/e2e/invoices/initial-encumbrance-remain-the-same-after-cancelling-related-invoice.cy.js
cypress/e2e/invoices/pay-invoice-for-previous-fy.cy.js
cypress/e2e/orders/edit-fund-when-invoice-has-multiple-fund-distributions.cy.js
cypress/e2e/orders/encumbrance-released-when-order-closed.cy.js
cypress/e2e/orders/open-order-having-po-line-with-two-fund-distributions.cy.js
cypress/e2e/orders/open-order-when-ledger-has-separate-aq-unit.cy.js
cypress/support/fragments/invoices/invoiceLineDetails.js
cypress/support/fragments/invoices/invoiceLineEditForm.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderLineEditForm.js

[C375227](https://foliotest.testrail.io/index.php?/cases/view/375227)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5803/allure)
***

[375227] Editing fund distribution in PO line (thunderjet) (TaaS)

---

cypress/e2e/checkout/checkout.note-and-columns.cy.js
cypress/support/fragments/check-out-actions/check-out-actions.js
cypress/support/fragments/check-out-actions/checkOutModal.js

[C778](https://foliotest.testrail.io/index.php?/cases/view/778)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5771/allure)

C778 Check out: check out note and columns on "Scan items" pane (vega) (TaaS)

---

cypress/e2e/loans/loans-declared-lost.cy.js
cypress/support/fragments/loans/changeDueDateForm.js
cypress/support/fragments/loans/loansPage.js
cypress/support/fragments/users/loans/overrideAndRenewModal.js
cypress/support/fragments/users/loans/renewConfirmationModal.js
cypress/support/fragments/users/loans/userLoans.js

[C9192](https://foliotest.testrail.io/index.php?/cases/view/9192)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5622/allure)

C9192 Loans: Actions while declared lost (vega) (TaaS)

---

cypress/e2e/fee-fine/verify-added-info-on-lost-item-page.cy.js
cypress/support/fragments/users/lostItemsRequiringActualCostPage.js

[C365613](https://foliotest.testrail.io/index.php?/cases/view/365613)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5850/allure)

C365613 Verify additional information in "Patron" column on the "Lost items requiring actual cost" page (vega) (TaaS)

---

cypress/e2e/orders/receiving-and-check-in/create-new-holding-for-existing-location.cy.js
cypress/support/fragments/inventory/index.js
cypress/support/fragments/receiving/modals/editPieceModal.js
cypress/support/fragments/receiving/receivingDetails.js
cypress/support/fragments/receiving/receivingStates.js
interactors/label.js

[C375242](https://foliotest.testrail.io/index.php?/cases/view/375242)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5898/allure)
***

[375242] Create new holdings for already existing location (thunderjet) (TaaS)

---

cypress/e2e/bulk-edit/in-app/bulk-edit-in-app-verify-user-cannot-click-on-commit-changes-button.cy.js
cypress/support/fragments/bulk-edit/bulk-edit-actions.js

[C360949](https://foliotest.testrail.io/index.php?/cases/view/360949)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5855/allur)

      'C360949 Verify that User cannot click on "Commit changes"  until preview is completed (firebird) (TaaS)'

---

cypress/e2e/inventory/instance/check-classification-types-list.cy.js
cypress/support/fragments/inventory/instanceRecordEdit.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/settings/inventory/classification-types/classificationTypes.js
cypress/support/fragments/settings/inventory/index.js
interactors/section.js
interactors/select.js

[C618](https://foliotest.testrail.io/index.php?/cases/view/618)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5865/allure)
***

[618] Classification types (folijet) (TaaS)

---

cypress/e2e/checkin/check-in-claimed-returned-items.cy.js
cypress/e2e/checkin/check-in-item-with-open-request.cy.js
cypress/e2e/circulation-log/circulation-log-barcodes.cy.js
cypress/e2e/circulation-log/filtering-circulation-log-by-loan-actions.cy.js
cypress/e2e/inventory/call-number/browse-call-number-wo-specified-call-number-type.cy.js
cypress/e2e/inventory/instance/multiple-items-in-holding-record.cy.js
cypress/e2e/loans/export-loans.cy.js
cypress/e2e/loans/loan-details.cy.js
cypress/e2e/loans/loans-claim-returned.cy.js
cypress/e2e/loans/multiple-loans.cy.js
cypress/e2e/title-level-request/user-can-move-title-level-request-from-one-item-to-another.cy.js
cypress/e2e/users/loans/manual-anonymization-closed-loans.cy.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js

[C196761](https://foliotest.testrail.io/index.php?/cases/view/196761)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5885/allure)
***

[196761] Instance holdings accordion display (folijet) (TaaS)

---

cypress/e2e/invoices/copy-icon-present-invoice-pane.cy.js
cypress/support/fragments/invoices/invoiceView.js

[C353944](https://foliotest.testrail.io/index.php?/cases/view/353944)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5896/allure)
***

[353944] Copy' icon is added to invoice number (thunderjet) (TaaS)

---

cypress/e2e/checkin/check-in-items-at-service-points.cy.js
cypress/e2e/checkin/check-in-multipiece-items.cy.js
cypress/e2e/checkin/check-in-service-point-not-assigned.cy.js
cypress/e2e/checkin/checkin-note-is-readable.cy.js
cypress/e2e/circulation-log/loan-periods.cy.js
cypress/e2e/loans/loan-dates.cy.js
cypress/e2e/loans/lost-loans.cy.js
cypress/e2e/orders/receiving-and-check-in/copy-number-not-shown-in-receiving.cy.js
cypress/e2e/orders/receiving-and-check-in/create-new-holding-for-existing-location.cy.js
cypress/e2e/users/loans/manual-anonymization-closed-loans.cy.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/item/itemRecordEdit.js
cypress/support/fragments/inventory/item/itemRecordView.js
cypress/support/fragments/orders/basicOrderLine.js
cypress/support/fragments/receiving/receivingDetails.js
cypress/support/fragments/receiving/receivingsListEditForm.js

[C374137](https://foliotest.testrail.io/index.php?/cases/view/374137)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5900/allure)
***

[374137] 'Copy number' is not shown in receiving (thunderjet) (TaaS)

---

cypress/e2e/organizations/check-organizations-table-content.cy.js
cypress/e2e/organizations/create-organization.cy.js
cypress/e2e/organizations/edit-organization.cy.js
cypress/e2e/organizations/filter-organization.cy.js
cypress/e2e/organizations/test-acquisition-unit-for-organizations.cy.js
cypress/e2e/organizations/view-existing-record.cy.js
cypress/support/fragments/organizations/organizations.js

[C369086](https://foliotest.testrail.io/index.php?/cases/view/369086)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5911/allure)
***

[369086] Check 'Name' column has link (thunderjet) (TaaS)

---

cypress/e2e/orders/encumbered-amount-is-not-changed-after-deleting-received-piece-when-order-closed.cy.js
cypress/support/fragments/orders/check-in/checkIn.js
cypress/support/fragments/orders/index.js
cypress/support/fragments/orders/pieces/pieces.js
cypress/support/fragments/receiving/modals/deletePieceModal.js
cypress/support/fragments/receiving/modals/editPieceModal.js
cypress/support/fragments/receiving/receivingDetails.js
cypress/support/fragments/receiving/receivingStates.js

[C375985](https://foliotest.testrail.io/index.php?/cases/view/375985)
[C375986](https://foliotest.testrail.io/index.php?/cases/view/375986)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5974/allure)
***

[375985] Encumbered amount is not changed after deleting received piece (thunderjet) (TaaS)

---

cypress/e2e/orders/edit-fund-when-invoice-paid-cancelled.cy.js
cypress/support/fragments/finance/transactions/transactionDetails.js
cypress/support/fragments/invoices/invoices.js
interactors/index.js
interactors/popover.js

[C368484](https://foliotest.testrail.io/index.php?/cases/view/368484)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5940/allure)
***

[368484] Editing fund distribution in PO line (thunderjet) (TaaS)

---

cypress/e2e/orders/edit-fund-when-invoice-paid-cancelled.cy.js

[C368477](https://foliotest.testrail.io/index.php?/cases/view/368477)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5962/allure)
***

[368477] Editing fund distribution in PO line (thunderjet) (TaaS)

---

cypress/e2e/marc/marc-bibliographic/edit-marc-bib/edit-marc-bib-add-multiple-001s.cy.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/387458)
[AllureReport](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5867/allure/)

C387458 Add multiple 001s when editing MARC Bibliographic record (spitfire)(TaaS)

---

cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-for-same-fy-can-be-started-only-once.cy.js
cypress/support/fragments/finance/ledgers/ledgerRolloverDetails.js
cypress/support/fragments/finance/ledgers/ledgerRollovers.js

[C360956](https://foliotest.testrail.io/index.php?/cases/view/360956)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6044/allure)
***

[360956] Rollover for one ledger and same fiscal year (thunderjet) (TaaS)

---

cypress/e2e/orders/search-instance-results-cleared-after-click-reset.cy.js
cypress/support/fragments/orders/modals/selectInstanceModal.js
cypress/support/fragments/orders/orderLineEditForm.js

[C377043](https://foliotest.testrail.io/index.php?/cases/view/377043)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6025/allure)
***

[377043] Plugin search result list is cleared (thunderjet) (TaaS)

---

cypress/e2e/inventory/item/can-search-item-having-barcode-w-slash.cy.js
cypress/support/fragments/inventory/index.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

[C423380](https://foliotest.testrail.io/index.php?/cases/view/423380)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6045/allure)
***

[423380] Check that item barcodes with slashes can be searched (folijet) (TaaS)

---

cypress/e2e/orders/edit-fund-and-decrease-cost-in-po-line-for-paid-invoice.cy.js

[C404443](https://foliotest.testrail.io/index.php?/cases/view/404443)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5999/allure)
***

[404443] Editing fund distribution and decreasing cost (thunderjet) (TaaS)

---

cypress/e2e/eholdings/package/eholdings-packages.cy.js
cypress/e2e/eholdings/title+package/add-agreement-to-package.cy.js
cypress/e2e/eholdings/title+package/eholdings-titles.cy.js
cypress/support/dictionary/permissions.js
cypress/support/fragments/eholdings/eHoldingsPackage.js
cypress/support/fragments/eholdings/eHoldingsPackages.js
cypress/support/fragments/eholdings/eHoldingsProviders.js
cypress/support/fragments/eholdings/eHoldingsResourceView.js
cypress/support/fragments/eholdings/eHoldingsTitle.js
cypress/support/fragments/eholdings/eHoldingsTitles.js
cypress/support/fragments/eholdings/eholdingsConstants.js
cypress/support/fragments/eholdings/modals/filterPackagesModal.js
cypress/support/fragments/eholdings/modals/selectAgreementModal.js
cypress/support/fragments/topMenuNavigation.js

[C752](https://foliotest.testrail.io/index.php?/cases/view/752)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6039/allure)
***

[752] Add an 'Agreement' and attach a title in a package (spitfire) (TaaS)

---

cypress/e2e/finance/transactions/allocation-amount-is-not-displayed-in-financial-summary.cy.js
cypress/e2e/finance/transactions/moving-allocation.cy.js
cypress/e2e/finance/transactions/unrelease-encumbrance.cy.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/budgets/budgets.js
cypress/support/fragments/finance/financeHelper.js
cypress/support/fragments/finance/fiscalYears/fiscalYears.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/finance/ledgers/ledgerDetails.js
cypress/support/fragments/finance/ledgers/ledgers.js
cypress/support/fragments/finance/modals/addTransferModal.js
cypress/support/fragments/finance/states.js

[C360116](https://foliotest.testrail.io/index.php?/cases/view/360116)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6064/allure)
***

[360116] 'Increase/decrease in allocation' amounts for funds (thunderjet) (TaaS)

---

cypress/e2e/orders/reopen-order-w-multiple-order-lines.cy.js
cypress/support/fragments/orders/modals/closeConfirmationModal.js
cypress/support/fragments/orders/orderDetails.js
cypress/support/fragments/orders/orderStates.js

[C366113](https://foliotest.testrail.io/index.php?/cases/view/366113)
[C366114](https://foliotest.testrail.io/index.php?/cases/view/366114)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6066/allure)
***

[366113] Order can be reopened (thunderjet) (TaaS)

---

cypress/e2e/title-level-request/request-goes-to-fulfillment-in-progress.cy.js
cypress/support/fragments/requests/requestDetail.js

[C350426](https://foliotest.testrail.io/index.php?/cases/view/350426)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6042/allure)

C350426: Check that request goes to "Fulfillment in progress" if the items status has changed to "Awaiting pickup" (vega) (TaaS)

---

cypress/e2e/checkin/check-in-notes.cy.js
cypress/e2e/checkout/checkout.note-and-columns.cy.js
cypress/e2e/circulation-log/check-date-and-time-requests.cy.js
cypress/support/fragments/requests/requestDetail.js
cypress/support/utils/dateTools.js

[C350711](https://foliotest.testrail.io/index.php?/cases/view/350711)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/5959/allure)

C350711 Check date and time --requests (volaris) (TaaS)

---

cypress/e2e/title-level-request/request-statuses-when-placing-item-title-request.cy.js
cypress/support/fragments/requests/requestDetail.js

[C350740](https://foliotest.testrail.io/index.php?/cases/view/350740)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6006/allure/)

C350740 Check request statuses when placing item and title level requests (vega) (TaaS)

---

cypress/e2e/eholdings/filter-by-tags-is-hidden.cy.js
cypress/support/fragments/eholdings/eHoldingsSearch.js
interactors/section.js

[C359011](https://foliotest.testrail.io/index.php?/cases/view/359011)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6065/allure)
***

[359011] 'Filter by Tag' option doesn't show (spitfire) (TaaS)

---

cypress/e2e/orders/location-dd-in-order-line-allows-parentheses.cy.js
cypress/support/fragments/orders/orderLineEditForm.js
interactors/selection.js

[C367957](https://foliotest.testrail.io/index.php?/cases/view/367957)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6078/allure)
***

[367957] Orders POL location dropdown search (thunderjet) (TaaS)

---

cypress/e2e/orders/item-status-changed-to-order-closed.cy.js
cypress/support/fragments/orders/modals/cancelConfirmationModal.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderLines.js
cypress/support/fragments/orders/orderStates.js

[C367963](https://foliotest.testrail.io/index.php?/cases/view/367963)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6082/allure)
***

[367963] Linked item status is updated to 'Order closed' (thunderjet) (TaaS)

---

cypress/e2e/finance/funds/add-donor-information-to-fund.cy.js
cypress/support/fragments/finance/funds/fundDetails.js
cypress/support/fragments/finance/funds/fundEditForm.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/finance/index.js
cypress/support/fragments/finance/modals/addDonorsModal.js
cypress/support/fragments/finance/states.js
cypress/support/fragments/organizations/newOrganization.js
interactors/modal.js
interactors/multi-column-list.js
interactors/section.js

[C422161](https://foliotest.testrail.io/index.php?/cases/view/422161)
[C422162](https://foliotest.testrail.io/index.php?/cases/view/422162)
[C422194](https://foliotest.testrail.io/index.php?/cases/view/422194)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6137/allure)
***
Note: Test is failing due to regression issue

[422161] Add donor information to a Fund (thunderjet) (TaaS)

---

cypress/e2e/consortia/create-local-marc-bib-in-member.cy.js
cypress/support/fragments/inventory/inventoryInstance.js

https://issues.folio.org/browse/FAT-9622
https://foliotest.testrail.io//index.php?/cases/view/422124

FAT-9622/C422124-Consortia

---

cypress/e2e/title-level-request/tlr-section-on-request-detail-page.cy.js
cypress/support/fragments/requests/newRequest.js

[C357532](https://foliotest.testrail.io/index.php?/cases/view/357532)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6069/allure)

C357532 Check that "Title level requests" section on Request Detail page and New Request page counted correctly (vega) (TaaS)

---

cypress/e2e/title-level-request/user-can-create-item-level-request-from-user-app.cy.js
cypress/support/fragments/users/usersCard.js

[C350423](https://foliotest.testrail.io/index.php?/cases/view/350423)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6084/allure)

C350423 Check that user can create Item level request from User app (use Request accordion) (vega) (TaaS)

---

cypress/e2e/title-level-request/request-statuses-when-placing-item-title-request.cy.js
cypress/e2e/title-level-request/user-directed-to-request-queue-with-correct-number-of-requests-displayed.cy.js
cypress/support/fragments/requests/requestDetail.js
cypress/support/fragments/requests/requests.js

[C350557](https://foliotest.testrail.io/index.php?/cases/view/350557)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6149/allure)

C350557 Check that the user directed to Request queue with correct number of requests displayed (vega) (TaaS)

---

cypress/e2e/finance/funds/remove-donor-from-fund.cy.js
cypress/support/fragments/finance/funds/fundEditForm.js

[C422212](https://foliotest.testrail.io/index.php?/cases/view/422212)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6166/allure)
***

[422212] Remove donor from fund (thunderjet) (TaaS)

---

cypress/e2e/requests/complete-request-workflow-steps-to-validate-status-and-filtering.cy.js
cypress/support/fragments/requests/requestDetail.js
cypress/support/fragments/users/usersCard.js

[C557](https://foliotest.testrail.io/index.php?/cases/view/557)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6210/allure)

C557 Complete request workflow steps to validate status change and filtering (vega) (TaaS)

---

cypress/e2e/finance/fiscalYears/calulate-available-balance-for-negative-amount.cy.js
cypress/e2e/finance/fiscalYears/fiscalYearRollover/encumbrances-are-rolled-over-correctly.cy.js
cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-based-on-remaining-for-paid-invoice.cy.js
cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-for-same-fy-can-be-started-only-once.cy.js
cypress/e2e/finance/fiscalYears/fiscalYearRollover/rollover-when-po-line-contains-two-fund-distributions.cy.js
cypress/e2e/finance/ledgers/export-ledger-w-different-fund-content.cy.js
cypress/e2e/finance/transactions/allocation-amount-is-not-displayed-in-financial-summary.cy.js
cypress/e2e/finance/transactions/rollover-transfer-amount-included-in-summary.cy.js
cypress/support/fragments/finance/financeDetails.js
cypress/support/fragments/finance/financeHelper.js
cypress/support/fragments/finance/fiscalYears/fiscalYearDetails.js
cypress/support/fragments/finance/fiscalYears/fiscalYears.js
cypress/support/fragments/finance/funds/funds.js
cypress/support/fragments/finance/groups/groupDetails.js
cypress/support/fragments/finance/groups/groups.js
cypress/support/fragments/finance/index.js
cypress/support/fragments/finance/ledgers/ledgerDetails.js
cypress/support/fragments/finance/ledgers/ledgerRollovers.js

[C375980](https://foliotest.testrail.io/index.php?/cases/view/375980)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6191/allure)
***

[375980] Rollover transfer amounts are included in Group (thunderjet) (TaaS)

---

cypress/e2e/finance/funds/decrease-allocation-result-in-negative-amount.cy.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/modals/addTransferModal.js
cypress/support/fragments/finance/states.js
cypress/support/fragments/finance/transfer/constants.js

[C414970](https://foliotest.testrail.io/index.php?/cases/view/414970)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6172/allure)
***

[414970] Decrease allocation resulting in a negative amount (thunderjet) (TaaS)

---

cypress/e2e/orders/delete-fund-in-pol-w-reviewed-invoice.cy.js
cypress/e2e/orders/electronic-format-fields-cleared-when-change-format-to-physical.cy.js
cypress/e2e/orders/encumbrance-released-when-order-closed.cy.js
cypress/e2e/orders/inventory-interaction/edit-instance-connection.cy.js
cypress/e2e/orders/unrelease-encumbrances-when-reopen-one-time-order.cy.js
cypress/support/fragments/inventory/inventoryInstance.js
cypress/support/fragments/inventory/inventoryInstances.js
cypress/support/fragments/orders/modals/changeInstanceModal.js
cypress/support/fragments/orders/modals/selectInstanceModal.js
cypress/support/fragments/orders/orderLineDetails.js
cypress/support/fragments/orders/orderStates.js

[C353576](https://foliotest.testrail.io/index.php?/cases/view/353576)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6206/allure)
***

[353576] Edit instance connection of POL (thunderjet) (TaaS)

---

cypress/e2e/finance/funds/view-expense-class-info-on-budget-details.cy.js
cypress/support/fragments/finance/budgets/budgetDetails.js
cypress/support/fragments/finance/financeDetails.js
cypress/support/fragments/finance/funds/fundDetails.js

[C415261](https://foliotest.testrail.io/index.php?/cases/view/415261)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6198/allure)
***

[415261] User can view actual Expense Class information (thunderjet) (TaaS)

---

cypress/e2e/notes/item-notes.cy.js
cypress/support/fragments/inventory/item/itemRecordEdit.js

[C631](https://foliotest.testrail.io/index.php?/cases/view/631)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6325/allure/)

C631 Item notes (folijet) (TaaS)

---

cypress/e2e/title-level-request/check-user-can-see-open-not-yet-filled-accordeon.cy.js
cypress/e2e/title-level-request/user-can-click-reorder-queue.cy.js
cypress/e2e/title-level-request/user-can-see-fulfillment-in-progress.cy.js
cypress/support/fragments/requests/requestDetail.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/347891)
[AllureReport](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6175/allure/)

C347891 Check that user can see Open - Not yet filled accordion (vega) (Taas)

---

cypress/e2e/data-import/settings/check-asterisk-in-existing-mapping-profile.cy.js
cypress/e2e/data-import/settings/check-vendor-mapping-ui.cy.js
cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfileEdit.js
cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfileView.js
cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfiles.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/376970)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6338/allure/)

C376970 Order field mapping profile: Check vendor mapping UI (folijet) (TaaS)

---

cypress/e2e/data-import/settings/verify-default-PO-line-limit-setting.cy.js
cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfileView.js
cypress/support/fragments/data_import/mapping_profiles/newFieldMappingProfile.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/374181)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6331/allure/)

C374181 Verify display of defaulted value for PO line limit setting on Order Field Mapping Profile (folijet) (TaaS)

---

cypress/e2e/settings/data-import/check-details-section-on-switching-record-type.cy.js
cypress/e2e/settings/data-import/check-orders-record-type-on-create-edit-field-mapping-profile.cy.js
cypress/e2e/settings/data-import/check-return-to-default-in-suppress-from-discovery.cy.js
cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileView.js
cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfiles.js
cypress/support/fragments/settings/dataImport/index.js
cypress/support/fragments/settings/dataImport/notifications.js
interactors/decorator.js
interactors/index.js

[C377016](https://foliotest.testrail.io/index.php?/cases/view/377016)
[C377017](https://foliotest.testrail.io/index.php?/cases/view/377017)
[C377018](https://foliotest.testrail.io/index.php?/cases/view/377018)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6341/allure)
***

[377016] Verify the possibility to return to the defaults values (folijet) (TaaS)

---

cypress/e2e/inventory/item-administrative-note.cy.js

[C359149](https://foliotest.testrail.io/index.php?/cases/view/359149)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6344/allure)

C359149 Search "Item" by administrative note using query search (spitfire) (TaaS)

---

cypress/e2e/data-import/settings/remove-default-action-profile.cy.js
cypress/support/fragments/data_import/job_profiles/jobProfileView.js

[TestRail](https://foliotest.testrail.io/index.php?/cases/view/422093)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6326/allure/)

C422093 Verify removal of default action profile from job profile: Default - Create SRS MARC Authority (folijet) (Taas)

---

cypress/e2e/inventory/holdings/holdings-administrative-note.cy.js
cypress/support/fragments/inventory/holdingsRecordEdit.js
cypress/support/fragments/inventory/inventorySearchAndFilter.js

[C359148](https://foliotest.testrail.io/index.php?/cases/view/359148)
[Allure Report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6375/allure)

C359148 Search "Holdings" with source = Folio/MARC by administrative note using query search (spitfire) (TaaS)

---

cypress/e2e/settings/data-import/check-no-error-after-switching-record-type-back.cy.js
cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js
cypress/support/fragments/settings/dataImport/notifications.js

[C375164](https://foliotest.testrail.io/index.php?/cases/view/375164)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6416/allure)
***

[375164] Verify that no error after switching Order type (folijet) (TaaS)

---

cypress/e2e/settings/data-import/check-order-lines-limit-settings-does-not-allow-fractional-numbers.cy.js
cypress/support/fragments/settings/dataImport/fieldMappingProfile/fieldMappingProfileEditForm.js

[C378897](https://foliotest.testrail.io/index.php?/cases/view/378897)
***
[Allure report](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6411/allure)
***

[378897] Order lines limit setting does not allow fractional numbers (folijet) (TaaS)

---

cypress/e2e/data-import/settings/verify-create-inventory-inactive-in-open-order.cy.js
cypress/support/fragments/data_import/mapping_profiles/fieldMappingProfileView.js
cypress/support/fragments/data_import/mapping_profiles/newFieldMappingProfile.js

[TestRail - C380444](https://foliotest.testrail.io/index.php?/cases/view/380444)
[TestRail - C380445](https://foliotest.testrail.io/index.php?/cases/view/380445)
[AllureReport](https://jenkins-aws.indexdata.com/job/folioRancher/job/folioTestingTools/job/runCypressTests/6397/allure/)

C380444-C380445 Order field mapping profile: Create Inventory fields are inactivated when Order status is Open (folijet) (TaaS)
